"""Bind Paper 1's SLOW-LANE manuscript numbers to the archived records that produced them.

`claim_coverage.SLOW_LANE_RESULTS` records, for each slow-lane number in the manuscript, a prose
sentence naming the producer and the archive. That is documentation, not verification: nothing
opens the archive and checks that the manuscript's number is still the archived one. Six review
rounds found stale numbers by hand in exactly this population.

This module closes that gap without rerunning anything. Each binding names a **path into a
committed archive**, and `verify()` resolves it and compares. Rerunning the slow lane is not
required — the archives were written by the runs that produced the manuscript's numbers, so
comparing against them catches the failure mode that actually occurs (the analysis is rerun and the
prose is not updated, or the prose is edited and the analysis is not).

    python -m puckworks.paper_a.slow_lane_bindings          # report
    python -m puckworks.paper_a.slow_lane_bindings --json   # machine-readable

A binding is a `(archive, path, transform)` triple:

* ``archive``  — file under `docs/paper1_resource/`.
* ``path``     — dotted path into the JSON; list indices are numeric segments.
* ``transform``— optional callable applied to the archived value before comparison, for the cases
  where the manuscript legitimately quotes a rounded, signed, or percentage-scaled form.

`rel` / `abs` tolerances exist because the manuscript quotes numbers at display precision. The
tolerance is deliberately tight enough that a genuine drift fails: a value quoted to 2 dp is
checked to 2 dp, not to "close enough".
"""
from __future__ import annotations

import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
ARCHIVE_DIR = REPO / "docs" / "paper1_resource"

OBJECTIVE = "PAPER_A_OBJECTIVE_FAMILY_PANELS.json"
EXTERNAL = "PAPER_A_EXTERNAL_PANEL_LOSSES.json"
ENDPOINT = "PAPER_A_ENDPOINT_PROPAGATION.json"
LOSS = "PAPER_A_COMPARATOR_LOSS_ROBUSTNESS.json"
CORPUS = "PAPER_A_TRANSFER_CORPUS_CONTRACTS.json"
CONVERGENCE = "PAPER_A_NUMERICAL_CONVERGENCE.json"
DIFFUSIVITY = "PAPER_A_DIFFUSIVITY_CLOSURE_AUDIT.json"
#: The committed figure bundle is an archive too: it carries the curvature diagnostics the
#: manuscript quotes, and it is regenerated by the same producers.
PANELS = "../figures/paper_a/results.json"
LOCO_CI = "PAPER_A_LOCO_COVERAGE_INTERVAL.json"


def _abs(v):
    return abs(float(v))


def _pct(v):
    return float(v) * 100.0


#: manuscript token -> (archive, dotted path, transform|None, rel, abs)
#:
#: The manuscript token is the string as it appears in the prose, so the binding is checkable
#: against the audit's own tokenisation rather than against a re-parsed number.
BINDINGS: dict[str, tuple] = {
    # ── endpoint propagation (rows are ordered 38, 40, 42 g; complete 44-record C/F corpus) ───
    "0.447": (ENDPOINT, "rows.0.paired_difference_pp", _abs, 0, 5e-4),
    "0.394": (ENDPOINT, "rows.1.paired_difference_pp", _abs, 0, 5e-4),
    "0.425": (ENDPOINT, "rows.2.paired_difference_pp", _abs, 0, 5e-4),
    "8.39": (ENDPOINT, "rows.0.pooled_model_mape", None, 0, 5e-3),
    "8.44": (ENDPOINT, "rows.1.pooled_model_mape", None, 0, 5e-3),
    "8.41": (ENDPOINT, "rows.2.pooled_model_mape", None, 0, 5e-3),
    "8.83": (ENDPOINT, "rows.1.pooled_const_mape", None, 0, 5e-3),
    "61": (ENDPOINT, "rows.0.n_model_worse_than_const", None, 0, 0),
    "62": (ENDPOINT, "rows.1.n_model_worse_than_const", None, 0, 0),
    "60": (ENDPOINT, "rows.2.n_model_worse_than_const", None, 0, 0),
    "132": (ENDPOINT, "rows.1.n_points", None, 0, 0),
    # corpus contract (round-7 P0-3): the declared record counts are bound to the emitted
    # sample-ID manifest, so "all 44 records" cannot drift away from what was scored.
    "44": (ENDPOINT, "corpus.n_held_out_records", None, 0, 0),
    "36": (ENDPOINT, "corpus.n_lookup_observations", lambda v: float(v) / 3.0, 0, 0),

    # ── PDE discretisation convergence ────────────────────────────────────────────────────────
    "0.0004": (CONVERGENCE, "worst_case_rel_dev_pct.whole_cup", None, 0, 5e-5),
    "0.0013": (CONVERGENCE, "worst_case_rel_dev_pct.late_fraction", None, 0, 5e-5),
    "0.0204": (CONVERGENCE, "worst_case_rel_dev_pct.range_ratio", None, 0, 5e-5),
    "1458": (CONVERGENCE, "solver_health.total_solves", None, 0, 0),
    "400": (CONVERGENCE, "node_counts.2", None, 0, 0),

    # ── objective family: rate at the profiled minimum, per panel and objective ───────────────
    "0.66": (OBJECTIVE, "panels.Arabica:caffeine.objective_family.sse.rate_at_min",
             None, 0, 5e-3),
    "0.86": (OBJECTIVE, "panels.Arabica:caffeine.objective_family.huber.rate_at_min",
             None, 0, 5e-3),
    "0.44": (OBJECTIVE, "panels.Robusta:trigonelline.objective_family.sse.rate_at_min",
             None, 0, 5e-3),
    "0.50": (OBJECTIVE, "panels.Robusta:trigonelline.objective_family.huber.rate_at_min",
             None, 0, 5e-3),
    "3.79": (OBJECTIVE, "panels.Arabica:trigonelline.objective_family.sse.rate_at_min",
             None, 0, 5e-3),
    "29": (OBJECTIVE, "n_rate_grid", None, 0, 0),

    # ── endpoint propagation: clustered percentile ranges, per endpoint ───────────────────────
    # The manuscript quotes these as bracket endpoints; bind each bound separately so a change to
    # either end fails rather than averaging out.
    # loco_coverage_interval, archived 2026-07-28. This was the ONLY slow-lane value with no
    # machine-readable record anywhere; the producer now writes one and it reproduces the prose
    # exactly (7.38 -> 7.4, [4.34, 11.48] -> [4.3, 11.5], 599 of 600 effective draws).
    "7.4": (LOCO_CI, "oob_pooled_mape_point", None, 0, 5e-2),
    "4.3": (LOCO_CI, "coverage_interval95.0", None, 0, 5e-2),
    "11.5": (LOCO_CI, "coverage_interval95.1", None, 0, 5e-2),
    # PRIMARY unit (variety, T, p). Bound through the schema-v2 `resampling.<scheme>.interval`
    # path rather than the flat alias, so a binding names the scheme it checks. Each bound is
    # bound separately, so a change to either end fails.
    #
    # Round-8 P1-2 moved these: the canonical draw count rose from B = 8000 to B = 1,000,000 after
    # a multi-seed audit showed the 40 g upper bound's fourth decimal was Monte Carlo noise. The
    # bound is now reliably +0.004, so the primary range CONTAINS zero at 40 g and 42 g.
    "0.884": (ENDPOINT, "rows.0.resampling.cond_in_variety.interval.display.lower", _abs, 0, 5e-4),
    "0.042": (ENDPOINT, "rows.0.resampling.cond_in_variety.interval.display.upper", _abs, 0, 5e-4),
    "0.829": (ENDPOINT, "rows.1.resampling.cond_in_variety.interval.display.lower", _abs, 0, 5e-4),
    "0.891": (ENDPOINT, "rows.2.resampling.cond_in_variety.interval.display.lower", _abs, 0, 5e-4),
    # secondary units, retained as sensitivities. `sample_in_variety_grind` is new in round 8: one
    # cluster per coffee sample record, the dependency the source establishes most directly.
    "0.740": (ENDPOINT, "rows.1.resampling.cond_in_group.interval.display.lower", _abs, 0, 5e-4),
    "0.039": (ENDPOINT, "rows.1.resampling.cond_in_group.interval.display.upper", _abs, 0, 5e-4),
    "0.863": (ENDPOINT, "rows.1.resampling.group.interval.display.lower", _abs, 0, 5e-4),
    "0.024": (ENDPOINT, "rows.1.resampling.group.interval.display.upper", _abs, 0, 5e-4),
    "0.742": (ENDPOINT, "rows.1.resampling.sample_in_variety_grind.interval.display.lower",
              _abs, 0, 5e-4),
    "0.053": (ENDPOINT, "rows.1.resampling.sample_in_variety_grind.interval.display.upper",
              _abs, 0, 5e-4),
    # round-8: the widths the Results paragraph compares, the signed knife-edge bound, and the
    # Monte Carlo standard error that says how far the third decimal is actually resolved.
    "0.833": (ENDPOINT, "rows.1.resampling.cond_in_variety.interval.width_pp", None, 0, 5e-4),
    "0.689": (ENDPOINT, "rows.1.resampling.sample_in_variety_grind.interval.width_pp",
              None, 0, 5e-4),
    "0.702": (ENDPOINT, "rows.1.resampling.cond_in_group.interval.width_pp", None, 0, 5e-4),
    "0.0038": (ENDPOINT, "rows.1.resampling.cond_in_variety.interval.full_precision_pp.upper",
               _abs, 0, 5e-5),
    "0.006": (ENDPOINT, "rows.2.resampling.cond_in_variety.interval.display.upper", _abs, 0, 5e-4),
    # Round-9 P1-1: the audit moved from one top-level scalar to a target-keyed list, and the
    # prose now quotes BOTH bound standard errors rather than one symmetric value.
    "0.000466": (ENDPOINT, "stability_audits.0.upper_monte_carlo_se_at_canonical_B_pp",
                 None, 0, 5e-7),
    "0.000520": (ENDPOINT, "stability_audits.0.lower_monte_carlo_se_at_canonical_B_pp",
                 None, 0, 5e-7),
    "78": (ENDPOINT, "resampling_design.schemes.cond_in_group.n_clusters", None, 0, 0.5),
    # comparator loss robustness (round-7 P1-2): both predictors refit under the alternative loss
    "0.393": (LOSS, "rows.1.paired_difference_pp", _abs, 0, 5e-4),
    # the matched on-grid subset, reported as the secondary corpus (round-7 P0-3)
    "0.361": (CORPUS, "matched_on_grid.paired_difference_pp", _abs, 0, 5e-4),
    "8.23": (CORPUS, "matched_on_grid.pooled_model_mape", None, 0, 5e-3),
    "8.59": (CORPUS, "matched_on_grid.pooled_const_mape", None, 0, 5e-3),
    "9.39": (CORPUS, "complete_corpus.off_grid_only.model_mape", None, 0, 5e-3),
    "9.93": (CORPUS, "complete_corpus.off_grid_only.const_mape", None, 0, 5e-3),
    "0.545": (CORPUS, "complete_corpus.off_grid_only.paired_difference_pp", _abs, 0, 5e-4),
    "4.5": (CORPUS, "complete_corpus.skill_vs_const", _pct, 0, 5e-2),
    "8.50": (LOSS, "rows.1.pooled_model_mape", None, 0, 5e-3),
    "8.89": (LOSS, "rows.1.pooled_const_mape", None, 0, 5e-3),
    "0.826": (LOSS, "rows.1.interval.display.lower", _abs, 0, 5e-4),
    "0.004": (LOSS, "rows.1.interval.display.upper", _abs, 0, 5e-4),

    # ── objective family: relative-L2 minimum ─────────────────────────────────────────────────
    "0.58": (OBJECTIVE, "panels.Arabica:caffeine.objective_family.relative_l2.rate_at_min",
             None, 0, 5e-3),

    # ── diffusivity closure: the degeneracy check the round-4 audit archived ──────────────────
    "1.43": (DIFFUSIVITY,
             "numerical_check_arabica_caffeine_optimal_grind.profile_range_ratio.source_closure",
             None, 0, 5e-3),
    "1.45": (DIFFUSIVITY,
             "numerical_check_arabica_caffeine_optimal_grind.profile_range_ratio.solvent_MW",
             None, 0, 5e-3),
    "2.84": (DIFFUSIVITY,
             "numerical_check_arabica_caffeine_optimal_grind.minimum_MAPE_pct.source_closure",
             None, 0, 5e-3),

    # ── external dissolved-solids panel ───────────────────────────────────────────────────────
    "1900": (PANELS, "panel_caffeine.condition_number", None, 0.03, 0),
    "3600": (PANELS, "panel_trigonelline.condition_number", None, 0.03, 0),
    "0.99": (PANELS, "panel_caffeine.local_curvature_coupling", _abs, 0, 5e-3),
    "5.1": (PANELS, "loco.condition_cluster_resampling95.0", None, 0, 5e-2),
    "8.3": (PANELS, "loco.condition_cluster_resampling95.1", None, 0, 5e-2),
    # The flow-map perturbation DOES write a record -- the committed figure bundle carries every
    # perturbation. These two were declared unbindable on the assumption that it did not.
    "0.71": (PANELS, ("flow_map_sensitivity_transfer", "per_perturbation", "-0.2", "fitted_rate"),
             None, 0, 5e-3),
    "0.88": (PANELS, ("flow_map_sensitivity_transfer", "per_perturbation", "0.0", "fitted_rate"),
             None, 0, 5e-3),
    "0.6": (PANELS, "geometry_sensitivity.max_geometry_spread_pp", None, 0, 5e-2),
    "2000": (PANELS, "identifiability_convergence.rows.3.condition_number", None, 0.02, 0),
    "2100": (PANELS, "identifiability_convergence.rows.1.condition_number", None, 0.02, 0),
    "2.6": (DIFFUSIVITY,
            "numerical_check_arabica_caffeine_optimal_grind.argmin_ratio_predicted", None, 0, 0.4),
}

#: Bindings deliberately NOT attempted, with the reason. Recorded so the gap is visible rather
#: than absent: an unlisted, unbound number looks identical to one nobody has looked at.
UNBINDABLE: dict[str, str] = {}
#: EMPTY as of 2026-07-28. Every slow-lane value the manuscript quotes now resolves against a
#: record. Of the eight originally declared unbindable, five were archived all along and merely
#: described in a way that pointed at the wrong producer; only `loco_coverage_interval` genuinely
#: lacked a record, and it now writes one.

#: Values whose two appearances in the manuscript differ only by ROUNDING, recorded so the choice
#: is made once rather than rediscovered. Not conflicts between runs.
ROUNDING_AMBIGUITIES: dict[str, str] = {
    "rendering policy for the clustered percentile ranges": (
        "THREE decimal places, everywhere the interval appears -- main text, Supplementary "
        "Table S3, every reading, every caption -- all rendered from PAPER_A_ENDPOINT_PROPAGATION "
        "by `tools/paper_a_supplement.py`. Round-7 P1-6: the earlier policy was stated as three "
        "SIGNIFICANT FIGURES and the SI still displayed two decimals, so an audit asserting "
        "uniform precision was contradicted by the committed package. Two decimals is not enough "
        "here: the primary range's upper bound at the 40 g endpoint is -0.0004 pp, which two "
        "decimals renders as -0.00 and three as +0.000, and the difference between those two "
        "renderings is the difference between claiming a resolved effect and not."),
    "negative zero": (
        "`paired_clustered_bootstrap` rounds its bounds BEFORE deciding `excludes_zero`, and "
        "normalises IEEE -0.0 to +0.0, so the archived flag and the archived interval can never "
        "disagree. `nearest_bound_to_zero_pp` carries the distance as a quantity, because at this "
        "effect size a boolean that flips on the fourth decimal is not a finding."),
}


#: Claims of the form "smallest/largest X across the swept cases" cannot be a fixed path -- the
#: extremum may move between cases when the analysis is rerun, and pinning today's argmax would
#: silently stop checking the claim. These resolve by COMPUTING the extremum over the archive.
def _extremum(field: str, how):
    def f(doc):
        return how(v[field] for v in doc["per_case"].values())
    return f


def _pc(solute: str, field: str):
    """A scalar field of the positive-control producer, per solute."""
    def f(doc):
        return doc["positive_control"]["per_solute"][solute][field]
    return f


def _pc_min(solute: str, field: str):
    """Minimum of a positive-control series over the swept rates."""
    def f(doc):
        return min(doc["positive_control"]["per_solute"][solute][field])
    return f


def _set_fraction(how):
    """min/max of the 10 % near-optimal set fraction across every panel x objective, as a %."""
    def f(doc):
        # Iterate the DECLARED objectives, not every key: `objective_family` also carries a scalar
        # `huber_delta` beside the three objective dicts, and .values() would sweep it in.
        objectives = doc["objectives"]
        return how(p["objective_family"][o]["sets"]["10pct"]["frac_within"]
                   for p in doc["panels"].values()
                   for o in objectives) * 100.0
    return f


DERIVED: dict[str, tuple] = {
    # "smallest / largest 10 %-set fraction across panels x objectives" -- an extremum over 18
    # cells, so it must be computed, not pinned to whichever cell happens to hold it today.
    # "spread of the paired difference across 38/40/42 g" is a RANGE over the three rows; pinning
    # it to a row would stop checking the claim the moment the extremes swapped endpoints.
    "0.053": (ENDPOINT,
             lambda d: (max(abs(r["paired_difference_pp"]) for r in d["rows"])
                        - min(abs(r["paired_difference_pp"]) for r in d["rows"])), 0, 5e-3),
    # "lowest / highest per solute x variety held-out median" -- an extremum over the six groups.
    "2.8": (PANELS, lambda d: min(v["loco_median"] for v in d["loco"]["per_fit"].values()),
            0, 5e-2),
    "8.8": (PANELS, lambda d: max(v["loco_median"] for v in d["loco"]["per_fit"].values()),
            0, 5e-2),
    # POSITIVE CONTROL, not full_cup_sim. These seven were labelled "full-cup sim:" in
    # SLOW_LANE_RESULTS, which sent a reader (and this module's author) to the wrong producer --
    # `full_cup_sim` holds none of them. They come from `positive_control`
    # (idn.identifiability_fractions_vs_cup) and every one matches. Minima are computed over the
    # swept rates rather than pinned to an index, so the binding survives a re-sweep.
    "6.0": (PANELS, _pc_min("caffeine", "fraction_mape"), 0, 5e-2),
    "10.0": (PANELS, _pc_min("trigonelline", "fraction_mape"), 0, 5e-2),
    "3.6": (PANELS, _pc_min("trigonelline", "sampled_agg_mape"), 0, 5e-2),
    "4.1": (PANELS, _pc("caffeine", "frac_range_ratio"), 0, 5e-2),
    "4.4": (PANELS, _pc("trigonelline", "frac_range_ratio"), 0, 5e-2),
    "1.4": (PANELS, _pc("caffeine", "sampled_agg_range_ratio"), 0, 5e-2),
    "1.2": (PANELS, _pc("trigonelline", "sampled_agg_range_ratio"), 0, 5e-2),
    # The worst individual LOCO fold. Declared unbindable on the assumption that the producer
    # archives only pooled and per-group summaries; it archives per-group RANGES, whose upper
    # end is exactly this. Derived over all six groups so it follows the worst fold.
    "32.7": (PANELS,
             lambda d: max(v["loco_range"][1] for v in d["loco"]["per_fit"].values()), 0, 5e-2),
    # Tolerance sweep. Declared unbindable as having "no committed archive of any kind"; the
    # bundle carries `transfer.threshold_sensitivity` for all six panels. The values are the
    # ARABICA-CAFFEINE panel (8.48, 9.69), not a cross-panel aggregate -- the description omitted
    # which panel, which is why they read as unarchived.
    "9.2": (PANELS, lambda d: d["transfer"]["threshold_sensitivity"]["Arabica:caffeine"]
            ["2pct"]["worst_heldout_mape"], 0, 5e-2),
    "10.5": (PANELS, lambda d: d["transfer"]["threshold_sensitivity"]["Arabica:caffeine"]
            ["20pct"]["worst_heldout_mape"], 0, 5e-2),
    "21.8": (PANELS, lambda d: d["transfer"]["manifold_worst_heldout_mape"], 0, 5e-2),
    "18.0": (PANELS, lambda d: d["transfer"]["point_worst_heldout_mape"], 0, 5e-2),
    "31": (OBJECTIVE, _set_fraction(min), 0, 0.5),
    "100": (OBJECTIVE, _set_fraction(max), 0, 0.5),
    # (archive, callable over the whole document, rel, abs)
    "1.19": (EXTERNAL, _extremum("fraction_range_ratio_nrmse", min), 0, 5e-3),
    "1.30": (EXTERNAL, _extremum("fraction_range_ratio_nrmse", max), 0, 5e-3),
    "1.64": (EXTERNAL, _extremum("fraction_range_ratio", min), 0, 5e-3),
    "2.07": (EXTERNAL, _extremum("fraction_range_ratio", max), 0, 5e-3),
    "57": (EXTERNAL, _extremum("fraction_min_nrmse", min), 0, 0.5),
    "75": (EXTERNAL, _extremum("fraction_min_nrmse", max), 0, 0.5),
}


def _resolve(doc, path):
    """Resolve a dotted path, or a tuple of segments.

    A tuple is required whenever a key CONTAINS a dot -- the flow-map perturbation is keyed by the
    fractional scale ("-0.2", "0.0"), which a dotted string would split into nonsense.
    """
    cur = doc
    for seg in (path if isinstance(path, tuple) else path.split(".")):
        if isinstance(cur, list):
            cur = cur[int(seg)]
        else:
            cur = cur[seg]
    return cur


#: Values that are module constants rather than archived results. Binding to the code is stronger
#: than binding to an archive: the manuscript is then checked against the thing that actually runs.
CODE_CONSTANTS: dict[str, tuple] = {
    "194.19": ("puckworks.models.pannusch2024.closures", "SOLUTES", ("caffeine", "M"), 5e-3),
    "137.14": ("puckworks.models.pannusch2024.closures", "SOLUTES", ("trigonelline", "M"), 5e-3),
    "354.31": ("puckworks.models.pannusch2024.closures", "SOLUTES", ("5CQA", "M"), 5e-3),
    "0.17": ("puckworks.models.pannusch2024.solver", "ALPHA_L", None, 5e-3),
}


def _code_value(module: str, attr: str, key):
    import importlib

    obj = getattr(importlib.import_module(module), attr)
    if key is None:
        return float(obj)
    for seg in (key if isinstance(key, tuple) else (key,)):
        obj = obj[seg]
    return float(obj)


def verify() -> dict:
    """Resolve every binding against its archive. Returns a report; never raises on a mismatch."""
    cache: dict[str, dict] = {}
    ok, mismatched, unresolvable = [], [], []
    for token, (module, attr, key, abs_) in sorted(CODE_CONSTANTS.items()):
        try:
            value = _code_value(module, attr, key)
        except Exception as exc:                                    # noqa: BLE001
            unresolvable.append((token, module, attr, f"{type(exc).__name__}: {exc}"))
            continue
        if abs(float(token) - value) <= float(abs_):
            ok.append((token, module, attr, value))
        else:
            mismatched.append((token, module, attr, value, float(token) - value))

    for token, (archive, fn, rel, abs_) in sorted(DERIVED.items()):
        try:
            if archive not in cache:
                cache[archive] = json.loads((ARCHIVE_DIR / archive).read_text(encoding="utf-8"))
            value = float(fn(cache[archive]))
        except Exception as exc:                                    # noqa: BLE001
            unresolvable.append((token, archive, "<derived>", f"{type(exc).__name__}: {exc}"))
            continue
        claimed = float(token)
        if abs(claimed - value) <= max(float(abs_), float(rel) * abs(value)):
            ok.append((token, archive, "<derived>", value))
        else:
            mismatched.append((token, archive, "<derived>", value, claimed - value))

    for token, (archive, path, transform, rel, abs_) in sorted(BINDINGS.items()):
        try:
            if archive not in cache:
                cache[archive] = json.loads(
                    (ARCHIVE_DIR / archive).read_text(encoding="utf-8"))
            value = _resolve(cache[archive], path)
            if transform is not None:
                value = transform(value)
            value = float(value)
        except Exception as exc:                                    # noqa: BLE001
            unresolvable.append((token, archive, path, f"{type(exc).__name__}: {exc}"))
            continue
        claimed = float(token)
        tol = max(float(abs_), float(rel) * abs(value))
        if abs(claimed - value) <= tol:
            ok.append((token, archive, path, value))
        else:
            mismatched.append((token, archive, path, value, claimed - value))
    return dict(n_bound=len(BINDINGS) + len(DERIVED) + len(CODE_CONSTANTS), n_ok=len(ok), n_mismatched=len(mismatched),
                n_unresolvable=len(unresolvable), n_declared_unbindable=len(UNBINDABLE),
                ok=ok, mismatched=mismatched, unresolvable=unresolvable)


def main(argv=None) -> int:                                          # pragma: no cover
    import sys
    argv = sys.argv[1:] if argv is None else list(argv)
    r = verify()
    if "--json" in argv:
        print(json.dumps({k: v for k, v in r.items() if not isinstance(v, list)}, indent=2))
        return 1 if (r["n_mismatched"] or r["n_unresolvable"]) else 0
    print(f"slow-lane bindings: {r['n_ok']}/{r['n_bound']} resolve and match; "
          f"{r['n_mismatched']} mismatched; {r['n_unresolvable']} unresolvable; "
          f"{r['n_declared_unbindable']} declared unbindable")
    for token, archive, path, value, delta in r["mismatched"]:
        print(f"  MISMATCH {token:>10}  {archive}:{path}  archived {value!r}  delta {delta:+.6g}")
    for token, archive, path, why in r["unresolvable"]:
        print(f"  UNRESOLVABLE {token:>10}  {archive}:{path}  {why}")
    return 1 if (r["n_mismatched"] or r["n_unresolvable"]) else 0


if __name__ == "__main__":                                           # pragma: no cover
    raise SystemExit(main())
