"""PR-03a — the fixed-positive-time singular limit, its assumptions, and the producer contract.

The proposition is in `docs/paper1_resource/PAPER_A_FIXED_TIME_SINGULAR_LIMIT_PROPOSITION.md`. These
tests do three separable things, because the previous single verdict fused them:

* **algebraic fixtures** — small systems where the right answer is known in closed form, used to
  show that each assumption test rejects what it is supposed to reject. A test that only ever sees
  the 27 real cells cannot demonstrate that;
* **construction fixtures** — the endpoint checks, exercised on hand-built degenerate inputs;
* **producer behaviour** — exit codes, `--check` drift detection, provenance, and the standing
  prohibition on campaign coupling.

Everything here runs on synthetic matrices or on the committed archive. Nothing recomputes the 27
cells, so this module stays inside the quick-gate budget.
"""
from __future__ import annotations

import json
import pathlib
import sys

import numpy as np
import pytest
from scipy.linalg import block_diag, expm

_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from tools import paper_a_endpoint_construction as EC   # noqa: E402

ARCHIVE = _ROOT / "docs" / "paper1_resource" / "PAPER_A_ENDPOINT_CONSTRUCTION.json"
PROOF = _ROOT / "docs" / "paper1_resource" / "PAPER_A_FIXED_TIME_SINGULAR_LIMIT_PROPOSITION.md"


@pytest.fixture(scope="module")
def archive():
    assert ARCHIVE.exists(), "the PR-03a archive is missing; it must be generated by the producer"
    return json.loads(ARCHIVE.read_text(encoding="utf-8"))


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 1. Algebraic fixtures — assumption (A2), semisimple zero
# ═════════════════════════════════════════════════════════════════════════════════════════════

JORDAN2 = np.array([[0.0, 1.0], [0.0, 0.0]])
JORDAN3 = np.array([[0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 0.0]])


def test_a_semisimple_zero_with_a_stable_fast_block_passes():
    A1 = block_diag(np.zeros((2, 2)), np.diag([-1.0, -2.0, -3.0]))
    r = EC.semisimplicity(A1, 3)
    assert r["semisimple"] is True
    assert r["failure_reason"] is None
    assert r["nullity"] == 2


@pytest.mark.parametrize("jordan,rank,name", [(JORDAN2, 3, "Jordan-2"), (JORDAN3, 4, "Jordan-3")])
def test_a_defective_zero_is_rejected(jordan, rank, name):
    """The kernel grows under squaring exactly when the zero eigenvalue is defective."""
    A1 = block_diag(jordan, np.diag([-1.0, -2.0]))
    r = EC.semisimplicity(A1, rank)
    assert r["semisimple"] is False, name
    assert "DEFECTIVE" in r["failure_reason"], (name, r["failure_reason"])


@pytest.mark.parametrize("scale", [1e6, 1e9, 1e12])
def test_a_scale_separated_defective_zero_is_rejected(scale):
    """The review's counterexample: the withdrawn largest-gap rule called this semisimple.

    For `block_diag(Jordan2(0), [-1e9])` the singular values are `[1e9, 1, 0]` and `[1e18, 0, 0]`,
    so the globally largest gap sits between the fast block and the Jordan singular value rather
    than at the true nonzero/zero cut. Verifying at the DECLARED cut rejects it.
    """
    A1 = block_diag(JORDAN2, [[-scale]])
    r = EC.semisimplicity(A1, 2)                       # true rank(A1) = 2
    assert r["semisimple"] is False, scale
    assert "DEFECTIVE" in r["failure_reason"], (scale, r["failure_reason"])

    # and the withdrawn rule is shown to have been wrong here, not merely replaced
    w = r["withdrawn_largest_gap_rule"]
    if scale >= 1e9:
        assert w["rank_A1"] == w["rank_A1_squared"] == 1, (
            "the withdrawn rule reported equal ranks and would have called this semisimple")


def test_a_scale_separated_defective_jordan3_is_rejected():
    A1 = block_diag(JORDAN3, np.diag([-1e9, -2e9]))
    r = EC.semisimplicity(A1, 4)
    assert r["semisimple"] is False
    assert "DEFECTIVE" in r["failure_reason"]


@pytest.mark.parametrize("declared", [2, 4])
def test_a_wrong_declared_rank_fails_closed(declared):
    """Declaring the wrong structural rank must never produce a pass."""
    A1 = block_diag(np.zeros((2, 2)), np.diag([-1.0, -2.0, -3.0]))     # true rank 3
    assert EC.semisimplicity(A1, declared)["semisimple"] is False


def test_an_undecidable_rank_is_reported_as_such_not_as_defective():
    """A huge internal scale ratio makes rank(A1^2) undecidable in double precision.

    That is a different failure from a defective kernel and is reported differently. Both fail
    closed; conflating them would hide which one occurred.
    """
    A1 = block_diag(np.zeros((2, 2)), np.diag([-1.0, -1e9]))           # genuinely semisimple
    r = EC.semisimplicity(A1, 2)
    assert r["semisimple"] is False
    assert "not numerically decidable" in r["failure_reason"]
    assert "DEFECTIVE" not in r["failure_reason"]


@pytest.mark.parametrize("bad_source", ["null_basis", "schur"])
def test_disagreement_between_rank_sources_fails_closed(bad_source):
    """Four routines compute the same integer by different means; any disagreement is not_assured."""
    ok = EC.rank_agreement(400, 400, 400, True, True)
    assert ok["agreement_ok"] is True and ok["all_sources_agree"] is True
    bad = (EC.rank_agreement(400, 399, 400, True, True) if bad_source == "null_basis"
           else EC.rank_agreement(400, 400, 401, True, True))
    assert bad["all_sources_agree"] is False and bad["agreement_ok"] is False


def test_agreement_fails_closed_on_semisimplicity_or_slow_pairing():
    assert EC.rank_agreement(400, 400, 400, False, True)["agreement_ok"] is False
    assert EC.rank_agreement(400, 400, 400, True, False)["agreement_ok"] is False


def test_the_structural_rank_is_declared_from_the_model_not_discovered():
    st = EC.structural_rank(nz=200)
    assert st["expected_fast_rank"] == 400 and st["expected_slow_nullity"] == 201
    assert st["state_dimension"] == 601
    assert "2*nz" in st["derivation"]


def test_the_largest_gap_rule_is_retained_only_as_a_diagnostic():
    """It decides nothing. Kept so the archive records what the withdrawn rule said."""
    rank, gap = EC._largest_gap_rank(np.array([1e9, 1.0, 0.0]))
    assert (rank, gap > 1e8) == (1, True), "this is exactly the wrong answer, hence diagnostic only"


def test_the_rank_is_verified_at_a_declared_cut_not_taken_from_a_threshold():
    """Regression: the threshold form reported the noise floor, not the operator.

    On one real cell (trigonelline, 88 C, 6 bar) the singular spectrum separates by ~1.9e13 — there
    is no ambiguity about the rank — yet the discarded value sits at 0.106x the base tolerance, so a
    10x TIGHTER tolerance pushed it back above the cut and the cell was reported non-semisimple.
    The verdict was measuring the tolerance. It is now taken from the gap.
    """
    s = np.array([6.4, 6.4, 6.2, 3.2e-13, 4.9e-14, 4.8e-14])
    ratio, separated, decidable = EC._separation_at(s, 3)
    assert separated and decidable and ratio > 1e12

    # the straddle is exhibited on the real cell that triggered it, not on a toy
    cell = _cell_of(json.loads(ARCHIVE.read_text(encoding="utf-8")), "trigonelline", 88.0, 6.0)
    semis = cell["assumptions"]["A2_semisimple_zero"]
    family = semis["rank_under_tolerance_family"]
    assert family["x0.1"]["rank_A1"] != family["x1"]["rank_A1"], (
        "this cell is the regression: a 10x tighter threshold moves the reported rank")
    assert semis["separation_at_expected_cut_A1"] > 1e12, "while the separation is unambiguous"
    assert semis["semisimple"] is True, "so the assumption holds and the threshold form was wrong"


def _cell_of(archive, solute, T_degC, p_bar):
    for c in archive["cells"]:
        if (c["solute"], c["T_degC"], c["p_bar"]) == (solute, T_degC, p_bar):
            return c
    raise AssertionError("cell not found: %s %s %s" % (solute, T_degC, p_bar))


def test_a_smoothly_decaying_spectrum_has_no_clean_cut():
    """No declared cut in a smooth spectrum separates by the required ratio."""
    s = np.geomspace(1.0, 1e-4, 12)
    for r in range(1, len(s)):
        _, separated, _ = EC._separation_at(s, r)
        assert separated is False, r


def test_a_full_rank_cut_separates_trivially():
    ratio, separated, decidable = EC._separation_at(np.array([3.0, 2.0, 1.0]), 3)
    assert separated and decidable and ratio == float("inf")


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 2. Algebraic fixtures — assumption (A3), stable fast spectrum
# ═════════════════════════════════════════════════════════════════════════════════════════════


def test_a_stable_fast_spectrum_passes_and_reports_its_margin():
    A1 = block_diag(np.zeros((2, 2)), np.diag([-1.0, -4.0]))
    spec, W, F = EC.fast_spectrum(A1)
    assert spec["all_fast_modes_strictly_stable"] is True
    assert spec["fast_mode_count"] == 2
    assert spec["max_real_fast_eigenvalue"] == pytest.approx(-1.0)
    assert W.shape[1] == 2 and F.shape == (2, 2)


def test_an_unstable_fast_eigenvalue_is_rejected():
    A1 = block_diag(np.zeros((2, 2)), np.diag([-1.0, +0.5]))
    spec, _, _ = EC.fast_spectrum(A1)
    assert spec["all_fast_modes_strictly_stable"] is False
    assert spec["max_real_fast_eigenvalue"] > 0


def test_a_zero_decay_margin_is_rejected():
    """Purely imaginary fast modes have zero decay margin: the limit does not exist."""
    A1 = block_diag(np.zeros((2, 2)), np.array([[0.0, 1.0], [-1.0, 0.0]]))
    spec, _, _ = EC.fast_spectrum(A1)
    assert spec["all_fast_modes_strictly_stable"] is False
    assert spec["max_real_fast_eigenvalue"] == pytest.approx(0.0, abs=1e-12)


@pytest.mark.parametrize("fast,label", [
    (np.diag([-1.0, -2.0]), "normal"),
    (np.array([[-1.0, 60.0], [0.0, -2.0]]), "strongly nonnormal"),
])
def test_normal_and_strongly_nonnormal_stable_fast_blocks_both_pass(fast, label):
    A1 = block_diag(np.zeros((2, 2)), fast)
    spec, _, F = EC.fast_spectrum(A1)
    assert spec["all_fast_modes_strictly_stable"] is True, label
    c = EC.lemma3_constants(F, np.zeros_like(F))
    assert c["applicable"] is True
    # nonnormality inflates M but must not destroy the bound
    assert c["M_decay_constant"] >= 1.0 and c["gamma_decay_rate"] > 0.0


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 3. The Lemma 3 bound and the theorem itself, on a fixture where the answer is known
# ═════════════════════════════════════════════════════════════════════════════════════════════


def _fixture():
    """Two slow coordinates, two fast, with nontrivial A0 slow-fast coupling both ways."""
    A1 = block_diag(np.zeros((2, 2)), np.array([[-1.0, 3.0], [0.0, -2.0]]))
    A0 = np.array([
        [-0.3, 0.2, 0.7, -0.1],     # A_ss | A_sf
        [0.1, -0.4, -0.2, 0.5],
        [0.6, -0.3, -0.2, 0.4],     # A_fs | A_ff
        [-0.2, 0.8, 0.3, -0.1],
    ])
    return A0, A1


def test_the_lemma3_bound_holds_with_its_derived_constants():
    """||exp((kappa F + A_ff) t)|| <= M exp(-gamma kappa t) for kappa >= kappa_0, as derived."""
    A0, A1 = _fixture()
    _, W, F = EC.fast_spectrum(A1)
    N, L, _, _ = EC.null_bases(A1)
    V = np.hstack([N, W])
    Mt = np.linalg.inv(V)[N.shape[1]:, :]
    A_ff = (Mt @ A0 @ W).real
    c = EC.lemma3_constants(F, A_ff)
    assert c["applicable"] is True

    M, gam, k0 = c["M_decay_constant"], c["gamma_decay_rate"], c["kappa_0_threshold"]
    for kappa in (k0, 2 * k0, 10 * k0):
        for t in (0.0, 0.05, 0.2, 1.0):
            lhs = np.linalg.norm(expm((kappa * F + A_ff) * t), 2)
            assert lhs <= M * np.exp(-gam * kappa * t) * (1 + 1e-9), (kappa, t, lhs)


def test_the_endpoint_is_the_fixed_positive_time_limit():
    """The theorem, checked numerically where the limit is known in closed form."""
    A0, A1 = _fixture()
    N, L, _, _ = EC.null_bases(A1)
    A_s = (L.conj().T @ A0 @ N).real
    T = 0.7
    z0 = np.array([1.0, -0.5, 0.8, 0.3])          # deliberately OFF the slow manifold
    target = N @ expm(A_s * T) @ (L.conj().T @ z0)

    kappas = [1e2, 1e3, 1e4, 1e5, 1e6]
    errs = [np.linalg.norm(expm((A0 + k * A1) * T) @ z0 - target) for k in kappas]
    for a, b in zip(errs, errs[1:]):
        assert b < a, errs                         # monotone convergence at fixed T
    # first-order O(1/kappa) behaviour FOR THIS FIXTURE: a decade of kappa buys a decade of error.
    # This demonstrates the rate; it does not verify an unscaled universal C_T/kappa bound, and the
    # earlier wording that claimed it did was wrong.
    for a, b in zip(errs, errs[1:]):
        assert b / a == pytest.approx(0.1, rel=0.05), errs
    assert errs[-1] < 1e-6


def test_the_residual_is_homogeneous_of_degree_one_in_the_initial_state():
    """The withdrawn bound failed exactly this: scaling z0 moved the left side, not the right.

    r_kappa(T) is linear in z0, so replacing z0 by alpha*z0 must multiply the residual by |alpha|
    exactly. A bound whose first term is a bare C_T/kappa cannot be right, because it does not move.
    """
    A0, A1 = _fixture()
    N, L, P, _ = EC.null_bases(A1)
    A_s = (L.conj().T @ A0 @ N).real
    T, kappa = 0.7, 1e4
    z0 = np.array([1.0, -0.5, 0.8, 0.3])

    def residual(z):
        return np.linalg.norm(expm((A0 + kappa * A1) * T) @ z
                              - N @ expm(A_s * T) @ (L.conj().T @ z))

    base = residual(z0)
    assert base > 0
    for alpha in (0.5, 2.0, -3.0, 1e3):
        assert residual(alpha * z0) == pytest.approx(abs(alpha) * base, rel=1e-9), alpha

    # ...and so are both terms of the corrected bound, since ||z0|| and ||Q z0|| scale identically
    Qz0 = z0 - P @ z0
    for alpha in (0.5, 2.0, 1e3):
        assert np.linalg.norm(alpha * z0) == pytest.approx(abs(alpha) * np.linalg.norm(z0))
        assert np.linalg.norm(alpha * z0 - P @ (alpha * z0)) == pytest.approx(
            abs(alpha) * np.linalg.norm(Qz0))


def test_the_proposition_states_a_bound_homogeneous_in_z0():
    """The displayed 'Moreover' clause must carry ||z0||, not a bare C_T/kappa."""
    text = PROOF.read_text(encoding="utf-8")
    assert "(C_T / κ) ‖z0‖" in text
    assert "independent of `z0`" in text
    assert "K_T := (2M/γ) [ ‖Mᵀ‖ + c T e^{aT} ‖Lᵀ‖ ]" in text
    assert "‖ r_κ(T) ‖  ≤  C_T / κ  +" not in text, "the withdrawn non-homogeneous form is back"


def test_convergence_is_not_uniform_at_zero_for_off_manifold_data():
    """z_kappa(0) - P z0 = Q z0, independent of kappa. No uniform O(1/kappa) bound on [0,T].

    This is the error the superseded full-state bound archive made, and the proposition rejects it
    explicitly. Here it is exhibited rather than asserted.
    """
    A0, A1 = _fixture()
    N, L, P, _ = EC.null_bases(A1)
    A_s = (L.conj().T @ A0 @ N).real
    z0 = np.array([1.0, -0.5, 0.8, 0.3])
    Qz0 = z0 - P @ z0
    assert np.linalg.norm(Qz0) > 0.1, "the fixture must be off-manifold for this test to mean anything"

    for kappa in (1e2, 1e4, 1e6, 1e8):
        gap_at_zero = np.linalg.norm(expm((A0 + kappa * A1) * 0.0) @ z0 - N @ (L.conj().T @ z0))
        assert gap_at_zero == pytest.approx(np.linalg.norm(Qz0), rel=1e-12), kappa

    # but on [delta, T] it does converge
    delta = 0.1
    far = [np.linalg.norm(expm((A0 + k * A1) * delta) @ z0
                          - N @ expm(A_s * delta) @ (L.conj().T @ z0)) for k in (1e2, 1e4, 1e6)]
    assert far[0] > far[1] > far[2], far
    assert far[2] / far[0] == pytest.approx(1e-4, rel=0.1), far


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 4. Construction fixtures
# ═════════════════════════════════════════════════════════════════════════════════════════════


def test_exact_null_bases_satisfy_every_projector_identity():
    A0, A1 = _fixture()
    N, L, P, d = EC.null_bases(A1)
    assert d["nullity"] == 2
    for key in ("residual_A1_N", "residual_Lt_A1", "residual_Lt_N_minus_I",
                "residual_P_squared_minus_P", "residual_A1_P", "residual_P_A1"):
        assert d[key] < EC.IDENTITY_TOL, (key, d[key])


def test_a_nearly_singular_gram_is_visible_in_the_conditioning_record():
    """cond(L^T N) before normalisation is the informative quantity; cond(N)=1 is automatic."""
    A0, A1 = _fixture()
    _, _, _, d = EC.null_bases(A1)
    assert d["cond_N"] == pytest.approx(1.0, abs=1e-9)
    assert d["cond_Lt_N_before_normalisation"] >= 1.0
    assert "svd_rank_separation_ratio" in d


@pytest.mark.parametrize("value,finite,real,positive", [
    (0.5 + 0j, True, True, True),
    (-0.5 + 0j, True, True, False),                       # nonpositive endpoint output
    (0.5 + 1e-6j, True, False, True),                     # complex beyond the real tolerance
    (float("inf") + 0j, False, True, True),               # nonfinite
    (float("nan") + 0j, False, True, False),
])
def test_endpoint_output_requirements(value, finite, real, positive):
    v = EC.endpoint_verdict(value)
    assert v["finite"] is finite
    assert v["real_within_tolerance"] is real
    assert v["strictly_positive"] is positive


def test_incomplete_coverage_is_reported_as_incomplete():
    assert EC.coverage_verdict(27, 9, 3, 2) == "complete"
    assert EC.coverage_verdict(26, 9, 3, 2) == "incomplete"     # a cell dropped
    assert EC.coverage_verdict(27, 10, 3, 2) == "incomplete"    # a condition uncovered


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 5. The closure rule and the finite-kappa diagnostic
# ═════════════════════════════════════════════════════════════════════════════════════════════


def test_the_closure_rule_is_exactly_as_declared():
    assert EC.overall_status("assured", "verified", "consistent", "complete") == "assured"
    assert EC.overall_status("assured", "verified", "method_limited", "complete") == "assured"
    assert EC.overall_status("assured", "verified", "inconsistent", "complete") == "not_assured"
    assert EC.overall_status("not_assured", "verified", "consistent", "complete") == "not_assured"
    assert EC.overall_status("assured", "failed", "consistent", "complete") == "not_assured"
    assert EC.overall_status("assured", "verified", "consistent", "incomplete") == "not_assured"


def test_a_method_limited_diagnostic_does_not_block_but_an_inconsistent_one_does():
    """The U-shaped sequence is a property of expm, not of the limit."""
    falling = [1e-6, 1e-9, 1e-10, 1e-11, 1e-12]
    u_shaped = [1e-6, 1e-12, 1e-11, 1e-10, 1e-9]
    never = [1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
    diverging = [1e-6, 1e-12, 1e-9, 1e-5, 1e-2]
    assert EC._finite_kappa_disposition(falling)[0] == "consistent"
    assert EC._finite_kappa_disposition(u_shaped)[0] == "method_limited"
    assert EC._finite_kappa_disposition(never)[0] == "inconsistent"
    assert EC._finite_kappa_disposition(diverging)[0] == "inconsistent"


def test_no_universal_error_law_is_asserted_anywhere():
    """The U-shape is a diagnostic reading. Asserting O(kappa*eps) as proved was unsupported."""
    src = (_ROOT / "tools" / "paper_a_endpoint_construction.py").read_text(encoding="utf-8")
    archive_note = json.loads(ARCHIVE.read_text(encoding="utf-8"))["finite_kappa_diagnostic_note"]
    # the claim must appear only as an explicit DENIAL, in both the producer and the archive
    assert "not a proved error law" in src
    assert "NOT a proved error law" in archive_note
    assert "no universal O(kappa*eps)" in archive_note


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 6. Producer behaviour
# ═════════════════════════════════════════════════════════════════════════════════════════════


def _fake(overall="assured", **over):
    base = {
        "coverage": {"operator_distinct_cells": 1, "declared_cells": 2,
                     "cells_passing": 1, "cells_failing": 0},
        "cells": [{"solute": "caffeine", "T_degC": 93.4, "p_bar": 9.0,
                   "finite_kappa_diagnostic": {"min_abs_error": 1e-12, "best_kappa": 1e3},
                   "assumptions": {"A4_A5_bases_and_normalisation": {"cond_L": 2.0},
                                   "A3_stable_fast_spectrum": {"max_real_fast_eigenvalue": -1.0}}}],
        "algebraic_limit_status": "assured", "endpoint_construction_status": "verified",
        "finite_kappa_validation_status": "method_limited", "coverage_status": "complete",
        "overall_PR03a_status": overall,
    }
    base.update(over)
    return base


def test_a_not_assured_run_returns_nonzero(monkeypatch, capsys):
    """The previous producer returned 0 on failure because "NOT_ASSURED".endswith("ASSURED")."""
    monkeypatch.setattr(EC, "run", lambda: _fake(overall="not_assured"))
    assert EC.main([]) == 1
    monkeypatch.setattr(EC, "run", lambda: _fake(overall="assured"))
    assert EC.main([]) == 0
    capsys.readouterr()


def test_check_returns_nonzero_when_not_assured(monkeypatch, tmp_path, capsys):
    stored = _fake(overall="not_assured")
    path = tmp_path / "a.json"
    path.write_text(EC.canonical(stored), encoding="utf-8")
    monkeypatch.setattr(EC, "OUT", path)
    monkeypatch.setattr(EC, "run", lambda: stored)
    assert EC.main(["--check"]) == 1
    capsys.readouterr()


def test_check_detects_archive_drift(monkeypatch, tmp_path, capsys):
    path = tmp_path / "a.json"
    path.write_text(EC.canonical(_fake()), encoding="utf-8")
    monkeypatch.setattr(EC, "OUT", path)

    monkeypatch.setattr(EC, "run", lambda: _fake())
    assert EC.main(["--check"]) == 0

    drifted = _fake()
    drifted["cells"][0]["finite_kappa_diagnostic"]["min_abs_error"] = 5e-9
    monkeypatch.setattr(EC, "run", lambda: drifted)
    assert EC.main(["--check"]) == 1
    capsys.readouterr()


def test_check_fails_when_the_archive_is_absent(monkeypatch, tmp_path, capsys):
    monkeypatch.setattr(EC, "OUT", tmp_path / "missing.json")
    monkeypatch.setattr(EC, "run", lambda: _fake())
    assert EC.main(["--check"]) == 1
    capsys.readouterr()


def test_semantic_diff_tolerates_float_noise_but_not_a_changed_status():
    assert EC.semantic_diff({"x": 1.0}, {"x": 1.0 + 1e-13}) == []
    assert EC.semantic_diff({"x": 1.0}, {"x": 1.02}) != []
    assert EC.semantic_diff({"s": "assured"}, {"s": "not_assured"}) != []
    assert EC.semantic_diff({"b": True}, {"b": False}) != []
    assert EC.semantic_diff({"a": [1, 2]}, {"a": [1, 2, 3]}) != []
    assert EC.semantic_diff({"a": 1}, {"b": 1}) != []


def test_environment_is_excluded_from_check_but_recorded(archive):
    assert "environment" in EC.CHECK_EXCLUDED_TOP_LEVEL
    for k in ("python", "numpy", "scipy", "platform"):
        assert k in archive["environment"]


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 7. The committed archive
# ═════════════════════════════════════════════════════════════════════════════════════════════


def test_the_archive_carries_all_five_statuses_and_closes(archive):
    assert archive["algebraic_limit_status"] == "assured"
    assert archive["endpoint_construction_status"] == "verified"
    assert archive["coverage_status"] == "complete"
    assert archive["finite_kappa_validation_status"] in ("consistent", "method_limited")
    assert archive["overall_PR03a_status"] == "assured"
    assert archive["overall_PR03a_status"] == EC.overall_status(
        archive["algebraic_limit_status"], archive["endpoint_construction_status"],
        archive["finite_kappa_validation_status"], archive["coverage_status"])


def test_every_declared_cell_is_covered_and_none_was_dropped(archive):
    cov = archive["coverage"]
    assert cov["operator_distinct_cells"] == 27
    assert cov["declared_cells"] == 54
    assert cov["cells_failing"] == 0
    assert len(archive["cells"]) == 27
    assert "deduplication_proof" in cov
    seen = {(c["solute"], c["T_degC"], c["p_bar"]) for c in archive["cells"]}
    assert len(seen) == 27, "operator-distinct cells must be distinct"


def test_every_cell_verifies_every_assumption(archive):
    for c in archive["cells"]:
        a = c["assumptions"]
        assert a["A2_semisimple_zero"]["semisimple"] is True, c["solute"]
        assert a["A2_semisimple_zero"]["failure_reason"] is None, c["solute"]
        assert a["A2_semisimple_zero"]["separates_cleanly_A1"] is True, c["solute"]
        assert a["A2_semisimple_zero"]["separates_cleanly_A1_squared"] is True, c["solute"]
        assert a["A2_semisimple_zero"]["expected_rank"] == a["structural_rank"]["expected_fast_rank"]
        assert a["rank_source_agreement"]["agreement_ok"] is True, c["solute"]
        assert a["rank_source_agreement"]["all_sources_agree"] is True, c["solute"]
        assert a["structural_rank"]["expected_fast_rank"] == 400
        assert a["structural_rank"]["expected_slow_nullity"] == 201
        assert a["A3_stable_fast_spectrum"]["all_fast_modes_strictly_stable"] is True, c["solute"]
        assert a["A3_stable_fast_spectrum"]["max_real_fast_eigenvalue"] < 0.0
        assert a["A4_A5_bases_and_normalisation"]["identities_within_tolerance"] is True
        assert a["lemma3_derived_constants"]["applicable"] is True
        assert a["lemma3_derived_constants"]["derived_not_fitted"] is True
        assert a["lemma3_derived_constants"]["gamma_decay_rate"] > 0.0
        e = c["endpoint"]
        assert e["finite"] and e["real_within_tolerance"] and e["strictly_positive"]


def test_the_dual_basis_cross_check_holds_at_every_cell(archive):
    """L from the SVD and L from the [N W] dual basis are the same operator; L^T N = I pins it."""
    for c in archive["cells"]:
        agreement = c["assumptions"]["A4_A5_bases_and_normalisation"]["dual_basis_agreement_norm"]
        assert agreement < 1e-9, (c["solute"], agreement)


def test_the_output_covector_annihilates_the_fast_subspace_at_every_cell(archive):
    """Why the output carries no initial layer — verified, not assumed, per the proposition remark.

    A linear output row is a COVECTOR: it lies in ker(A1^T), equivalently e_out Q = 0. Saying it
    "lies in ker(A1)" was a category error in the wording, not in the construction.
    """
    for c in archive["cells"]:
        assert c["endpoint"]["output_covector_annihilates_fast_subspace"] is True, c["solute"]
        assert c["endpoint"]["output_covector_fast_component_norm"] < 1e-9


def test_the_proposition_uses_covector_language():
    text = PROOF.read_text(encoding="utf-8")
    assert "e_out Q = 0" in text
    assert "ker(A1ᵀ)" in text
    assert "lies in `ker(A1)`" not in text, "a covector cannot lie in ker(A1)"


def test_the_archive_binds_the_proof_artefact_by_hash(archive):
    import hashlib

    prop = archive["proposition"]
    assert prop["artefact"].endswith("PAPER_A_FIXED_TIME_SINGULAR_LIMIT_PROPOSITION.md")
    assert prop["sha256"] == hashlib.sha256(PROOF.read_bytes()).hexdigest(), (
        "the proof artefact changed without the archive being regenerated")
    assert prop["proved_here"] is False, "the producer verifies assumptions; it does not prove"
    assert "not uniform at t = 0" in prop["qualification"].lower()


def test_the_archive_records_full_provenance(archive):
    import hashlib

    p = archive["provenance"]
    producer = _ROOT / "tools" / "paper_a_endpoint_construction.py"
    assert p["producer_sha256"] == hashlib.sha256(producer.read_bytes()).hexdigest(), (
        "the producer changed without the archive being regenerated")
    for rel, digest in p["inputs"].items():
        assert (_ROOT / rel).exists(), rel
        assert digest == hashlib.sha256((_ROOT / rel).read_bytes()).hexdigest(), rel
    assert p["manual_verdict_editing"].startswith("PROHIBITED")
    assert "--check" in p["verification_command"]


def test_warnings_are_captured_rather_than_suppressed(archive):
    for c in archive["cells"]:
        assert isinstance(c["warnings"], list)


def test_the_finite_kappa_sequence_is_labelled_a_diagnostic(archive):
    assert "DIAGNOSTIC" in archive["cells"][0]["finite_kappa_diagnostic"]["role"]
    assert "not an independent proof" in archive["finite_kappa_diagnostic_note"]
    assert list(archive["verification_sequence"]) == list(EC.VERIFY_KAPPA)


# ═════════════════════════════════════════════════════════════════════════════════════════════
# 8. Standing prohibitions
# ═════════════════════════════════════════════════════════════════════════════════════════════


def test_the_producer_imports_no_campaign_data():
    import ast

    tree = ast.parse((_ROOT / "tools" / "paper_a_endpoint_construction.py")
                     .read_text(encoding="utf-8"))
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
    assert not any(m.startswith("puckworks.data") for m in imported), sorted(imported)


def test_no_p0_g8_result_archive_exists():
    assert not (_ROOT / "docs" / "paper1_resource"
                / "PAPER_A_ASYMPTOTIC_PROFILE_LIMITS.json").exists()


def test_the_wide_reference_architecture_is_untouched_by_this_cycle():
    """Scope closure: PR-03a may not reopen the accepted WIDE-reference architecture."""
    from puckworks.paper_a import wide_reference as WR

    assert WR.D_WIDE == (0.15, 500.0)
    assert WR.D_PUB == (0.15, 6.5)
    assert WR.GRID_SIZES == (40, 80, 160, 320)
    assert WR.RELATIVE_Q == (0.05, 0.10, 0.20)
    assert WR.ABSOLUTE_A == (0.10, 0.25)
    assert WR.NEAR_ZERO_PP == 0.05
    assert WR.ESTIMAND_TAG == "FULL-WIDE-ENDPOINT"
    assert WR.N_GROUPS == 6
    assert WR.PROGRAMME_RESULTS == ("H1_STRONG", "H1_QUALIFIED", "H1_DOES_NOT_LEAD")
    assert WR.EVENTUAL_UPPER_PRECONDITION_STATUSES == ("unresolved", "assured", "failed")
    assert WR.EVENTUAL_UPPER_PRECONDITION == "fixed_positive_time_limit"
