"""puckworks.public — PRESENTATION-ONLY public-value layer (PV-00).

NOT a physics component and NOT registered in the registry. This package turns
existing harness/gate/data results into traceable public claims: every public
number is generated by a NAMED function (never hand-typed), carries its
evidence-strength label UNCHANGED, an observation/reconstruction/prediction/
simulation badge, its source datasets, validity range, caveat, and a one-line
reproduction command.

Guardrails (docs/PUBLIC_VALUE.md §3) are enforced structurally here, not by
convention: see `puckworks/public/schema.py` (validation) and
`tests/test_public_claims.py` (the failing conditions). The public track consumes
scientific results; it never relaxes their strength labels.

Entry points:
    from puckworks.public import PUBLIC_CLAIMS
    python -m puckworks.public export --out docs/public/generated
"""
from .schema import PublicClaim, Producer, BADGES, EVIDENCE_STRENGTHS
from .claims import PUBLIC_CLAIMS

__all__ = ["PublicClaim", "Producer", "BADGES", "EVIDENCE_STRENGTHS",
           "PUBLIC_CLAIMS"]
