"""Seed public-claim registry — the four P0 stories (PUBLIC_VALUE.md §17).

Every numeric value is GENERATED by the named `Producer` (a harness/model function),
never hand-typed; the stored numbers are snapshots the exporter and
`tests/test_public_claims.py` regenerate and check for drift. Evidence-strength
labels are copied UNCHANGED from the scientific analyses — the public layer never
softens them.
"""
from .schema import PublicClaim, Producer

_H = "puckworks.harness"

PUBLIC_CLAIMS = [

    # ---- PV-01 — "The first drop is already strong" -------------------------
    PublicClaim(
        claim_id="PV-01",
        public_question="Is the first liquid out of an espresso puck weak because "
                        "water only just entered, or can it already be near-saturated?",
        headline="The first liquid out of this espresso puck was already about 97% "
                 "as concentrated as the peak.",
        plain_language_finding="In one pressure-controlled, fraction-resolved dataset, "
            "the earliest measured fraction was already ~97% of the peak TDS. This "
            "separates WETTING time (water crossing the puck) from DISSOLUTION speed "
            "(coffee going into solution) — the liquid can take time to appear while "
            "becoming chemically concentrated almost immediately.",
        numeric_result={"early_over_peak": 0.968, "early_tds_pct": 24.36,
                        "peak_tds_pct": 25.16, "boulder_diffusion_timescale_s": 23.1},
        units={"early_over_peak": "ratio", "early_tds_pct": "% TDS",
               "peak_tds_pct": "% TDS", "boulder_diffusion_timescale_s": "s"},
        uncertainty_or_sensitivity="The first fraction has only ONE replicate; the "
            "23 s boulder-diffusion timescale is the comparator that near-instant "
            "dissolution beats — favouring rapid dissolution in this configuration.",
        evidence_strength="independent",
        badge="OBSERVED",
        components=["waszkiewicz2025 TDS fractions", "cameron2020 (boulder timescale)"],
        dataset_manifest_ids=["waszkiewicz2025/tds_fractions"],
        validity_range="One rig, one coffee, one configuration (pressure-controlled).",
        primary_caveat="One rig/config and a single first-fraction replicate — a "
            "strong prompt for replication, NOT a universal law. Do not claim all "
            "espresso reaches full strength instantly.",
        practical_implication="Collect TIMED FRACTIONS rather than judging extraction "
            "from the final cup; do not assume the first drops are chemically weak.",
        reproduction="python -c \"from puckworks.harness import dissolution_speed_test as f; print(f())\"",
        producer=Producer(
            module=_H, function="dissolution_speed_test",
            result_map={"early_over_peak": "early_to_peak",
                        "early_tds_pct": "early_tds_pct",
                        "peak_tds_pct": "peak_tds_pct",
                        "boulder_diffusion_timescale_s": "tau_boulder_diffusion_s"}),
    ),

    # ---- PV-02 — "The machine can fake a puck problem" ----------------------
    PublicClaim(
        claim_id="PV-02",
        public_question="When a flow curve dips and recovers, does that prove the "
                        "coffee bed changed (swelling, channeling, fines)?",
        headline="A flow dip can come from the espresso machine even when the puck "
                 "model does nothing — but some traces DO need a time-varying bed.",
        plain_language_finding="A machine-only model (pump + headspace, no bed "
            "mechanism) can reproduce a dip-and-recovery, so that shape alone is not "
            "a diagnosis. Separately, on a 9-bar rising-flow trace, every constant "
            "baseline fails and a time-varying porosity trajectory reconstructs it "
            "~4.9x better — time variation IS needed there (though a flexible "
            "non-mechanistic curve does as well, so this does not identify a specific "
            "bed mechanism).",
        numeric_result={"dynamic_rmse_g_per_s": 0.116,
                        "best_constant_null_rmse_g_per_s": 0.573,
                        "improvement_factor": 4.9},
        units={"dynamic_rmse_g_per_s": "g/s",
               "best_constant_null_rmse_g_per_s": "g/s", "improvement_factor": "x"},
        uncertainty_or_sensitivity="Single 9-bar trace, one window (15-95 s); a "
            "4-parameter flexible cubic reaches ~0.096 g/s, so the RMSE gap shows "
            "time-variation is needed, not that a particular mechanism is identified.",
        evidence_strength="post-fit reconstruction",
        badge="RECONSTRUCTED",
        components=["waszkiewicz2025.poroelastic", "foster2025 machine mode",
                    "kappa_t_ladder"],
        dataset_manifest_ids=["waszkiewicz2025/traces_time_dependent"],
        validity_range="One rig; the machine-null is on Foster's fitted trace, the "
            "ladder on the Waszkiewicz 9-bar rising-flow window.",
        primary_caveat="Sufficient, NOT unique: do not say 'dissolution caused the "
            "rising flow'. A flow curve becomes informative only with more observables "
            "and controlled perturbations.",
        practical_implication="Do not diagnose swelling/channeling from a "
            "dip-and-recovery alone; log pressure, flow, first-drip time, mass, "
            "control mode, and ideally timed TDS fractions.",
        reproduction="python -c \"from puckworks.harness import kappa_t_ladder as f; print(f())\"",
        producer=Producer(
            module=_H, function="kappa_t_ladder",
            result_map={"dynamic_rmse_g_per_s": "rung4_phi_of_t",
                        "best_constant_null_rmse_g_per_s": "rung1_const_kappa",
                        "improvement_factor": "improvement_factor"}),
    ),

    # ---- PV-04 — "We killed our favorite result" ---------------------------
    PublicClaim(
        claim_id="PV-04",
        public_question="How can an exciting result weaken when the target variable "
                        "and its uncertainty are audited?",
        headline="We thought a model had explained the fine-grind espresso dip — then "
                 "we checked the units and the raw replicates.",
        plain_language_finding="After rebuilding the target as a coherent TDS-derived "
            "extraction yield (an earlier version mixed mg solute masses with g TDS), "
            "the raw measured cells are ORDERED across dial (18.27 -> 19.38 -> 19.62%), "
            "with the middle dial BELOW the coarse one — no interior 'fine-grind' "
            "maximum. A channeling model can still MAKE such a bump, but that is model "
            "capacity, not identification: the bump is fragile and smaller than the "
            "shot-to-shot spread.",
        numeric_result={"ey_dial_1p4_pct": 18.27, "ey_dial_1p7_pct": 19.38,
                        "ey_dial_2p0_pct": 19.62,
                        "mid_vs_coarse_contrast_EYpt": -0.241,
                        "welch_ci95_lo_EYpt": -0.422, "welch_ci95_hi_EYpt": -0.06},
        units={"ey_dial_1p4_pct": "% EY", "ey_dial_1p7_pct": "% EY",
               "ey_dial_2p0_pct": "% EY", "mid_vs_coarse_contrast_EYpt": "EY-points",
               "welch_ci95_lo_EYpt": "EY-points", "welch_ci95_hi_EYpt": "EY-points"},
        uncertainty_or_sensitivity="Welch 95% CI on the middle-vs-coarse contrast "
            "excludes zero; the model's interior bump is near-flat at 9 bar and "
            "appears in only a minority of the closure grid — smaller than replicate "
            "spread. Means are described as ORDERED, not 'statistically monotone' "
            "(the 1.4-vs-1.7 interval includes zero).",
        evidence_strength="independent",
        badge="OBSERVED",
        components=["schmieder_interior_max_target", "result1_magnitude_comparison",
                    "channeling_interior_max_sensitivity"],
        dataset_manifest_ids=["schmieder2023/cup_masses", "schmieder2023/rsm_coefficients"],
        validity_range="Schmieder E65S grinder DoE, fixed central flow/temperature "
            "condition; TDS-derived EY observable.",
        primary_caveat="These are Schmieder E65S grinder-DIAL positions — a dial "
            "number is NOT a particle size and is non-portable to another grinder "
            "without a calibrated adapter. Do not read a universal 'too-fine optimum'. "
            "Also: static channeling remains a viable GENERATOR (model capacity), the "
            "data just do not identify it as the cause.",
        practical_implication="Plot raw replicates before trend lines, use a coherent "
            "yield measure, and distinguish a machine-specific dial position from a "
            "physical grind characteristic.",
        reproduction="python -m puckworks.public.analysis_autopsy verify",
        # Consumes the deterministic, hash-bound PV-04 snapshot (a FAST producer that reads the packaged
        # data), not the slow harness function directly. numeric_result stays focused on the CORRECTED
        # OBSERVED quantities so the claim's OBSERVED/independent label never silently covers the
        # simulated model-capacity or derived RSM-audit values (those live in the richer snapshot with
        # their own per-partition evidence labels).
        producer=Producer(
            module="puckworks.public.analysis_autopsy", function="pv04_values",
            result_map={"ey_dial_1p4_pct": "ey_dial_1p4_pct",
                        "ey_dial_1p7_pct": "ey_dial_1p7_pct",
                        "ey_dial_2p0_pct": "ey_dial_2p0_pct",
                        "mid_vs_coarse_contrast_EYpt": "mid_vs_coarse_contrast_EYpt",
                        "welch_ci95_lo_EYpt": "welch_ci95_lo_EYpt",
                        "welch_ci95_hi_EYpt": "welch_ci95_hi_EYpt"}),
        compares_grinder_dials=True,
    ),

    # ---- PV-05 — "More Physics Made It Worse" (model-composition story) ------
    PublicClaim(
        claim_id="PV-05",
        public_question="Can two individually plausible espresso components be combined "
                        "safely just by sharing one state variable?",
        headline="Adding a swelling branch made this tested model worse.",
        plain_language_finding="A time-varying extraction model followed the rising flow "
            "trace much better than a constant baseline. But when a swelling branch was "
            "added through one shared porosity state, that state over-closed and the "
            "composite prediction became worse than the constant. The result rejects "
            "this composition, not swelling physics in general.",
        numeric_result={
            "const_baseline_rmse_g_per_s": 0.573,
            "extraction_only_rmse_g_per_s": 0.116,
            "composite_rmse_g_per_s": 0.648,
            "rmse_ratio_composite_over_constant": 1.131,
            "rmse_ratio_composite_over_extraction": 5.586,
            "min_shared_porosity": 0.0998,
            "eps0_reference_porosity": 0.17,
            "swelling_closes_shared_state": True,
            "eval_window_start_s": 15.0,
            "eval_window_end_s": 95.0},
        units={
            "const_baseline_rmse_g_per_s": "g/s",
            "extraction_only_rmse_g_per_s": "g/s",
            "composite_rmse_g_per_s": "g/s",
            "rmse_ratio_composite_over_constant": "ratio",
            "rmse_ratio_composite_over_extraction": "ratio",
            "min_shared_porosity": "porosity fraction (dimensionless)",
            "eps0_reference_porosity": "porosity fraction (dimensionless)",
            "swelling_closes_shared_state": "boolean",
            "eval_window_start_s": "s",
            "eval_window_end_s": "s"},
        uncertainty_or_sensitivity="Over the 15-95 s window the composite 0.648 g/s is "
            "1.13x the best-constant null (0.573 g/s) and 5.59x the extraction-only rung "
            "(0.116 g/s, cross-checked by degeneracy_rmse); the shared porosity "
            "over-closes to 0.0998 (below the 0.17 reference). A diagnosed mis-scale, "
            "reported not tuned away.",
        evidence_strength="qualitative",
        badge="EXPLORATORY_SIMULATION",
        components=["brewer2026.coupled_kappa_t"],
        dataset_manifest_ids=["waszkiewicz2025/traces_time_dependent",
                              "waszkiewicz2025/constants"],
        validity_range="9-bar Waszkiewicz trace; the imported swelling parameters are "
            "mo2023_2's, applied to a saturated pre-wet rig; one observation operator.",
        primary_caveat="Diagnoses THIS shared-porosity composition, not the existence of "
            "swelling; does NOT prove the extraction-only mechanism; and 'simple is "
            "always best' is NOT the lesson — complexity is justified when it beats the "
            "baseline. Not coupled into the Guided Espresso Pull.",
        practical_implication="Do not assume a more elaborate model is more trustworthy; "
            "a simple baseline must stay visible and be beaten before components are "
            "combined through a shared state.",
        reproduction="python -m puckworks.public.model_composition verify",
        producer=Producer(
            module="puckworks.public.model_composition",
            function="pv05_values",
            result_map={
                "const_baseline_rmse_g_per_s": "const_baseline_rmse_g_per_s",
                "extraction_only_rmse_g_per_s": "extraction_only_rmse_g_per_s",
                "composite_rmse_g_per_s": "composite_rmse_g_per_s",
                "rmse_ratio_composite_over_constant": "rmse_ratio_composite_over_constant",
                "rmse_ratio_composite_over_extraction": "rmse_ratio_composite_over_extraction",
                "min_shared_porosity": "min_shared_porosity",
                "eps0_reference_porosity": "eps0_reference_porosity",
                "swelling_closes_shared_state": "swelling_closes_shared_state",
                "eval_window_start_s": "eval_window_start_s",
                "eval_window_end_s": "eval_window_end_s"}),
    ),

    # ---- PV-03 — "The cup hides the clock" (flat-valley identifiability) -----
    PublicClaim(
        claim_id="PV-03",
        public_question="Can a model match the final cup while leaving its hidden rate "
                        "and inventory unresolved?",
        headline="The final cup can hide very different extraction clocks.",
        plain_language_finding="Across the tested endpoint data, many inventory-rate "
            "combinations fit nearly equally well (log-parameter SSE-Hessian condition "
            "number ~1,930; the 10%-near-optimal rate set covers ~76% of the tested grid). "
            "Held-out cup predictions remain reasonably stable, but the mechanistic model "
            "(8.2% MAPE) barely improves on a level-only constant (8.6%) and is worse on "
            "50 of 108 held-out points. Timed fractions preserve rate information the final "
            "cup discards.",
        numeric_result={
            "condition_number": 1927.0, "inverse_curvature_coupling": -0.994,
            "profile_fraction_of_log_grid": 0.76, "sse_mape_threshold_jaccard": 0.86,
            "held_out_model_mape": 8.23, "held_out_const_mape": 8.59,
            "n_model_worse_than_const": 50, "n_points": 108, "skill_vs_const": 0.042,
            "table7_implied_rate": 0.95},
        units={
            "condition_number": "ratio",
            "inverse_curvature_coupling": "ratio (geometric, not statistical)",
            "profile_fraction_of_log_grid": "fraction of tested log-rate grid",
            "sse_mape_threshold_jaccard": "Jaccard overlap (0-1)",
            "held_out_model_mape": "% MAPE", "held_out_const_mape": "% MAPE",
            "n_model_worse_than_const": "count", "n_points": "count",
            "skill_vs_const": "fraction", "table7_implied_rate": "rate scale (dimensionless)"},
        uncertainty_or_sensitivity="Practical (not structural) non-identifiability; no "
            "likelihood/noise model. The tested rate range is RIGHT-CENSORED at its upper "
            "edge. The inverse-curvature coupling is objective-surface geometry, NOT a "
            "statistical parameter correlation; the 10% set is a tested-domain threshold "
            "set, NOT a confidence interval.",
        evidence_strength="negative validation",
        badge="RECONSTRUCTED",
        components=["pannusch2024.solver (refit)", "angeloni2023 endpoints",
                    "identifiability_panel", "transfer_skill_vs_baselines"],
        dataset_manifest_ids=["angeloni2023/bioactives", "angeloni2023/total_solids",
                              "angeloni2023/inventories", "pannusch2024/table2_params"],
        validity_range="One model refit to one independent campaign; conditional on the "
            "tested model, observation operator, data, objective, and matched-endpoint domain.",
        primary_caveat="Endpoint prediction stability is NOT parameter identification and "
            "NOT mechanistic validation; the mechanistic model barely beats a level-only "
            "null. Not a claim of structural identifiability, and not evidence the "
            "mechanism transferred.",
        practical_implication="To learn mechanism, preserve the clock (collect timed "
            "fractions), measure the soluble inventory independently, and beat a simple "
            "level-only null before crediting a mechanism from endpoint accuracy.",
        reproduction="python -m puckworks.public.flat_valley verify",
        producer=Producer(
            module="puckworks.public.flat_valley", function="pv03_values",
            result_map={"condition_number": "condition_number",
                        "inverse_curvature_coupling": "inverse_curvature_coupling",
                        "profile_fraction_of_log_grid": "profile_fraction_of_log_grid",
                        "sse_mape_threshold_jaccard": "sse_mape_threshold_jaccard",
                        "held_out_model_mape": "held_out_model_mape",
                        "held_out_const_mape": "held_out_const_mape",
                        "n_model_worse_than_const": "n_model_worse_than_const",
                        "n_points": "n_points", "skill_vs_const": "skill_vs_const",
                        "table7_implied_rate": "table7_implied_rate"}),
    ),
]
