"""Exporters + claim-card renderer + CLI (PV-00 §5.3, §5.6).

`export()` regenerates every public number from its Producer (so nothing is ever
copied from a paper by hand), stamps the source commit, and writes JSON, CSV, and
Markdown claim cards. One command regenerates the whole public layer:

    python -m puckworks.public export --out docs/public/generated [--slow]

Without --slow, Producers flagged slow (PDE/GPU solves) keep their stored snapshot
and are marked stale-unchecked in the output.
"""
from __future__ import annotations
import csv
import io
import json
import os
import subprocess
from .claims import PUBLIC_CLAIMS


def _source_commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "UNKNOWN"


def regenerate(claims=None, run_slow=False):
    """Return (claims, drift) with numeric_result recomputed from each Producer.
    `drift` lists (claim_id, key, snapshot, live) where a regenerated value differs
    from the stored snapshot — the staleness guard (a changed harness result must
    invalidate the card, PV-00 §5.7)."""
    claims = list(PUBLIC_CLAIMS if claims is None else claims)
    commit = _source_commit()
    drift = []
    for c in claims:
        c.source_commit = commit
        if c.producer.slow and not run_slow:
            continue
        live = c.producer.compute()
        for k, v in live.items():
            snap = c.numeric_result.get(k)
            if isinstance(v, (int, float)) and isinstance(snap, (int, float)):
                # staleness guard: flag a MEANINGFUL shift (the card's rounded number
                # would change), not sub-percent float rounding of the display value.
                tol = max(1e-3, 5e-3 * abs(float(snap)))
                if abs(float(v) - float(snap)) > tol:
                    drift.append((c.claim_id, k, snap, round(float(v), 4)))
            elif v != snap:
                drift.append((c.claim_id, k, snap, v))
            # keep the authored (display-rounded) snapshot; the exporter writes it
            if not (isinstance(v, (int, float)) and isinstance(snap, (int, float))):
                c.numeric_result[k] = v
    return claims, drift


def to_json(claims) -> str:
    return json.dumps([c.to_dict() for c in claims], indent=2, default=str)


def to_csv(claims) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["claim_id", "headline", "key", "value", "unit", "evidence_strength",
                "badge", "dataset_manifest_ids", "source_commit"])
    for c in claims:
        for k, v in c.numeric_result.items():
            w.writerow([c.claim_id, c.headline, k, v, c.units.get(k, ""),
                        c.evidence_strength, c.badge,
                        ";".join(c.dataset_manifest_ids), c.source_commit or ""])
    return buf.getvalue()


def render_card(c) -> str:
    """A minimal claim card: headline, one result, scope sentence, reproduction."""
    nums = "; ".join(f"**{k}** = {v} {c.units.get(k, '')}".strip()
                     for k, v in c.numeric_result.items())
    dials = " · ⚠ grinder-dial: non-portable" if c.compares_grinder_dials else ""
    return (
        f"### {c.claim_id} — {c.headline}\n\n"
        f"`[{c.badge}]` · evidence: **{c.evidence_strength}**{dials}\n\n"
        f"**Question.** {c.public_question}\n\n"
        f"**Finding.** {c.plain_language_finding}\n\n"
        f"**Numbers.** {nums}\n\n"
        f"**Uncertainty / sensitivity.** {c.uncertainty_or_sensitivity}\n\n"
        f"**Validity.** {c.validity_range}\n\n"
        f"**Caveat (scope sentence).** {c.primary_caveat}\n\n"
        f"**Practical implication.** {c.practical_implication}\n\n"
        f"**Datasets.** {', '.join(c.dataset_manifest_ids)} · "
        f"**Generated by** `{c.producer.ref()}`"
        f"{' (slow)' if c.producer.slow else ''} · commit `{(c.source_commit or '')[:10]}`\n\n"
        f"**Reproduce.** `{c.reproduction}`\n"
    )


def to_markdown(claims) -> str:
    head = ("# puckworks — public claim cards (generated)\n\n"
            "*Generated by `python -m puckworks.public export`. Every number is "
            "produced by a named function (see each card's *Generated by*); "
            "evidence-strength labels are carried UNCHANGED from the scientific "
            "analyses. Do not hand-edit — regenerate.*\n\n")
    return head + "\n---\n\n".join(render_card(c) for c in claims)


def export(out_dir="docs/public/generated", run_slow=False):
    claims, drift = regenerate(run_slow=run_slow)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "claims.json"), "w") as f:
        f.write(to_json(claims))
    with open(os.path.join(out_dir, "claims.csv"), "w") as f:
        f.write(to_csv(claims))
    with open(os.path.join(out_dir, "claims.md"), "w") as f:
        f.write(to_markdown(claims))
    return dict(out_dir=out_dir, n_claims=len(claims), drift=drift,
                slow_run=run_slow)


def main(argv=None):
    import argparse
    p = argparse.ArgumentParser(prog="puckworks.public")
    sub = p.add_subparsers(dest="cmd")
    e = sub.add_parser("export", help="regenerate + write JSON/CSV/Markdown cards")
    e.add_argument("--out", default="docs/public/generated")
    e.add_argument("--slow", action="store_true", help="also run slow Producers")
    args = p.parse_args(argv)
    if args.cmd == "export":
        r = export(args.out, run_slow=args.slow)
        print(f"wrote {r['n_claims']} claims -> {r['out_dir']} "
              f"(slow={r['slow_run']})")
        if r["drift"]:
            print("DRIFT (snapshot != regenerated):")
            for cid, k, snap, live in r["drift"]:
                print(f"  {cid}.{k}: snapshot {snap} -> live {live}")
    else:
        p.print_help()


if __name__ == "__main__":
    main()
