"""PublicClaim + Producer schema and the structural guardrails (PV-00 §5.2)."""
from __future__ import annotations
from dataclasses import dataclass, field, asdict
from importlib import import_module

# The four badges (PUBLIC_VALUE.md §3.1) — put ONE in the graphic, not the caption.
BADGES = ("OBSERVED", "RECONSTRUCTED", "PREDICTED", "EXPLORATORY_SIMULATION")

# PUBLIC evidence vocabulary. It is a DELIBERATELY COARSER, lay-facing vocabulary -- NOT the
# registry vocabulary. An earlier comment here claimed it "rides along UNCHANGED into public",
# which was false: the registry uses nine snake_case relations
# (puckworks.registry.EVIDENCE_STRENGTHS) and these are six spaced lay terms. Paper 3 review P0-2
# flagged the three drifting vocabularies; the mapping below makes the relationship explicit and
# testable instead of implied.
EVIDENCE_STRENGTHS = ("independent", "post-fit reconstruction", "verification",
                      "qualitative", "reference", "negative validation")

#: registry relation -> public lay term. Many-to-one BY DESIGN: the public surface deliberately
#: does not expose the registry's finer distinctions.
REGISTRY_TO_PUBLIC = {
    "controlled_independent": "independent",
    "within_campaign_held_out": "independent",
    "post_fit_reconstruction": "post-fit reconstruction",
    "source_curve_reproduction": "post-fit reconstruction",
    "code_verification": "verification",
    "sign_or_compatibility": "qualitative",
    "qualitative_capacity": "qualitative",
    "exploratory_synthesis": "qualitative",
    "proposed_experiment": "reference",
}

#: OUTCOME is a separate field from RELATION (Paper 3 §5, axis 2). `negative validation` is a
#: LEGACY COMPOUND: it encodes a *failed outcome*, not a kind of comparison, and the manuscript
#: says so explicitly ("a negative result ... is a failed outcome on some relation, not a relation
#: of its own"). It is retained because published public artifacts already carry it, but it MUST
#: decompose as below and must not be treated as a relation in new work.
PUBLIC_OUTCOMES = ("supported", "negative", "indeterminate")
LEGACY_COMPOUND_RELATIONS = {
    "negative validation": {"relation": "qualitative", "outcome": "negative"},
}


def _dig(obj, path):
    """Extract a value at a dotted path; segments may be dict keys or list indices."""
    cur = obj
    for seg in path.split("."):
        if isinstance(cur, (list, tuple)):
            cur = cur[int(seg)]
        else:
            cur = cur[seg]
    return cur


@dataclass
class Producer:
    """How a claim's numbers are GENERATED (never hand-typed). `result_map` maps a
    numeric_result key -> a dotted path into the named function's return value, so
    a test/exporter can recompute every public number and detect drift or a
    hard-coded value (a numeric key with no result_map entry is the failure)."""
    module: str
    function: str
    result_map: dict           # numeric_result key -> dotted result path
    kwargs: dict = field(default_factory=dict)
    slow: bool = False         # True => PDE/GPU solves; skip in the quick test

    def compute(self) -> dict:
        fn = getattr(import_module(self.module), self.function)
        res = fn(**self.kwargs)
        return {k: _dig(res, p) for k, p in self.result_map.items()}

    def ref(self) -> str:
        return f"{self.module}.{self.function}"


@dataclass
class PublicClaim:
    """One traceable public claim. Every numeric value regenerates from `producer`;
    every value carries a unit; the claim carries an evidence-strength label and a
    badge, its source datasets, validity range, caveat, and reproduction command."""
    claim_id: str
    public_question: str
    headline: str
    plain_language_finding: str
    numeric_result: dict            # key -> value (SNAPSHOT; regenerated by producer)
    units: dict                     # key -> unit string (every numeric key needs one)
    uncertainty_or_sensitivity: str
    evidence_strength: str          # one of the PUBLIC EVIDENCE_STRENGTHS above -- a coarser
                                    # lay term MAPPED from the registry relation via
                                    # REGISTRY_TO_PUBLIC, not the registry value verbatim
    badge: str                      # one of BADGES
    components: list                # registry component / harness names used
    dataset_manifest_ids: list      # rows that MUST exist in data/MANIFEST.csv
    validity_range: str
    primary_caveat: str
    practical_implication: str
    reproduction: str               # one-line command
    producer: Producer
    compares_grinder_dials: bool = False   # if True, caveat MUST warn non-portability
    # --- commit provenance (Paper 3 review P0-6) -------------------------------------------
    # `source_commit` was AMBIGUOUS: it is stamped at export time, so it meant "the commit at
    # which this artifact was last regenerated" -- which a reader could equally read as "the
    # commit the result was produced from" or "the current release commit". Those are different
    # facts, and a snapshot can verify successfully at a later commit while still displaying an
    # earlier value. The two are now recorded SEPARATELY. `source_commit` is retained as a
    # deprecated alias of `generated_from_commit` because published artifacts already carry it.
    source_commit: str | None = None            # DEPRECATED alias of generated_from_commit
    generated_from_commit: str | None = None    # immutable: the commit the payload was produced at
    last_verified_against_commit: str | None = None   # mutable: most recent successful verification

    # ---- structural guardrails (PUBLIC_VALUE.md §3; enforced, not by convention) --
    def validate(self) -> list:
        """Return a list of guardrail violations (empty == clean)."""
        errs = []
        # (1) every numeric public claim value has a unit
        for k in self.numeric_result:
            if k not in self.units or not str(self.units[k]).strip():
                errs.append(f"{self.claim_id}: numeric '{k}' has no unit")
        # (2) evidence-strength tag present and in the vocabulary (never invented)
        if self.evidence_strength not in EVIDENCE_STRENGTHS:
            errs.append(f"{self.claim_id}: evidence_strength "
                        f"'{self.evidence_strength}' not in the ROADMAP §0 vocabulary")
        # (3) a badge is set and valid; a simulation claim needs the SIM badge
        if self.badge not in BADGES:
            errs.append(f"{self.claim_id}: badge '{self.badge}' invalid")
        # (5) a public number is hard-coded (no producer path) — the integrity rule
        for k in self.numeric_result:
            if k not in self.producer.result_map:
                errs.append(f"{self.claim_id}: numeric '{k}' is hard-coded "
                            f"(no producer.result_map entry generating it)")
        # (6) a grinder-dial comparison without a non-portability warning
        if self.compares_grinder_dials:
            c = self.primary_caveat.lower()
            if not any(w in c for w in ("non-portable", "not portable", "adapter",
                                        "not a unit", "calibrat")):
                errs.append(f"{self.claim_id}: compares grinder dials but the caveat "
                            f"carries no non-portability / adapter warning")
        return errs

    def to_dict(self) -> dict:
        d = asdict(self)
        d["producer"] = {"ref": self.producer.ref(), "slow": self.producer.slow,
                         "kwargs": self.producer.kwargs}
        return d
