"""PublicClaim + Producer schema and the structural guardrails (PV-00 §5.2)."""
from __future__ import annotations
from dataclasses import dataclass, field, asdict
from importlib import import_module

# The four badges (PUBLIC_VALUE.md §3.1) — put ONE in the graphic, not the caption.
BADGES = ("OBSERVED", "RECONSTRUCTED", "PREDICTED", "EXPLORATORY_SIMULATION")

# The evidence-strength vocabulary (ROADMAP §0) — rides along UNCHANGED into public.
EVIDENCE_STRENGTHS = ("independent", "post-fit reconstruction", "verification",
                      "qualitative", "reference", "negative validation")


def _dig(obj, path):
    """Extract a value at a dotted path; segments may be dict keys or list indices."""
    cur = obj
    for seg in path.split("."):
        if isinstance(cur, (list, tuple)):
            cur = cur[int(seg)]
        else:
            cur = cur[seg]
    return cur


@dataclass
class Producer:
    """How a claim's numbers are GENERATED (never hand-typed). `result_map` maps a
    numeric_result key -> a dotted path into the named function's return value, so
    a test/exporter can recompute every public number and detect drift or a
    hard-coded value (a numeric key with no result_map entry is the failure)."""
    module: str
    function: str
    result_map: dict           # numeric_result key -> dotted result path
    kwargs: dict = field(default_factory=dict)
    slow: bool = False         # True => PDE/GPU solves; skip in the quick test

    def compute(self) -> dict:
        fn = getattr(import_module(self.module), self.function)
        res = fn(**self.kwargs)
        return {k: _dig(res, p) for k, p in self.result_map.items()}

    def ref(self) -> str:
        return f"{self.module}.{self.function}"


@dataclass
class PublicClaim:
    """One traceable public claim. Every numeric value regenerates from `producer`;
    every value carries a unit; the claim carries an evidence-strength label and a
    badge, its source datasets, validity range, caveat, and reproduction command."""
    claim_id: str
    public_question: str
    headline: str
    plain_language_finding: str
    numeric_result: dict            # key -> value (SNAPSHOT; regenerated by producer)
    units: dict                     # key -> unit string (every numeric key needs one)
    uncertainty_or_sensitivity: str
    evidence_strength: str          # one of EVIDENCE_STRENGTHS (UNCHANGED from source)
    badge: str                      # one of BADGES
    components: list                # registry component / harness names used
    dataset_manifest_ids: list      # rows that MUST exist in data/MANIFEST.csv
    validity_range: str
    primary_caveat: str
    practical_implication: str
    reproduction: str               # one-line command
    producer: Producer
    compares_grinder_dials: bool = False   # if True, caveat MUST warn non-portability
    source_commit: str | None = None       # filled at export time

    # ---- structural guardrails (PUBLIC_VALUE.md §3; enforced, not by convention) --
    def validate(self) -> list:
        """Return a list of guardrail violations (empty == clean)."""
        errs = []
        # (1) every numeric public claim value has a unit
        for k in self.numeric_result:
            if k not in self.units or not str(self.units[k]).strip():
                errs.append(f"{self.claim_id}: numeric '{k}' has no unit")
        # (2) evidence-strength tag present and in the vocabulary (never invented)
        if self.evidence_strength not in EVIDENCE_STRENGTHS:
            errs.append(f"{self.claim_id}: evidence_strength "
                        f"'{self.evidence_strength}' not in the ROADMAP §0 vocabulary")
        # (3) a badge is set and valid; a simulation claim needs the SIM badge
        if self.badge not in BADGES:
            errs.append(f"{self.claim_id}: badge '{self.badge}' invalid")
        # (5) a public number is hard-coded (no producer path) — the integrity rule
        for k in self.numeric_result:
            if k not in self.producer.result_map:
                errs.append(f"{self.claim_id}: numeric '{k}' is hard-coded "
                            f"(no producer.result_map entry generating it)")
        # (6) a grinder-dial comparison without a non-portability warning
        if self.compares_grinder_dials:
            c = self.primary_caveat.lower()
            if not any(w in c for w in ("non-portable", "not portable", "adapter",
                                        "not a unit", "calibrat")):
                errs.append(f"{self.claim_id}: compares grinder dials but the caveat "
                            f"carries no non-portability / adapter warning")
        return errs

    def to_dict(self) -> dict:
        d = asdict(self)
        d["producer"] = {"ref": self.producer.ref(), "slow": self.producer.slow,
                         "kwargs": self.producer.kwargs}
        return d
