from .schema import QuantityRow

CARDS = {
 "foster2025.machine_mode": "docs/cards/foster2025_2.md@b907b002ddb81560dd6e3d514b8cfa31bb1b2820a397195d27aa865036976b4b",
 "wadsworth2026.inertial": "docs/cards/wadsworth2026_inertial.md@799b7dc68df3dc5602e7831db08482405c4c40cfccf24dfb81e69676f7a4c888",
 "cameron2020.extraction_bdf": "docs/cards/cameron2020.md@3d0eb1f7e6b18a5aebf2c17eab75b990f5d167aef1a5fb6129ab402f21f3f22b",
}

def _row(cid, stage, name, direction, unit, basis, definition, role, valid, evidence,
         group, support="SUPPORTED", control="SOURCE_NATIVE", node="NOT_APPLICABLE",
         reference="NOT_APPLICABLE", flow="NOT_APPLICABLE", mass="NOT_APPLICABLE", notes=""):
    return QuantityRow(cid, stage, name, direction, unit, basis, definition, role,
        f"{CARDS[cid].split('@')[0]}; authoritative implementation", valid, evidence, "yes" if direction=="input" else "derived",
        "direct", group, support, control, node, reference, flow, mass, "90-92_C_SOURCE_NOMINAL",
        "ONE_DIMENSIONAL_OR_LUMPED", "SOURCE_DEFAULT", "DECLARED_BY_COMPONENT", "NONE", "NONE",
        CARDS[cid], "puckworks/models/__init__.py@a8e336c00982f05e3312483d2d67f894b7485995069af936b084341b9ce8e114", notes)

def inventory():
    rows=[]
    f="foster2025.machine_mode"; w="wadsworth2026.inertial"; c="cameron2020.extraction_bdf"
    rows += [_row(f,"machine","machine_generated_pressure","output","Pa","node-specific absolute pressure","Pump/headspace pressure generated by source machine closure","derived","NOT_PROVIDED","source_curve_reproduction","pressure",node="HEADSPACE",reference="ABSOLUTE"),
             _row(f,"machine","bed_darcy_flow","output","m^3/s","bed inlet volumetric flow","Fixed-bed infiltration flow","derived","NOT_PROVIDED","source_curve_reproduction","flow",node="BED_INLET",reference="DIFFERENTIAL",flow="VOLUMETRIC_FLOW_RATE"),
             _row(f,"machine","wetting_front","state","m","axial front from bed inlet","Sharp wetting-front position","state",{"min":0,"max":"bed_depth"},"source_curve_reproduction","wetting"),
             _row(f,"machine","extraction_yield","output","%","dry coffee mass","Chemistry not defined by this component","derived","NOT_PROVIDED","source_curve_reproduction","extraction_yield","UNSUPPORTED_RELATIONSHIP")]
    rows += [_row(w,"flow","bed_pressure_drop","input","Pa","bed differential pressure","Pressure drop applied across fixed bed","controlled","NOT_PROVIDED","source_curve_reproduction","pressure",node="BED_PRESSURE_DROP",reference="DIFFERENTIAL"),
             _row(w,"flow","permeability","input","m^2","intrinsic Darcy permeability","Declared permeability input","controlled","strict_SI_positive","source_curve_reproduction","permeability"),
             _row(w,"flow","darcy_velocity","output","m/s","superficial inlet-area basis","Forchheimer superficial velocity","derived","strict_SI_positive","source_curve_reproduction","darcy_velocity",flow="SUPERFICIAL_DARCY_VELOCITY"),
             _row(w,"flow","forchheimer_number","output","1","bed-average closure basis","Ratio of inertial to viscous terms","derived","NOT_PROVIDED","source_curve_reproduction","forchheimer"),
             _row(w,"flow","tds","output","mass_percent_cup","cup beverage mass","Chemistry not defined by this component","derived","NOT_PROVIDED","source_curve_reproduction","tds","UNSUPPORTED_RELATIONSHIP")]
    rows += [_row(c,"extraction","pump_overpressure","input","bar","pump overpressure above atmosphere","Cameron SI pressure convention","controlled",{"min":5.0,"max":11.0},"code_verification","pressure",node="PUMP_OUTLET",reference="GAUGE"),
             _row(c,"extraction","darcy_velocity","input","m/s","superficial bed-area basis","Scalar Darcy-flux override","controlled","positive","code_verification","darcy_velocity",flow="SUPERFICIAL_DARCY_VELOCITY"),
             _row(c,"extraction","outlet_concentration","output","kg/m^3","instantaneous bed-outlet liquid","Dissolved concentration at bed outlet","derived","NOT_PROVIDED","code_verification","outlet_concentration",mass="DISSOLVED_SOLIDS_PER_LIQUID_VOLUME"),
             _row(c,"extraction","tds","output","mass_percent_cup","accumulated cup beverage mass","Final cup dissolved-solids mass fraction","derived","NOT_PROVIDED","code_verification","tds",mass="DISSOLVED_SOLIDS_PER_CUP_MASS"),
             _row(c,"extraction","extraction_yield","output","percent","initial dry-coffee mass","Accumulated extracted solids divided by dose","derived","NOT_PROVIDED","code_verification","extraction_yield",mass="DISSOLVED_SOLIDS_PER_DRY_COFFEE_MASS"),
             _row(c,"extraction","bed_deformation","output","m","bed height change","Deformation not defined by this component","derived","NOT_PROVIDED","code_verification","deformation","UNSUPPORTED_RELATIONSHIP")]
    return [r.to_dict() for r in sorted(rows,key=lambda x:(x.component_id,x.quantity_name))]
