"""Canonical project-status source of truth (P0.1).

`docs/status/current.json` is the SINGLE machine-readable status source. This module generates
`docs/planning/STATE_OF_TRUTH.md` from it deterministically and verifies it in CI:

    python -m puckworks.statusdoc --write            # regenerate the Markdown
    python -m puckworks.statusdoc --verify            # structural + freshness + phrase checks
    python -m puckworks.statusdoc --audit-ruleset     # (needs gh auth) intended vs actual required checks

The verifier fails on stale/contradictory state: a completed item that is also active/blocked, a
completed item whose commit does not resolve, an active/blocked item with no next gate, an
external blocker with no resumption trigger, more than five active items, prohibited transient
phrases in the generated document, or a generated document that differs from the checked-in copy.
"""
import json
import subprocess
from pathlib import Path

SCHEMA_VERSION = 1
REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_REL = "docs/status/current.json"
DOC_REL = "docs/planning/STATE_OF_TRUTH.md"

STATES = ("proposed", "active", "blocked", "complete", "superseded")
MAX_ACTIVE = 5
# transient wording that must never appear in the GENERATED canonical document
PROHIBITED_PHRASES = ("this pr", "current branch", "pending commit", "pending)")
_REQUIRED_FIELDS = ("id", "title", "area", "state", "priority", "owner_type", "external_blocker",
                    "resume_trigger", "next_gate", "acceptance_evidence", "issue_or_pr",
                    "verified_commit", "verified_date")

_BANNER = ("<!-- GENERATED by `python -m puckworks.statusdoc --write` from docs/status/current.json."
           " DO NOT EDIT BY HAND — edits are overwritten and fail CI. Curate current.json. -->")


def load(root=REPO_ROOT):
    with open(Path(root) / SOURCE_REL, encoding="utf-8") as fh:
        return json.load(fh)


def _commit_resolves(sha, root=REPO_ROOT):
    """True iff `sha` resolves to a commit in the local repo (needs full history in CI)."""
    if not sha:
        return False
    try:
        r = subprocess.run(["git", "-C", str(root), "cat-file", "-e", "%s^{commit}" % sha],
                           capture_output=True)
        return r.returncode == 0
    except Exception:
        return False


def validate(data, root=REPO_ROOT, check_commits=True):
    """Structural validation of the status source. Returns a list of problem strings."""
    problems = []
    if data.get("schema_version") != SCHEMA_VERSION:
        problems.append("schema_version must be %d" % SCHEMA_VERSION)
    items = data.get("items", [])
    seen = set()
    for it in items:
        iid = it.get("id", "<no id>")
        if iid in seen:
            problems.append("duplicate id: %s" % iid)
        seen.add(iid)
        for f in _REQUIRED_FIELDS:
            if f not in it:
                problems.append("%s: missing field %r" % (iid, f))
        st = it.get("state")
        if st not in STATES:
            problems.append("%s: bad state %r" % (iid, st))
        if st in ("active", "blocked") and not it.get("next_gate"):
            problems.append("%s: %s item has no next_gate" % (iid, st))
        if it.get("external_blocker") and not it.get("resume_trigger"):
            problems.append("%s: external_blocker set but no resume_trigger" % iid)
        if st == "complete":
            if not it.get("issue_or_pr"):
                problems.append("%s: complete item has no issue_or_pr" % iid)
            if not it.get("verified_date"):
                problems.append("%s: complete item has no verified_date" % iid)
            sha = it.get("verified_commit")
            if not sha:
                problems.append("%s: complete item has no verified_commit" % iid)
            elif check_commits and not _commit_resolves(sha, root):
                problems.append("%s: verified_commit %r does not resolve to a commit" % (iid, sha))
        # a blocked item that also claims completion evidence is contradictory
        if st != "complete" and it.get("verified_commit") and st != "superseded":
            problems.append("%s: non-complete item carries a verified_commit (%r) — contradictory"
                            % (iid, it.get("verified_commit")))
    n_active = sum(1 for it in items if it.get("state") == "active")
    if n_active > MAX_ACTIVE:
        problems.append("active queue has %d items (max %d)" % (n_active, MAX_ACTIVE))
    return problems


def _by_state(items, state):
    return [it for it in items if it.get("state") == state]


def _md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x).replace("|", "\\|") for x in r) + " |")
    return "\n".join(out)


def render(data):
    """Deterministic Markdown from the status source (no transient phrases, no timestamps)."""
    items = data.get("items", [])
    active = _by_state(items, "active")
    L = [_BANNER, "", "# PUCKWORKS — STATE OF TRUTH", "",
         "Generated from `%s` (the single machine-readable status source). Regenerate with "
         "`python -m puckworks.statusdoc --write`; CI fails on stale or contradictory state. The "
         "active queue is capped at %d outcomes; completed history and superseded plans are in "
         "their own sections below." % (SOURCE_REL, MAX_ACTIVE), "",
         "## Active queue (%d / %d)" % (len(active), MAX_ACTIVE), ""]
    if active:
        L.append(_md_table(
            ["id", "title", "area", "priority", "owner", "next gate", "acceptance evidence"],
            [[it["id"], it["title"], it["area"], it["priority"], it["owner_type"],
              it["next_gate"], it["acceptance_evidence"]] for it in active]))
    else:
        L.append("_No active outcomes._")
    proposed = _by_state(items, "proposed")
    if proposed:
        L += ["", "## Proposed (next up)", "",
              _md_table(["id", "title", "area", "priority", "owner"],
                        [[it["id"], it["title"], it["area"], it["priority"], it["owner_type"]]
                         for it in proposed])]
    blocked = _by_state(items, "blocked")
    if blocked:
        L += ["", "## Blocked", "",
              _md_table(["id", "title", "blocker", "resumption trigger", "owner"],
                        [[it["id"], it["title"], it["external_blocker"], it["resume_trigger"],
                          it["owner_type"]] for it in blocked])]
    complete = _by_state(items, "complete")
    if complete:
        L += ["", "## Completed (generated — not the active queue)", "",
              _md_table(["id", "title", "PR", "commit", "date"],
                        [[it["id"], it["title"], it["issue_or_pr"], it["verified_commit"],
                          it["verified_date"]] for it in complete])]
    superseded = _by_state(items, "superseded")
    if superseded:
        L += ["", "## Superseded planning snapshots", "",
              "Historical; not an authoritative statement of current status (archived under "
              "`docs/planning/archive/`):", ""]
        for it in superseded:
            L.append("- **%s** — %s" % (it["id"], it["title"]))
    L.append("")
    return "\n".join(L) + "\n"


def write(root=REPO_ROOT):
    data = load(root)
    (Path(root) / DOC_REL).write_text(render(data), encoding="utf-8")
    return DOC_REL


def verify(root=REPO_ROOT, check_commits=True):
    """Full verify: structural + prohibited phrases + generated == checked-in. Problem list."""
    data = load(root)
    problems = validate(data, root, check_commits=check_commits)
    doc = render(data)
    low = doc.lower()
    for p in PROHIBITED_PHRASES:
        if p in low:
            problems.append("generated document contains prohibited transient phrase %r" % p)
    checked = Path(root) / DOC_REL
    if not checked.exists() or checked.read_text(encoding="utf-8") != doc:
        problems.append("%s is stale — run `python -m puckworks.statusdoc --write`" % DOC_REL)
    return problems


def audit_ruleset(repo="trbrewer/puckworks", branch="main",
                  intended=("quick (3.10)", "quick (3.12)", "verify-generated",
                            "paper3-scope-strict", "all-scope-strict")):
    """Query the GitHub ruleset API (needs `gh` auth) and report intended-vs-actual required
    checks. Repository PROSE cannot establish an external GitHub setting — this reads the setting.
    Returns (ok, report_dict)."""
    try:
        out = subprocess.run(["gh", "api", "repos/%s/rulesets" % repo], capture_output=True,
                             text=True, check=True).stdout
        rulesets = json.loads(out)
    except Exception as e:  # pragma: no cover - needs network/auth
        return False, {"error": "cannot query ruleset API: %s" % e}
    required = set()
    active = False
    for rs in rulesets:
        try:
            det = subprocess.run(["gh", "api", "repos/%s/rulesets/%s" % (repo, rs["id"])],
                                 capture_output=True, text=True, check=True).stdout
            r = json.loads(det)
        except Exception:  # pragma: no cover
            continue
        for rule in r.get("rules", []):
            if rule.get("type") == "required_status_checks":
                active = active or r.get("enforcement") == "active"
                for c in rule["parameters"].get("required_status_checks", []):
                    required.add(c.get("context"))
    missing = sorted(set(intended) - required)
    extra = sorted(required - set(intended))
    return (active and not missing), {"enforcement_active": active,
                                      "required": sorted(required), "intended": list(intended),
                                      "missing_intended": missing, "unexpected_extra": extra}


def main(argv=None):
    import sys
    argv = sys.argv[1:] if argv is None else argv
    if "--write" in argv:
        print("wrote:", write())
        return 0
    if "--audit-ruleset" in argv:
        ok, rep = audit_ruleset()
        print(json.dumps(rep, indent=2))
        return 0 if ok else 1
    if "--verify" in argv:
        problems = verify(check_commits="--no-commit-check" not in argv)
        if problems:
            print("STATUS VERIFY FAILED (%d):" % len(problems))
            for p in problems:
                print("  -", p)
            return 1
        print("status source is valid and %s is up to date" % DOC_REL)
        return 0
    print("usage: --write | --verify [--no-commit-check] | --audit-ruleset")
    return 0


if __name__ == "__main__":   # pragma: no cover
    raise SystemExit(main())
