"""Paper 3 per-claim EVIDENCE GRAPH (WP2.4; schema v2 — scope + semantic integrity).

One typed `EvidenceLink` per registry gate wiring (a gate may split into several claim links).
v2 adds the scoping and provenance fields needed for FAIL-CLOSED, SCOPED Paper-3 release
validation without forcing every unrelated or future gate to be empirically resolved:

  * claim ownership + Paper-3 use + reality-facing + support status;
  * a typed `sources[]` list (source_card + exact MANIFEST dataset ids + dataset_status +
    evidence_role + independence + note) so an empty dataset list never silently stands for the
    many distinct "no dataset" reasons;
  * a link-level `relationship` (the honest fit/evaluation relationship) that the mechanical
    guards check against the actual fit/eval dataset overlap.

Integrity invariants (enforced by `reconcile()`):
  * bijection with the LIVE registry wirings;
  * NOTHING promotes a claim's tier by inference — drafts carry null tiers and are the only thing
    the bootstrap emits; a tier is set only by a human ADJUDICATED flip with every field filled;
  * the stored `component_evidence_strength` must EQUAL the live registry value;
  * fit/eval dataset overlap may not be labelled `independent_external` or `within_campaign_held_out`;
  * `code_verification` may not be labelled empirical; `source_curve_reproduction` may not be
    `independent_external`; a post-fit-same-data relationship may not carry a top tier.

Scoped strict modes:
  * `--strict --scope paper3` — fail-closed on the ASSERTED Paper-3 claims (claim_owner==paper3
    and paper3_use in {primary_claim, method_demonstration}); ignores honestly out-of-scope,
    future, or project-only gates. This is the release gate.
  * `--strict --scope all` — additionally require the WHOLE graph adjudicated (manual/nonblocking).

Source of truth (curate): `EVIDENCE_LINKS.json`. Generated (never hand-edit; CI fails on drift):
the full matrix (csv/md), the machine export, the summary, the Paper-3 priority matrix, the
adjudication queue, and the narrative conflicts report under `docs/paper3_resource/generated/`.

CLI:
    python -m puckworks.paper3.evidence_graph --reconcile [--strict --scope paper3|all]
    python -m puckworks.paper3.evidence_graph --bootstrap | --write | --verify
"""
import csv
import hashlib
import io
import json
from pathlib import Path

import puckworks.models  # noqa: F401  (registers all components)
from puckworks import registry as R

SCHEMA_VERSION = 2
REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_REL = "docs/paper3_resource/generated"
_LINKS_JSON = Path(__file__).resolve().parent / "EVIDENCE_LINKS.json"
_MANIFEST = REPO_ROOT / "puckworks" / "data" / "MANIFEST.csv"
_CARDS_DIR = REPO_ROOT / "docs" / "cards"

_BANNER = ("GENERATED by `python -m puckworks.paper3.evidence_graph --write` from "
           "EVIDENCE_LINKS.json + the live registry. DO NOT EDIT BY HAND — edits are "
           "overwritten and fail CI. Curate EVIDENCE_LINKS.json instead.")
_HTML_BANNER = "<!-- " + _BANNER + " -->"

# ---- controlled vocabularies -------------------------------------------------------------
ADJUDICATION_STATES = ("ADJUDICATED", "NEEDS_ADJUDICATION")
CLAIM_OWNERS = ("paper3", "paper_b2", "paper_a", "paper4_future", "project_only")
PAPER3_USES = ("primary_claim", "method_demonstration", "resource_context", "cited_science",
               "not_in_scope")
SUPPORT_STATUS = ("admissible", "context_only", "unsupported", "blocked_missing",
                  "proposed_not_run", "needs_adjudication")
# the honest fit/evaluation relationship of the link as a whole (authoritative for the guards)
RELATIONSHIPS = ("independent_external", "within_campaign_held_out", "same_campaign_not_held_out",
                 "post_fit_same_data", "code_verification", "not_empirical")
DATASET_STATUS = ("resolved_manifest", "not_applicable_code", "not_applicable_source_equation",
                  "not_applicable_synthetic", "proposed_experiment", "blocked_missing",
                  "needs_adjudication")
EVIDENCE_ROLES = ("fit", "eval", "reference", "context")
SOURCE_INDEPENDENCE = ("independent", "held_out_same_campaign", "same_campaign", "same_data_as_fit",
                       "fit_input", "not_applicable")
EVIDENCE_STRENGTHS = R.EVIDENCE_STRENGTHS

# asserted Paper-3 claims that the paper3 release gate is fail-closed on
_ASSERTED_PAPER3_USES = ("primary_claim", "method_demonstration")
# sentinels that must never survive into an ADJUDICATED link
_PLACEHOLDERS = ("TODO", "TBD", "NEEDS_ADJUDICATION", "FIXME", "XXX", "PLACEHOLDER")
_REQUIRED_WHEN_ADJUDICATED = ("claim", "observable", "caveat", "claim_not_supported",
                              "evidence_strength", "relationship", "claim_owner", "paper3_use",
                              "support_status")

# Known un-reconciled published constants (CLAUDE.md rule 6 — surfaced, never silently merged).
CONSTANT_CONFLICTS = (
    {"constant": "c_sat (saturation concentration, kg/m^3)",
     "reference": "docs/ROADMAP.md §5.4",
     "values": {"212.4": ["cameron2020", "lee2023", "moroney2016", "egidi2024"],
                "224": ["grudeva2026 (paper)"],
                "170": ["grudeva2023 (thesis)"]},
     "note": "Per ROADMAP §5.4: 212.4 kg/m^3 is a single shared-provenance value across "
             "cameron2020/lee2023/moroney2016/egidi2024; grudeva's paper (224) and thesis (170) "
             "sets disagree with it and each other (grudeva card-of-record reconciliation is "
             "ROADMAP item 1.7a). The value is a surfaced config field, never a merged constant."},
)


# ---- registry / manifest / card views ----------------------------------------------------
def registry_gate_wirings():
    """The live set of (component_id, gate_name) wirings, plus per-component context."""
    wirings = []
    ctx = {}
    for c in sorted(R.components(), key=lambda c: (c.stage, c.name)):
        ctx[c.name] = {"stage": c.stage, "execution_role": c.execution_role,
                       "provenance_class": c.provenance_class,
                       "component_evidence_strength": c.evidence_strength or "unclassified"}
        for g in sorted(c.gates, key=lambda g: g.__name__):
            wirings.append((c.name, g.__name__))
    return wirings, ctx


def _manifest_dataset_ids():
    if not _MANIFEST.exists():
        return set()
    with open(_MANIFEST, newline="", encoding="utf-8-sig") as fh:
        return {row["dataset_id"] for row in csv.DictReader(fh) if row.get("dataset_id")}


def _manifest_source_cards():
    """The set of source_card provenance strings the MANIFEST declares (authoritative provenance;
    some are docs/cards stems, some are descriptive strings like '(registry [RS])')."""
    if not _MANIFEST.exists():
        return set()
    with open(_MANIFEST, newline="", encoding="utf-8-sig") as fh:
        return {row.get("source_card", "").strip() for row in csv.DictReader(fh)
                if row.get("source_card", "").strip()}


def _card_stems():
    if not _CARDS_DIR.exists():
        return set()
    return {p.stem for p in _CARDS_DIR.glob("*.md")}


# ---- link IO -----------------------------------------------------------------------------
def load_links(path=_LINKS_JSON):
    if not Path(path).exists():
        return []
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    return data["links"] if isinstance(data, dict) else data


def _draft_skeleton(component, gate, ctx):
    """A conservative NEEDS_ADJUDICATION skeleton. NOTHING is inferred: every per-gate verdict
    (tier, relationship, scope, support) is null; only the component's declared tier is carried
    as context."""
    return {
        "link_id": "%s::%s" % (component, gate),
        "claim_id": "%s::%s" % (component, gate),
        "component": component, "gate": gate, "card": None,
        "claim": None, "observable": None,
        "claim_owner": None, "paper3_use": None, "reality_facing": None,
        "support_status": "needs_adjudication",
        "evidence_strength": None,
        "component_evidence_strength": ctx[component]["component_evidence_strength"],
        "relationship": None, "sources": None,
        "caveat": None, "claim_not_supported": None, "conflict_note": None,
        "adjudication_status": "NEEDS_ADJUDICATION",
    }


def bootstrap_missing(links=None):
    """Return draft skeletons for every registry wiring not already covered by a link."""
    if links is None:
        links = load_links()
    wirings, ctx = registry_gate_wirings()
    covered = {(l["component"], l["gate"]) for l in links}
    return [_draft_skeleton(c, g, ctx) for (c, g) in wirings if (c, g) not in covered]


# ---- helpers -----------------------------------------------------------------------------
def _fit_eval_ids(link):
    """Union of dataset ids playing a fit vs eval role across the link's sources."""
    fit, ev = set(), set()
    for s in (link.get("sources") or []):
        role = s.get("evidence_role")
        for d in (s.get("dataset_manifest_ids") or []):
            if role == "fit":
                fit.add(d)
            elif role == "eval":
                ev.add(d)
    return fit, ev


def _has_placeholder(link):
    for v in link.values():
        if isinstance(v, str) and any(p in v for p in _PLACEHOLDERS) and v not in ADJUDICATION_STATES:
            return True
    return False


def _provenance_resolved(link):
    """True iff every source has a concretely-resolved provenance state (nothing still pending)."""
    for s in (link.get("sources") or []):
        if s.get("dataset_status") in ("needs_adjudication", "blocked_missing"):
            return False
    return True


# ---- reconciler --------------------------------------------------------------------------
def reconcile(links=None, strict=False, scope="all"):
    """Validate the link set against the live registry + manifest + cards. Returns a list of
    problem strings (empty == clean).

    strict=False: structural validity + bijection + adjudicated-completeness + mechanical guards.
    strict=True, scope='paper3': ALSO fail-closed on asserted Paper-3 claims (release gate).
    strict=True, scope='all': ALSO require the WHOLE graph adjudicated (manual)."""
    if links is None:
        links = load_links()
    wirings, ctx = registry_gate_wirings()
    comp_ids = set(ctx)
    comp_gates = {}
    for c, g in wirings:
        comp_gates.setdefault(c, set()).add(g)
    manifest_ids = _manifest_dataset_ids()
    manifest_cards = _manifest_source_cards()
    card_stems = _card_stems()
    valid_source_card = card_stems | manifest_cards
    problems = []

    # 1. bijection with the registry wirings
    covered = {(l["component"], l["gate"]) for l in links}
    for (c, g) in wirings:
        if (c, g) not in covered:
            problems.append("MISSING LINK: registry wiring %s::%s has no evidence link" % (c, g))
    wiring_set = set(wirings)
    for l in links:
        if (l["component"], l["gate"]) not in wiring_set:
            problems.append("ORPHAN LINK %s: (%s, %s) is not a live registry wiring"
                            % (l.get("link_id"), l["component"], l["gate"]))

    seen_ids = set()
    for l in links:
        lid = l.get("link_id") or "<no link_id>"
        if lid in seen_ids:
            problems.append("DUPLICATE link_id: %s" % lid)
        seen_ids.add(lid)
        c, g = l.get("component"), l.get("gate")
        if c not in comp_ids:
            problems.append("%s: unknown component %r" % (lid, c))
            continue
        if g not in comp_gates.get(c, set()):
            problems.append("%s: gate %r is not wired to component %s" % (lid, g, c))

        # 2. structural / vocabulary validity
        def _enum(field, allowed, nullable=True):
            v = l.get(field)
            if v is None and nullable:
                return
            if v not in allowed:
                problems.append("%s: bad %s %r" % (lid, field, v))
        _enum("adjudication_status", ADJUDICATION_STATES, nullable=False)
        _enum("claim_owner", CLAIM_OWNERS)
        _enum("paper3_use", PAPER3_USES)
        _enum("support_status", SUPPORT_STATUS)
        _enum("relationship", RELATIONSHIPS)
        _enum("evidence_strength", EVIDENCE_STRENGTHS)
        if l.get("reality_facing") not in (None, True, False):
            problems.append("%s: reality_facing must be bool/null" % lid)
        if l.get("card") is not None and l["card"] not in card_stems:
            problems.append("%s: card %r is not a card stem" % (lid, l["card"]))
        # component evidence must match the LIVE registry value (no stale stored context)
        live = ctx[c]["component_evidence_strength"]
        if l.get("component_evidence_strength") != live:
            problems.append("%s: component_evidence_strength %r != live registry %r"
                            % (lid, l.get("component_evidence_strength"), live))
        # sources[]
        for s in (l.get("sources") or []):
            sc = s.get("source_card")
            if sc is not None and sc not in valid_source_card:
                problems.append("%s: source_card %r is neither a card stem nor a MANIFEST "
                                "source_card" % (lid, sc))
            if s.get("dataset_status") not in DATASET_STATUS:
                problems.append("%s: bad dataset_status %r" % (lid, s.get("dataset_status")))
            if s.get("evidence_role") not in EVIDENCE_ROLES:
                problems.append("%s: bad evidence_role %r" % (lid, s.get("evidence_role")))
            if s.get("independence") not in SOURCE_INDEPENDENCE:
                problems.append("%s: bad source independence %r" % (lid, s.get("independence")))
            for d in (s.get("dataset_manifest_ids") or []):
                if d not in manifest_ids:
                    problems.append("%s: dataset_id %r not in MANIFEST" % (lid, d))
            # a resolved_manifest source must actually carry manifest ids; the not_applicable /
            # proposed / blocked states must NOT carry resolved ids (empty != resolved)
            if s.get("dataset_status") == "resolved_manifest" and not s.get("dataset_manifest_ids"):
                problems.append("%s: resolved_manifest source has no dataset ids" % lid)

        st = l.get("adjudication_status")
        # 3. completeness + mechanical guards on ADJUDICATED links
        if st == "ADJUDICATED":
            for f in _REQUIRED_WHEN_ADJUDICATED:
                if l.get(f) in (None, "", []):
                    problems.append("%s: ADJUDICATED but %s is empty" % (lid, f))
            if l.get("sources") is None:
                problems.append("%s: ADJUDICATED but sources is null (use [] only if truly none)"
                                % lid)
            if l.get("reality_facing") is None:
                problems.append("%s: ADJUDICATED but reality_facing is null" % lid)
            if _has_placeholder(l):
                problems.append("%s: ADJUDICATED but contains a placeholder value" % lid)

            ev, rel = l.get("evidence_strength"), l.get("relationship")
            fit, evl = _fit_eval_ids(l)
            overlap = fit & evl
            if overlap and rel == "independent_external":
                problems.append("%s: fit/eval datasets overlap (%s) but relationship is "
                                "independent_external" % (lid, sorted(overlap)))
            if overlap and rel == "within_campaign_held_out":
                problems.append("%s: fit/eval datasets overlap (%s) but relationship is "
                                "within_campaign_held_out (held-out means disjoint)"
                                % (lid, sorted(overlap)))
            if ev == "controlled_independent":
                has_indep_eval = any(s.get("evidence_role") == "eval"
                                     and s.get("independence") == "independent"
                                     for s in (l.get("sources") or []))
                if not has_indep_eval:
                    problems.append("%s: controlled_independent but no independent evaluation "
                                    "source" % lid)
            if ev == "within_campaign_held_out":
                if rel != "within_campaign_held_out" or not evl:
                    problems.append("%s: within_campaign_held_out but no held-out evaluation "
                                    "source / relationship" % lid)
            if ev == "code_verification" and rel not in ("code_verification", "not_empirical"):
                problems.append("%s: evidence_strength=code_verification used as empirical "
                                "(relationship=%r)" % (lid, rel))
            if ev == "source_curve_reproduction" and rel == "independent_external":
                problems.append("%s: source_curve_reproduction may not be independent_external"
                                % lid)
            if rel == "post_fit_same_data" and ev in ("controlled_independent",
                                                      "within_campaign_held_out"):
                problems.append("%s: post_fit_same_data cannot carry tier %r" % (lid, ev))

    # 4. scoped strict modes
    if strict and scope == "paper3":
        for l in links:
            if l.get("claim_owner") != "paper3":
                continue
            if l.get("paper3_use") not in _ASSERTED_PAPER3_USES:
                continue
            lid = l.get("link_id")
            if l.get("adjudication_status") != "ADJUDICATED":
                problems.append("PAPER3 %s: asserted Paper-3 claim not adjudicated" % lid)
                continue
            if l.get("support_status") != "admissible":
                problems.append("PAPER3 %s: asserted Paper-3 claim lacks admissible support (%r)"
                                % (lid, l.get("support_status")))
            if not l.get("caveat") or not l.get("claim_not_supported"):
                problems.append("PAPER3 %s: asserted Paper-3 claim lacks caveat / "
                                "claim_not_supported" % lid)
            if not _provenance_resolved(l):
                problems.append("PAPER3 %s: asserted Paper-3 claim has unresolved provenance" % lid)
    if strict and scope == "all":
        n_draft = sum(1 for l in links if l.get("adjudication_status") == "NEEDS_ADJUDICATION")
        if n_draft:
            problems.append("STRICT(all): %d link(s) still NEEDS_ADJUDICATION" % n_draft)
    return problems


# ---- generated artifacts -----------------------------------------------------------------
def _sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sorted_links(links):
    return sorted(links, key=lambda l: (l["component"], l["gate"], l["link_id"]))


def _join(seq):
    return ";".join(seq) if seq else ""


def _all_dataset_ids(link):
    out = []
    for s in (link.get("sources") or []):
        out.extend(s.get("dataset_manifest_ids") or [])
    return out


def _matrix_csv(links, ctx):
    cols = ["link_id", "component", "stage", "gate", "card", "adjudication_status",
            "claim_owner", "paper3_use", "support_status", "reality_facing",
            "evidence_strength", "component_evidence_strength", "relationship",
            "source_cards", "dataset_ids", "fit_datasets", "eval_datasets",
            "observable", "claim", "claim_not_supported"]
    out = ["# " + _BANNER]
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=cols, extrasaction="ignore", lineterminator="\n")
    w.writeheader()
    for l in _sorted_links(links):
        fit, evl = _fit_eval_ids(l)
        src_cards = [s.get("source_card") for s in (l.get("sources") or [])
                     if s.get("source_card")]
        w.writerow({
            "link_id": l["link_id"], "component": l["component"],
            "stage": ctx[l["component"]]["stage"], "gate": l["gate"],
            "card": l.get("card") or "", "adjudication_status": l["adjudication_status"],
            "claim_owner": l.get("claim_owner") or "", "paper3_use": l.get("paper3_use") or "",
            "support_status": l.get("support_status") or "",
            "reality_facing": "" if l.get("reality_facing") is None else l["reality_facing"],
            "evidence_strength": l.get("evidence_strength") or "",
            "component_evidence_strength": l.get("component_evidence_strength") or "",
            "relationship": l.get("relationship") or "",
            "source_cards": _join(src_cards), "dataset_ids": _join(_all_dataset_ids(l)),
            "fit_datasets": _join(sorted(fit)), "eval_datasets": _join(sorted(evl)),
            "observable": (l.get("observable") or "").replace("\n", " "),
            "claim": (l.get("claim") or "").replace("\n", " "),
            "claim_not_supported": (l.get("claim_not_supported") or "").replace("\n", " "),
        })
    out.append(buf.getvalue().rstrip("\n"))
    return "\n".join(out) + "\n"


def _matrix_md(links, ctx):
    adj = [l for l in _sorted_links(links) if l["adjudication_status"] == "ADJUDICATED"]
    draft = [l for l in _sorted_links(links) if l["adjudication_status"] == "NEEDS_ADJUDICATION"]
    L = [_HTML_BANNER, "", "# Paper 3 — per-claim evidence graph (schema v2)", "",
         "One row per registry gate wiring (a gate may split into several claim links). "
         "`evidence_strength` is the **per-gate adjudicated** tier; `component_evidence_strength` "
         "is the component's own declared tier (context only). `relationship` is the honest "
         "fit/evaluation relationship. `NEEDS_ADJUDICATION` rows are drafts — their verdicts are "
         "deliberately blank until curated.", "",
         "**%d links total — %d adjudicated, %d awaiting adjudication.**"
         % (len(links), len(adj), len(draft)), "",
         "## Adjudicated claims", "",
         "| link | owner | p3 use | support | tier | relationship | observable | claim |",
         "|---|---|---|---|---|---|---|---|"]
    for l in adj:
        L.append("| `%s` | %s | %s | %s | %s | %s | %s | %s |" % (
            l["link_id"], l.get("claim_owner") or "—", l.get("paper3_use") or "—",
            l.get("support_status") or "—", l.get("evidence_strength") or "—",
            l.get("relationship") or "—", (l.get("observable") or "—").replace("|", "\\|"),
            (l.get("claim") or "—").replace("|", "\\|")))
    L += ["", "## Awaiting adjudication (drafts)", "",
          "| link | stage | gate | component tier (context) |", "|---|---|---|---|"]
    for l in draft:
        L.append("| `%s` | %s | `%s` | %s |" % (
            l["link_id"], ctx[l["component"]]["stage"], l["gate"],
            l.get("component_evidence_strength") or "—"))
    L.append("")
    return "\n".join(L) + "\n"


def _priority_matrix_md(links, ctx):
    """The Paper-3 priority matrix: asserted Paper-3 claims, with full provenance columns."""
    rows = [l for l in _sorted_links(links) if l.get("claim_owner") == "paper3"
            and l.get("paper3_use") in _ASSERTED_PAPER3_USES]
    L = [_HTML_BANNER, "", "# Paper 3 — priority evidence matrix (asserted claims)", "",
         "The claims the `--strict --scope paper3` release gate is fail-closed on "
         "(claim_owner=paper3, paper3_use in %s). Each exposes source cards, exact dataset ids, "
         "dataset status, fit/eval role, independence, the caveat, and what is NOT supported."
         % (", ".join(_ASSERTED_PAPER3_USES)), "",
         "**%d asserted Paper-3 claim(s).**" % len(rows), ""]
    for l in rows:
        fit, evl = _fit_eval_ids(l)
        L += ["## `%s`" % l["link_id"],
              "- **claim:** %s" % (l.get("claim") or "—"),
              "- **observable:** %s" % (l.get("observable") or "—"),
              "- **tier / relationship:** %s / %s"
              % (l.get("evidence_strength") or "—", l.get("relationship") or "—"),
              "- **paper3_use / support:** %s / %s"
              % (l.get("paper3_use"), l.get("support_status")),
              "- **reality_facing:** %s" % l.get("reality_facing"),
              "- **fit datasets:** %s" % (_join(sorted(fit)) or "(none)"),
              "- **eval datasets:** %s" % (_join(sorted(evl)) or "(none)"),
              "- **sources:**"]
        for s in (l.get("sources") or []):
            L.append("    - `%s` — %s — role=%s, independence=%s%s"
                     % (s.get("source_card") or "(none)",
                        s.get("dataset_status"),
                        s.get("evidence_role"), s.get("independence"),
                        (" — %s" % s["note"]) if s.get("note") else ""))
        L += ["- **caveat:** %s" % (l.get("caveat") or "—"),
              "- **claim NOT supported:** %s" % (l.get("claim_not_supported") or "—"), ""]
    if not rows:
        L.append("_No asserted Paper-3 claims yet._")
        L.append("")
    return "\n".join(L) + "\n"


def _queue_md(links, ctx):
    draft = [l for l in _sorted_links(links) if l["adjudication_status"] == "NEEDS_ADJUDICATION"]
    by_comp = {}
    for l in draft:
        by_comp.setdefault(l["component"], []).append(l)
    L = [_HTML_BANNER, "", "# Paper 3 evidence-graph — adjudication queue", "",
         "%d gate wiring(s) still need a curated per-claim adjudication. For each, fill the v2 "
         "fields in `EVIDENCE_LINKS.json` (claim, observable, claim_owner, paper3_use, "
         "reality_facing, relationship, sources[], evidence_strength, caveat, "
         "claim_not_supported, support_status) and flip `adjudication_status` to `ADJUDICATED`."
         % len(draft), ""]
    for comp in sorted(by_comp):
        L.append("## `%s` — %s (component tier: %s)"
                 % (comp, ctx[comp]["stage"], ctx[comp]["component_evidence_strength"]))
        for l in by_comp[comp]:
            L.append("- [ ] `%s`" % l["gate"])
        L.append("")
    if not draft:
        L.append("_Queue empty — every gate wiring is adjudicated._")
        L.append("")
    return "\n".join(L) + "\n"


def _conflicts_md(links, ctx):
    noted = [l for l in _sorted_links(links) if l.get("conflict_note")]
    L = [_HTML_BANNER, "", "# Paper 3 evidence-graph — narrative conflicts report", "",
         "Disagreements the registry deliberately does NOT average away. Each is a surfaced "
         "config field / documented tension, not a merged constant.", "",
         "## Gate-level conflict notes", ""]
    if noted:
        L += ["| link | gate | conflict |", "|---|---|---|"]
        for l in noted:
            L.append("| `%s` | `%s` | %s |" % (
                l["link_id"], l["gate"], l["conflict_note"].replace("|", "\\|")))
    else:
        L.append("_No gate-level conflict notes recorded yet._")
    L += ["", "## Un-reconciled published constants (surfaced, not merged)", ""]
    for cc in CONSTANT_CONFLICTS:
        L.append("### %s" % cc["constant"])
        L.append(cc["note"])
        if cc.get("reference"):
            L.append("")
            L.append("_Authoritative reconciliation: %s._" % cc["reference"])
        L.append("")
        L += ["| value | source(s) |", "|---|---|"]
        for val, cards in sorted(cc["values"].items()):
            L.append("| %s | %s |" % (val, ", ".join("`%s`" % s for s in cards)))
        L.append("")
    return "\n".join(L) + "\n"


def _summary_json(links, ctx):
    def _count(key):
        out = {}
        for l in links:
            out[str(l.get(key))] = out.get(str(l.get(key)), 0) + 1
        return dict(sorted(out.items()))
    asserted = [l for l in links if l.get("claim_owner") == "paper3"
                and l.get("paper3_use") in _ASSERTED_PAPER3_USES]
    payload = {
        "schema_version": SCHEMA_VERSION, "GENERATED": _BANNER,
        "n_links": len(links),
        "n_adjudicated": sum(1 for l in links if l["adjudication_status"] == "ADJUDICATED"),
        "n_needs_adjudication": sum(1 for l in links
                                    if l["adjudication_status"] == "NEEDS_ADJUDICATION"),
        "n_asserted_paper3_claims": len(asserted),
        "n_asserted_paper3_admissible": sum(1 for l in asserted
                                            if l.get("support_status") == "admissible"),
        "by_claim_owner": _count("claim_owner"),
        "by_paper3_use": _count("paper3_use"),
        "by_support_status": _count("support_status"),
        "by_evidence_strength": _count("evidence_strength"),
        "by_relationship": _count("relationship"),
        "paper3_scope_strict_clean": reconcile(links, strict=True, scope="paper3") == [],
    }
    payload["content_sha256"] = _sha(json.dumps(payload, sort_keys=True, ensure_ascii=False))
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _export_json(links, ctx):
    payload = {"schema_version": SCHEMA_VERSION, "GENERATED": _BANNER, "n_links": len(links),
               "n_adjudicated": sum(1 for l in links
                                    if l["adjudication_status"] == "ADJUDICATED"),
               "links": _sorted_links(links)}
    payload["content_sha256"] = _sha(json.dumps(payload, sort_keys=True, ensure_ascii=False))
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def generate():
    """Return {relpath: content_str} for every evidence-graph artifact (deterministic)."""
    links = load_links()
    _, ctx = registry_gate_wirings()
    return {
        "evidence_graph_matrix.csv": _matrix_csv(links, ctx),
        "evidence_graph_matrix.md": _matrix_md(links, ctx),
        "evidence_graph.json": _export_json(links, ctx),
        "evidence_graph_summary.json": _summary_json(links, ctx),
        "paper3_priority_evidence_matrix.md": _priority_matrix_md(links, ctx),
        "evidence_adjudication_queue.md": _queue_md(links, ctx),
        "evidence_conflicts.md": _conflicts_md(links, ctx),
    }


def write(root=REPO_ROOT):
    out_dir = Path(root) / GENERATED_REL
    out_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in generate().items():
        (out_dir / rel).write_text(content, encoding="utf-8")
    return sorted(generate())


def verify(root=REPO_ROOT):
    out_dir = Path(root) / GENERATED_REL
    stale = []
    for rel, content in generate().items():
        p = out_dir / rel
        if (not p.exists()) or p.read_text(encoding="utf-8") != content:
            stale.append(rel)
    return stale


def main(argv=None):
    import sys
    argv = sys.argv[1:] if argv is None else argv
    if "--reconcile" in argv:
        strict = "--strict" in argv
        scope = "all"
        if "--scope" in argv:
            i = argv.index("--scope")
            scope = argv[i + 1] if i + 1 < len(argv) else "all"
        problems = reconcile(strict=strict, scope=scope)
        tag = (" --strict --scope %s" % scope) if strict else ""
        if problems:
            print("EVIDENCE GRAPH RECONCILE FAILED%s (%d):" % (tag, len(problems)))
            for p in problems:
                print("  -", p)
            return 1
        print("evidence graph reconciles with the live registry%s" % tag)
        return 0
    if "--bootstrap" in argv:
        print(json.dumps(bootstrap_missing(), indent=2))
        return 0
    if "--verify" in argv:
        s = verify()
        print("stale artifacts:", s or "none")
        return 1 if s else 0
    if "--write" in argv:
        print("wrote:", write())
        return 0
    print(json.dumps({k: len(v) for k, v in generate().items()}, indent=2))
    return 0


if __name__ == "__main__":   # pragma: no cover
    raise SystemExit(main())
