"""Paper 3 per-claim EVIDENCE GRAPH (WP2.4).

Replaces the gate-name-only `component_gate_matrix.csv` with a curated, TYPED evidence graph:
one `EvidenceLink` per registry gate wiring (a gate may split into several links when it backs
several distinct claims), each carrying the specific claim, the observable compared, the source
cards, the exact MANIFEST dataset ids with their fit/eval roles, the independence of the
evaluation, the honest per-gate evidence strength, a caveat, and what the gate does NOT
establish.

Design invariants (integrity — enforced by `reconcile()`):
  * The link set is reconciled against the LIVE registry: every (component, gate) wiring is
    covered by >=1 link, and every link points at a real wiring, real dataset ids, real cards.
  * NOTHING here promotes a claim's evidence tier by inference. The bootstrap emits only
    `NEEDS_ADJUDICATION` drafts with `evidence_strength = null`; a link earns a tier ONLY by a
    human setting `adjudication_status = "ADJUDICATED"` with every curated field filled.
  * The registry's component-level `evidence_strength` is copied onto each link ONLY as
    `component_evidence_strength` (context — the component's self-declared tier), never as the
    link's own adjudicated verdict.
  * Vocabulary guards forbid the two labelling errors the project bans: source-curve
    reproduction may not be called `independent`; code/conservation checks may not be called
    empirical (their independence must be `code_verification`/`not_empirical`).
  * `dataset_ids = []` (gate loads no dataset) is DISTINCT from a null/absent field (not yet
    adjudicated). Drafts leave curated fields `null`; adjudicated links must fill them.

Source of truth (hand-curated, editable): `EVIDENCE_LINKS.json` (this directory).
Generated (deterministic, no timestamp, banner, sha256 — CI fails on drift): the matrix, the
machine export, the adjudication queue, and the G10 narrative conflicts report under
`docs/paper3_resource/generated/`.

CLI:
    python -m puckworks.paper3.evidence_graph --reconcile [--strict]   # validate vs registry
    python -m puckworks.paper3.evidence_graph --bootstrap             # print draft skeletons
    python -m puckworks.paper3.evidence_graph --write                 # regenerate artifacts
    python -m puckworks.paper3.evidence_graph --verify                # fail on stale artifacts
"""
import csv
import hashlib
import json
from pathlib import Path

import puckworks.models  # noqa: F401  (registers all components)
from puckworks import registry as R

SCHEMA_VERSION = 1
REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_REL = "docs/paper3_resource/generated"
_LINKS_JSON = Path(__file__).resolve().parent / "EVIDENCE_LINKS.json"
_MANIFEST = REPO_ROOT / "puckworks" / "data" / "MANIFEST.csv"
_CARDS_DIR = REPO_ROOT / "docs" / "cards"

_BANNER = ("GENERATED by `python -m puckworks.paper3.evidence_graph --write` from "
           "EVIDENCE_LINKS.json + the live registry. DO NOT EDIT BY HAND — edits are "
           "overwritten and fail CI. Curate EVIDENCE_LINKS.json instead.")
_HTML_BANNER = "<!-- " + _BANNER + " -->"

# ---- controlled vocabularies -------------------------------------------------------------
ADJUDICATION_STATES = ("ADJUDICATED", "NEEDS_ADJUDICATION")
INDEPENDENCE_KINDS = (
    "independent",                 # eval data disjoint from fit / parameter-free
    "within_campaign_held_out",    # held-out slice of the same measurement campaign
    "post_fit_reconstruction",     # evaluated on the same data used to fit
    "code_verification",           # checks a code/math property, not empirical
    "not_empirical",               # no measured data compared at all
)
# per-link honest tier: the registry enum (registry.EVIDENCE_STRENGTHS is authoritative)
EVIDENCE_STRENGTHS = R.EVIDENCE_STRENGTHS
# curated fields that MUST be present for an ADJUDICATED link
_REQUIRED_WHEN_ADJUDICATED = (
    "claim", "observable", "independence", "evidence_strength", "caveat",
    "claim_not_supported",
)

# Known un-reconciled physical constants (CLAUDE.md rule 6 — surfaced, never silently merged).
# These are config fields with conflicting published values across source cards; the conflicts
# report lists them so a reader sees the disagreement rather than an averaged-away number.
CONSTANT_CONFLICTS = (
    {"constant": "c_sat (saturation concentration, kg/m^3)",
     "reference": "docs/ROADMAP.md §5.4",
     "values": {"212.4": ["cameron2020", "lee2023", "moroney2016", "egidi2024"],
                "224": ["grudeva2026 (paper)"],
                "170": ["grudeva2023 (thesis)"]},
     "note": "Per ROADMAP §5.4: 212.4 kg/m^3 is a single shared-provenance value across "
             "cameron2020/lee2023/moroney2016/egidi2024; grudeva's paper (224) and thesis (170) "
             "sets disagree with it and each other (grudeva card-of-record reconciliation is "
             "ROADMAP item 1.7a). The value is a surfaced config field, never a merged constant."},
)


# ---- registry / manifest / card views ----------------------------------------------------
def _components():
    return {c.name: c for c in R.components()}


def registry_gate_wirings():
    """The live set of (component_id, gate_name) wirings, plus per-component context."""
    wirings = []
    ctx = {}
    for c in sorted(R.components(), key=lambda c: (c.stage, c.name)):
        ctx[c.name] = {"stage": c.stage, "execution_role": c.execution_role,
                       "provenance_class": c.provenance_class,
                       "component_evidence_strength": c.evidence_strength or "unclassified"}
        for g in sorted(c.gates, key=lambda g: g.__name__):
            wirings.append((c.name, g.__name__))
    return wirings, ctx


def _manifest_dataset_ids():
    if not _MANIFEST.exists():
        return set()
    with open(_MANIFEST, newline="", encoding="utf-8-sig") as fh:
        return {row["dataset_id"] for row in csv.DictReader(fh) if row.get("dataset_id")}


def _card_stems():
    if not _CARDS_DIR.exists():
        return set()
    return {p.stem for p in _CARDS_DIR.glob("*.md")}


# ---- link IO -----------------------------------------------------------------------------
def load_links(path=_LINKS_JSON):
    if not Path(path).exists():
        return []
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    return data["links"] if isinstance(data, dict) else data


def _draft_skeleton(component, gate, ctx):
    """A conservative NEEDS_ADJUDICATION skeleton. NOTHING is inferred: the per-gate
    evidence_strength is null (only the component's declared tier is carried, as context)."""
    return {
        "link_id": "%s::%s" % (component, gate),
        "component": component,
        "gate": gate,
        "card": None,
        "claim": None,
        "observable": None,
        "source_cards": None,
        "dataset_ids": None,
        "dataset_role": None,
        "independence": None,
        "evidence_strength": None,
        "component_evidence_strength": ctx[component]["component_evidence_strength"],
        "caveat": None,
        "claim_not_supported": None,
        "conflict_note": None,
        "adjudication_status": "NEEDS_ADJUDICATION",
    }


def bootstrap_missing(links=None):
    """Return draft skeletons for every registry wiring not already covered by a link.
    Used once to prefill EVIDENCE_LINKS.json; never auto-writes (curation is a human step)."""
    if links is None:
        links = load_links()
    wirings, ctx = registry_gate_wirings()
    covered = {(l["component"], l["gate"]) for l in links}
    return [_draft_skeleton(c, g, ctx) for (c, g) in wirings if (c, g) not in covered]


# ---- reconciler --------------------------------------------------------------------------
def reconcile(links=None, strict=False):
    """Validate the link set against the live registry + manifest + cards. Returns a list of
    problem strings (empty == clean). `strict` additionally requires zero NEEDS_ADJUDICATION."""
    if links is None:
        links = load_links()
    wirings, ctx = registry_gate_wirings()
    comp_ids = set(ctx)
    comp_gates = {}
    for c, g in wirings:
        comp_gates.setdefault(c, set()).add(g)
    manifest_ids = _manifest_dataset_ids()
    card_stems = _card_stems()
    problems = []

    # 1. bijection with the registry wirings
    covered = {(l["component"], l["gate"]) for l in links}
    for (c, g) in wirings:
        if (c, g) not in covered:
            problems.append("MISSING LINK: registry wiring %s::%s has no evidence link" % (c, g))
    for l in links:
        if (l["component"], l["gate"]) not in set(wirings):
            problems.append("ORPHAN LINK %s: (%s, %s) is not a live registry wiring"
                            % (l.get("link_id"), l["component"], l["gate"]))

    # 2. per-link structural + integrity validation
    seen_ids = set()
    for l in links:
        lid = l.get("link_id") or "<no link_id>"
        if lid in seen_ids:
            problems.append("DUPLICATE link_id: %s" % lid)
        seen_ids.add(lid)
        c, g = l.get("component"), l.get("gate")
        if c not in comp_ids:
            problems.append("%s: unknown component %r" % (lid, c))
        elif g not in comp_gates.get(c, set()):
            problems.append("%s: gate %r is not wired to component %s" % (lid, g, c))
        st = l.get("adjudication_status")
        if st not in ADJUDICATION_STATES:
            problems.append("%s: bad adjudication_status %r" % (lid, st))
        ind = l.get("independence")
        if ind is not None and ind not in INDEPENDENCE_KINDS:
            problems.append("%s: bad independence %r" % (lid, ind))
        ev = l.get("evidence_strength")
        if ev is not None and ev not in EVIDENCE_STRENGTHS:
            problems.append("%s: bad evidence_strength %r" % (lid, ev))
        for stem_field in ("card",):
            v = l.get(stem_field)
            if v is not None and v not in card_stems:
                problems.append("%s: %s %r is not a card stem" % (lid, stem_field, v))
        for stem in (l.get("source_cards") or []):
            if stem not in card_stems:
                problems.append("%s: source_card %r is not a card stem" % (lid, stem))
        for did in (l.get("dataset_ids") or []):
            if did not in manifest_ids:
                problems.append("%s: dataset_id %r not in MANIFEST" % (lid, did))
        # dataset_role keys must be a subset of dataset_ids, values a known role
        roles = l.get("dataset_role") or {}
        for did, role in roles.items():
            if did not in (l.get("dataset_ids") or []):
                problems.append("%s: dataset_role references %r not in dataset_ids" % (lid, did))
            if role not in ("fit", "eval", "both", "reference"):
                problems.append("%s: bad dataset role %r for %r" % (lid, role, did))

        # 3. completeness + vocabulary guards for ADJUDICATED links
        if st == "ADJUDICATED":
            for f in _REQUIRED_WHEN_ADJUDICATED:
                if l.get(f) in (None, "", []):
                    problems.append("%s: ADJUDICATED but %s is empty" % (lid, f))
            if l.get("dataset_ids") is None:
                problems.append("%s: ADJUDICATED but dataset_ids is null (use [] if none)" % lid)
            # every declared dataset must carry a role
            for did in (l.get("dataset_ids") or []):
                if did not in roles:
                    problems.append("%s: ADJUDICATED but dataset %r has no fit/eval role"
                                    % (lid, did))
            # vocabulary integrity: the two banned mislabels
            if ev == "code_verification" and ind not in ("code_verification", "not_empirical"):
                problems.append("%s: evidence_strength=code_verification but independence=%r "
                                "(a code/conservation check is not empirical)" % (lid, ind))
            if ev == "controlled_independent" and ind != "independent":
                problems.append("%s: controlled_independent requires independence=independent, "
                                "got %r" % (lid, ind))
            if ev == "source_curve_reproduction" and ind == "independent":
                problems.append("%s: source_curve_reproduction may not be labelled independent"
                                % lid)
            if ind == "post_fit_reconstruction" and ev in ("controlled_independent",
                                                            "within_campaign_held_out"):
                problems.append("%s: post-fit reconstruction cannot be tier %r" % (lid, ev))

    if strict:
        n_draft = sum(1 for l in links if l.get("adjudication_status") == "NEEDS_ADJUDICATION")
        if n_draft:
            problems.append("STRICT: %d link(s) still NEEDS_ADJUDICATION" % n_draft)
    return problems


# ---- generated artifacts -----------------------------------------------------------------
def _sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sorted_links(links):
    return sorted(links, key=lambda l: (l["component"], l["gate"], l["link_id"]))


def _join(seq):
    return ";".join(seq) if seq else ""


def _matrix_csv(links, ctx):
    cols = ["link_id", "component", "stage", "gate", "card", "adjudication_status",
            "evidence_strength", "component_evidence_strength", "independence",
            "observable", "dataset_ids", "fit_datasets", "eval_datasets",
            "claim", "claim_not_supported"]
    out = ["# " + _BANNER]
    import io
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=cols, extrasaction="ignore", lineterminator="\n")
    w.writeheader()
    for l in _sorted_links(links):
        roles = l.get("dataset_role") or {}
        fit = [d for d in (l.get("dataset_ids") or []) if roles.get(d) in ("fit", "both")]
        ev = [d for d in (l.get("dataset_ids") or []) if roles.get(d) in ("eval", "both")]
        w.writerow({
            "link_id": l["link_id"], "component": l["component"],
            "stage": ctx[l["component"]]["stage"], "gate": l["gate"],
            "card": l.get("card") or "", "adjudication_status": l["adjudication_status"],
            "evidence_strength": l.get("evidence_strength") or "",
            "component_evidence_strength": l.get("component_evidence_strength") or "",
            "independence": l.get("independence") or "",
            "observable": (l.get("observable") or "").replace("\n", " "),
            "dataset_ids": _join(l.get("dataset_ids") if l.get("dataset_ids") is not None else []),
            "fit_datasets": _join(fit), "eval_datasets": _join(ev),
            # csv.DictWriter quotes fields containing commas — keep the prose intact
            "claim": (l.get("claim") or "").replace("\n", " "),
            "claim_not_supported": (l.get("claim_not_supported") or "").replace("\n", " "),
        })
    out.append(buf.getvalue().rstrip("\n"))
    return "\n".join(out) + "\n"


def _matrix_md(links, ctx):
    adj = [l for l in _sorted_links(links) if l["adjudication_status"] == "ADJUDICATED"]
    draft = [l for l in _sorted_links(links) if l["adjudication_status"] == "NEEDS_ADJUDICATION"]
    L = [_HTML_BANNER, "",
         "# Paper 3 — per-claim evidence graph", "",
         "One row per registry gate wiring (a gate may split into several claim links). "
         "`evidence_strength` is the **per-gate adjudicated** tier; "
         "`component_evidence_strength` is the component's own declared tier (context only, "
         "never inherited as a verdict). `NEEDS_ADJUDICATION` rows are drafts — their tier is "
         "deliberately blank until a human curates them.", "",
         "**%d links total — %d adjudicated, %d awaiting adjudication.**"
         % (len(links), len(adj), len(draft)), "",
         "## Adjudicated claims", "",
         "| link | stage | gate | tier | independence | observable | claim |",
         "|---|---|---|---|---|---|---|"]
    for l in adj:
        L.append("| `%s` | %s | `%s` | %s | %s | %s | %s |" % (
            l["link_id"], ctx[l["component"]]["stage"], l["gate"],
            l.get("evidence_strength") or "—", l.get("independence") or "—",
            (l.get("observable") or "—").replace("|", "\\|"),
            (l.get("claim") or "—").replace("|", "\\|")))
    L += ["", "## Awaiting adjudication (drafts)", "",
          "| link | stage | gate | component tier (context) |",
          "|---|---|---|---|"]
    for l in draft:
        L.append("| `%s` | %s | `%s` | %s |" % (
            l["link_id"], ctx[l["component"]]["stage"], l["gate"],
            l.get("component_evidence_strength") or "—"))
    L.append("")
    return "\n".join(L) + "\n"


def _queue_md(links, ctx):
    draft = [l for l in _sorted_links(links) if l["adjudication_status"] == "NEEDS_ADJUDICATION"]
    by_comp = {}
    for l in draft:
        by_comp.setdefault(l["component"], []).append(l)
    L = [_HTML_BANNER, "",
         "# Paper 3 evidence-graph — adjudication queue", "",
         "%d gate wiring(s) still need a curated per-claim adjudication. For each, fill "
         "`claim, observable, source_cards, dataset_ids (+ fit/eval role), independence, "
         "evidence_strength, caveat, claim_not_supported` in `EVIDENCE_LINKS.json` and flip "
         "`adjudication_status` to `ADJUDICATED`. The component's declared tier is shown only as "
         "a ceiling to sanity-check against — it is NOT the per-gate verdict." % len(draft), ""]
    for comp in sorted(by_comp):
        L.append("## `%s` — %s (component tier: %s)"
                 % (comp, ctx[comp]["stage"], ctx[comp]["component_evidence_strength"]))
        for l in by_comp[comp]:
            L.append("- [ ] `%s`" % l["gate"])
        L.append("")
    if not draft:
        L.append("_Queue empty — every gate wiring is adjudicated._")
        L.append("")
    return "\n".join(L) + "\n"


def _conflicts_md(links, ctx):
    """G10-centred narrative conflicts report: per-gate conflict notes + the un-reconciled
    published constants (CLAUDE.md rule 6), surfaced rather than silently merged."""
    noted = [l for l in _sorted_links(links) if l.get("conflict_note")]
    L = [_HTML_BANNER, "",
         "# Paper 3 evidence-graph — narrative conflicts report", "",
         "Disagreements the registry deliberately does NOT average away. Each is a surfaced "
         "config field / documented tension, not a merged constant.", "",
         "## Gate-level conflict notes", ""]
    if noted:
        L += ["| link | gate | conflict |", "|---|---|---|"]
        for l in noted:
            L.append("| `%s` | `%s` | %s |" % (
                l["link_id"], l["gate"], l["conflict_note"].replace("|", "\\|")))
    else:
        L.append("_No gate-level conflict notes recorded yet._")
    L += ["", "## Un-reconciled published constants (surfaced, not merged)", ""]
    for cc in CONSTANT_CONFLICTS:
        L.append("### %s" % cc["constant"])
        L.append(cc["note"])
        if cc.get("reference"):
            L.append("")
            L.append("_Authoritative reconciliation: %s._" % cc["reference"])
        L.append("")
        L += ["| value | source(s) |", "|---|---|"]
        for val, cards in sorted(cc["values"].items()):
            L.append("| %s | %s |" % (val, ", ".join("`%s`" % s for s in cards)))
        L.append("")
    return "\n".join(L) + "\n"


def _export_json(links, ctx):
    payload = {"schema_version": SCHEMA_VERSION,
               "GENERATED": _BANNER,
               "n_links": len(links),
               "n_adjudicated": sum(1 for l in links
                                    if l["adjudication_status"] == "ADJUDICATED"),
               "links": _sorted_links(links)}
    payload["content_sha256"] = _sha(json.dumps(payload, sort_keys=True, ensure_ascii=False))
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def generate():
    """Return {relpath: content_str} for every evidence-graph artifact (deterministic)."""
    links = load_links()
    _, ctx = registry_gate_wirings()
    return {
        "evidence_graph_matrix.csv": _matrix_csv(links, ctx),
        "evidence_graph_matrix.md": _matrix_md(links, ctx),
        "evidence_graph.json": _export_json(links, ctx),
        "evidence_adjudication_queue.md": _queue_md(links, ctx),
        "evidence_conflicts.md": _conflicts_md(links, ctx),
    }


def write(root=REPO_ROOT):
    out_dir = Path(root) / GENERATED_REL
    out_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in generate().items():
        (out_dir / rel).write_text(content, encoding="utf-8")
    return sorted(generate())


def verify(root=REPO_ROOT):
    out_dir = Path(root) / GENERATED_REL
    stale = []
    for rel, content in generate().items():
        p = out_dir / rel
        if (not p.exists()) or p.read_text(encoding="utf-8") != content:
            stale.append(rel)
    return stale


def main(argv=None):
    import sys
    argv = sys.argv[1:] if argv is None else argv
    if "--reconcile" in argv:
        problems = reconcile(strict="--strict" in argv)
        if problems:
            print("EVIDENCE GRAPH RECONCILE FAILED (%d):" % len(problems))
            for p in problems:
                print("  -", p)
            return 1
        print("evidence graph reconciles with the live registry%s"
              % (" (strict)" if "--strict" in argv else ""))
        return 0
    if "--bootstrap" in argv:
        print(json.dumps(bootstrap_missing(), indent=2))
        return 0
    if "--verify" in argv:
        s = verify()
        print("stale artifacts:", s or "none")
        return 1 if s else 0
    if "--write" in argv:
        print("wrote:", write())
        return 0
    print(json.dumps({k: len(v) for k, v in generate().items()}, indent=2))
    return 0


if __name__ == "__main__":   # pragma: no cover
    raise SystemExit(main())
