"""Producer-generated Paper 3 registry artifacts (WP2.3).

`generate()` renders the live registry into deterministic Table 1, Appendix A, counts, a
component->dataset->gate matrix, and a machine-readable export. Nothing here embeds a
timestamp or git commit (those belong in the release manifest), so regenerating twice is
byte-identical and CI can fail on a stale/hand-edited artifact.

CLI:  python -m puckworks.paper3.registry_artifacts [--write | --verify]
"""
import csv
import hashlib
import json
from collections import Counter
from pathlib import Path

import puckworks.models  # noqa: F401  (registers all components)
from puckworks import registry as R

SCHEMA_VERSION = 1
REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_REL = "docs/paper3_resource/generated"
_MANIFEST = REPO_ROOT / "puckworks" / "data" / "MANIFEST.csv"

_BANNER = ("<!-- GENERATED by `python -m puckworks.paper3.registry_artifacts` from the live "
           "registry. DO NOT EDIT BY HAND — edits are overwritten and fail CI. -->")


def _sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _components():
    return sorted(R.components(), key=lambda c: (c.stage, c.name))


def _manifest_dataset_ids():
    if not _MANIFEST.exists():
        return set()
    with open(_MANIFEST, newline="", encoding="utf-8-sig") as fh:
        return {row["dataset_id"] for row in csv.DictReader(fh) if row.get("dataset_id")}


def _component_row(c):
    return {
        "id": c.name, "stage": c.stage, "execution_role": c.execution_role,
        "provenance_class": c.provenance_class,
        "evidence_strength": c.evidence_strength or "unclassified",
        "kind_legacy": c.kind, "paper": c.paper, "doi": c.doi, "module": c.module,
        "n_gates": len(c.gates),
    }


def _md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def generate():
    """Return {relpath: content_str} for every Paper 3 registry artifact (deterministic)."""
    comps = _components()
    rows = [_component_row(c) for c in comps]
    arts = {}

    # --- machine-readable export -----------------------------------------------------------
    export = {"schema_version": SCHEMA_VERSION, "n_components": len(rows), "components": rows}
    export["content_sha256"] = _sha(json.dumps(export, sort_keys=True, ensure_ascii=False))
    arts["registry_export.json"] = json.dumps(export, indent=2, sort_keys=True) + "\n"

    # --- counts ----------------------------------------------------------------------------
    counts = {
        "schema_version": SCHEMA_VERSION,
        "n_components": len(rows),
        "by_stage": dict(sorted(Counter(r["stage"] for r in rows).items())),
        "by_execution_role": dict(sorted(Counter(r["execution_role"] for r in rows).items())),
        "by_provenance_class": dict(sorted(Counter(r["provenance_class"] for r in rows).items())),
        "by_evidence_strength": dict(sorted(Counter(r["evidence_strength"] for r in rows).items())),
    }
    counts["content_sha256"] = _sha(json.dumps(counts, sort_keys=True, ensure_ascii=False))
    arts["registry_counts.json"] = json.dumps(counts, indent=2, sort_keys=True) + "\n"

    # --- Table 1: registry overview (stage x execution_role) -------------------------------
    stages = sorted({r["stage"] for r in rows})
    roles = list(R.EXECUTION_ROLES)
    t1_rows = []
    for st in stages:
        cells = [sum(1 for r in rows if r["stage"] == st and r["execution_role"] == role)
                 for role in roles]
        t1_rows.append([st] + cells + [sum(cells)])
    total_row = ["**Total**"] + [sum(1 for r in rows if r["execution_role"] == role)
                                 for role in roles] + [len(rows)]
    t1_rows.append(total_row)
    t1 = [_BANNER, "", "# Table 1 — registry overview (stage × execution role)", "",
          _md_table(["stage"] + roles + ["total"], t1_rows), ""]
    arts["table1_registry_overview.md"] = "\n".join(t1) + "\n"

    # --- Appendix A: full component catalog ------------------------------------------------
    hdr = ["stage", "id", "execution_role", "provenance_class", "evidence_strength",
           "paper", "doi", "n_gates"]
    a_rows = [[r["stage"], "`%s`" % r["id"], r["execution_role"], r["provenance_class"],
               r["evidence_strength"], r["paper"], r["doi"] or "—", r["n_gates"]] for r in rows]
    appendix = [_BANNER, "", "# Appendix A — component catalog (%d components)" % len(rows),
                "", _md_table(hdr, a_rows), ""]
    arts["appendixA_component_catalog.md"] = "\n".join(appendix) + "\n"

    # --- component -> dataset -> gate matrix (CSV) -----------------------------------------
    manifest_ids = _manifest_dataset_ids()
    lines = ["id,stage,execution_role,evidence_strength,n_gates,gate_names"]
    for c in comps:
        gate_names = ";".join(sorted(g.__name__ for g in c.gates))
        lines.append("%s,%s,%s,%s,%d,%s" % (
            c.name, c.stage, c.execution_role, c.evidence_strength or "unclassified",
            len(c.gates), gate_names))
    arts["component_gate_matrix.csv"] = "\n".join(lines) + "\n"

    # --- WP1.3 measurement/source dictionary render (a scientific output) ------------------
    from puckworks.data.visualizer_store import MEASUREMENT_DICTIONARY
    md_items = sorted(MEASUREMENT_DICTIONARY.items())
    dict_body = {"schema_version": SCHEMA_VERSION,
                 "n_channels": len(md_items),
                 "channels": {k: v for k, v in md_items}}
    dict_body["content_sha256"] = _sha(json.dumps(dict_body, sort_keys=True, ensure_ascii=False))
    arts["measurement_dictionary.json"] = json.dumps(dict_body, indent=2, sort_keys=True) + "\n"

    csv_cols = ["channel", "source_field", "quantity_kind", "raw_unit", "canonical_unit",
                "sensor", "commanded", "ambiguity", "eligibility"]
    csv_lines = [",".join(csv_cols)]
    for ch, v in md_items:
        csv_lines.append(",".join(str(v.get(c, "") if c != "channel" else ch)
                                  for c in csv_cols))
    arts["measurement_dictionary.csv"] = "\n".join(csv_lines) + "\n"

    md_hdr = ["channel", "quantity kind", "raw unit", "canonical unit", "commanded/achieved",
              "ambiguity", "eligibility"]
    md_rows = [[ch, v["quantity_kind"], v["raw_unit"], v["canonical_unit"] or "— (native)",
                "commanded" if v["commanded"] else "achieved", v["ambiguity"] or "—",
                v["eligibility"]] for ch, v in md_items]
    dict_md = [_BANNER, "", "# Measurement / source dictionary (P1 first tranche)", "",
               "Channels with `canonical unit = — (native)` are NOT resolved SI quantities and "
               "must not be pooled onto a physical axis (e.g. ambiguous reported flow).", "",
               _md_table(md_hdr, md_rows), ""]
    arts["measurement_dictionary.md"] = "\n".join(dict_md) + "\n"

    return arts


def write(root=REPO_ROOT):
    out_dir = Path(root) / GENERATED_REL
    out_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in generate().items():
        (out_dir / rel).write_text(content, encoding="utf-8")
    return sorted(generate())


def verify(root=REPO_ROOT):
    """Return the list of stale/missing generated artifacts (empty = up to date)."""
    out_dir = Path(root) / GENERATED_REL
    stale = []
    for rel, content in generate().items():
        p = out_dir / rel
        if (not p.exists()) or p.read_text(encoding="utf-8") != content:
            stale.append(rel)
    return stale


if __name__ == "__main__":   # pragma: no cover
    import sys
    if "--verify" in sys.argv:
        s = verify()
        print("stale artifacts:", s or "none")
        sys.exit(1 if s else 0)
    if "--write" in sys.argv:
        print("wrote:", write())
    else:
        print(json.dumps({k: len(v) for k, v in generate().items()}, indent=2))
