"""Render every submission-facing copy of Paper 1's front matter from ONE source.

Third review P0-1. The JFE manuscript and the JFE package described different papers: different
titles (the package still carried the retired "Whole-cup measurements can obscure kinetic parameter
localization..."), different abstracts (313 words vs a stale 237-word one), different keyword lists
and counts, five repository-facing Highlights, and a status line saying that completed analyses
remained outstanding. The review's instruction was explicit -- do NOT repair the copies one at a
time; generate them.

`docs/submission/paper_a_front_matter.yaml` is the source. This script splices it into marked
blocks in the manuscript, the canonical draft, the package and the cover letter, and generates the
Highlights file whole. `tests/test_paper_a_front_matter.py` fails if any rendering drifts.

    python tools/paper_a_front_matter.py                        # report drift, exit 1 if any
    python tools/paper_a_front_matter.py --write                # regenerate every rendering
    python tools/paper_a_front_matter.py --check-submission-ready   # exit 1 while metadata is null
"""
from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE = REPO / "docs" / "submission" / "paper_a_front_matter.yaml"

MANUSCRIPT = REPO / "docs" / "submission" / "PAPER_A_JFE_MANUSCRIPT.md"
DRAFT = REPO / "docs" / "PAPER_A_DRAFT.md"
PACKAGE = REPO / "docs" / "submission" / "PAPER_A_JFE_PACKAGE.md"
HIGHLIGHTS = REPO / "docs" / "submission" / "PAPER_A_JFE_HIGHLIGHTS.txt"
COVER_LETTER = REPO / "docs" / "submission" / "PAPER_A_JFE_COVER_LETTER.md"

STAMP = "<!-- generated by tools/paper_a_front_matter.py — do not edit by hand -->"

# Metadata that must be supplied by an author or an external artefact before submission.
REQUIRED_BEFORE_SUBMISSION = (
    "authors", "affiliations", "corresponding_author", "orcids", "credit_roles",
    "funding", "competing_interests", "generative_ai_declaration",
    "release_doi", "release_commit",
)


def load() -> dict:
    """Parse the single source.

    `yaml` is imported HERE rather than at module scope: pyproject declares pyyaml a radar/dev
    extra ("not a core dep"), and this module is reached transitively from
    `tools/paper_a_consistency.py`, which in turn is exercised by a Paper 3 defect-injection case.
    A module-scope import therefore turned an optional Paper 1 dependency into a hard requirement
    for an unrelated Paper 3 guardrail on the minimum-dependency lane.
    """
    import yaml
    return yaml.safe_load(SOURCE.read_text(encoding="utf-8"))


def _one_line(s: str) -> str:
    return " ".join(str(s).split())


def word_count(s: str) -> int:
    return len(_one_line(s).split())


# ── block splicing ────────────────────────────────────────────────────────────────────────────
def _markers(name: str) -> tuple[str, str]:
    return f"<!-- frontmatter:{name}:begin -->", f"<!-- frontmatter:{name}:end -->"


def splice(text: str, name: str, body: str) -> str:
    """Replace a marked block, or raise if the file has no slot for it."""
    begin, end = _markers(name)
    if begin not in text or end not in text:
        raise KeyError(f"no `{name}` front-matter block in the target file")
    head, rest = text.split(begin, 1)
    _old, tail = rest.split(end, 1)
    return f"{head}{begin}\n{STAMP}\n{body.rstrip()}\n{end}{tail}"


def block(text: str, name: str) -> str:
    begin, end = _markers(name)
    return text.split(begin, 1)[1].split(end, 1)[0].replace(STAMP, "").strip()


# ── renderings ────────────────────────────────────────────────────────────────────────────────
def _placeholder(value, what: str) -> str:
    return _one_line(value) if value else f"[{what} — not yet supplied; see paper_a_front_matter.yaml]"


def _declaration(fm: dict, key: str, heading: str, guidance: str) -> str:
    value = fm.get(key)
    body = _one_line(value) if value else (
        f"*Not yet supplied.* {guidance} Tracked as `{key}` in "
        f"`docs/submission/paper_a_front_matter.yaml`; "
        f"`tools/paper_a_front_matter.py --check-submission-ready` blocks submission until it is "
        f"resolved.")
    return f"### {heading}\n\n{body}"


def declarations_block(fm: dict) -> str:
    """Declarations rendered from the one source, so the unresolved ones are TRACKED rather than
    free-text `[insert ...]` markers scattered through the manuscript (third review P0-7)."""
    return "\n\n".join([
        _declaration(fm, "credit_roles", "CRediT authorship contribution statement",
                     "Assign roles author by author; do not retain roles that were not performed."),
        _declaration(fm, "funding", "Funding",
                     "State the funder and grant number, or the standard no-specific-grant text."),
        _declaration(fm, "competing_interests", "Declaration of competing interest",
                     "State competing interests, or the standard none-declared text."),
        _declaration(fm, "generative_ai_declaration", "Declaration of generative AI in the writing process",
                     "Must match the venue's current Editorial Manager wording and the actual use of tools."),
    ])


def manuscript_blocks(fm: dict) -> dict[str, str]:
    kw = "; ".join(fm["keywords"])
    return {
        "declarations": declarations_block(fm),
        "title": f"# {_one_line(fm['title'])}",
        "runningtitle": f"**Running title:** {_one_line(fm['running_title'])}",
        "authors": "\n\n".join([
            f"**Authors:** {_placeholder(fm['authors'], 'author list')}",
            f"**Affiliations:** {_placeholder(fm['affiliations'], 'affiliations')}",
            f"**Corresponding author:** "
            f"{_placeholder(fm['corresponding_author'], 'corresponding author')}",
        ]),
        "abstract": _one_line(fm["abstract"]),
        "keywords": f"**Keywords:** {kw}",
    }


def package_blocks(fm: dict) -> dict[str, str]:
    n = word_count(fm["abstract"])
    hi = "\n".join(f"- {h} **[{len(h)} characters]**" for h in fm["highlights"])
    return {
        "title": f"**{_one_line(fm['title'])}**\n\n"
                 f"*Running title:* {_one_line(fm['running_title'])}",
        "articletype": _one_line(fm["article_type"]),
        "abstract": f"*{n} words (venue limit "
                    f"{fm['venue']['abstract_word_limit']}).*\n\n{_one_line(fm['abstract'])}",
        "keywords": "; ".join(fm["keywords"]) +
                    f"\n\n*{len(fm['keywords'])} terms (venue limit "
                    f"{fm['venue']['keyword_limit']}).*",
        "highlights": hi,
        "significance": _one_line(fm["editor_significance"]),
    }


def highlights_file(fm: dict) -> str:
    lines = [
        "Paper A — Journal of Food Engineering Highlights",
        "GENERATED by tools/paper_a_front_matter.py from docs/submission/paper_a_front_matter.yaml.",
        "Do not edit by hand.",
        "",
    ]
    lines += [f"• {h}" for h in fm["highlights"]]
    return "\n".join(lines) + "\n"


#: Cover-letter assertions, each with the front-matter field that has to be resolved before the
#: assertion may be made. Fourth review P0-7: the letter stated "all authors have approved the
#: submission" and "we declare no competing interests" while `authors` and `competing_interests`
#: were both null. Those are representations to an editor about real people, and a generator must
#: not make them on the authors' behalf from an empty field.
LETTER_ASSERTIONS = (
    ("authors",
     "all authors have approved the submission",
     "author approval cannot be asserted until the author list is filled in and each author has "
     "actually approved"),
    ("competing_interests",
     "we declare no competing interests beyond those stated in the manuscript",
     "the competing-interest declaration must come from the authors, not from an empty field"),
)


def unsupported_letter_assertions(fm: dict) -> list[tuple[str, str, str]]:
    return [a for a in LETTER_ASSERTIONS if not fm.get(a[0])]


def _letter_declarations(fm: dict) -> str:
    """The letter's declaration paragraph, asserting only what the front matter supports."""
    blocked = unsupported_letter_assertions(fm)
    supported = [text for key, text, _ in LETTER_ASSERTIONS if fm.get(key)]
    para = "This manuscript is original and is not under consideration elsewhere."
    if supported:
        joined = supported[0] if len(supported) == 1 else \
            ", ".join(supported[:-1]) + " and " + supported[-1]
        para = (f"This manuscript is original, is not under consideration elsewhere, and "
                f"{joined}.")
    if not blocked:
        return para
    lines = [para, "",
             "> **This letter is not ready to send.** The following declarations are deliberately "
             "absent rather than asserted, because the front matter does not yet support them:",
             ">"]
    lines += [f"> - *{text}* — {why} (`{key}` is unset in "
              f"`docs/submission/paper_a_front_matter.yaml`)."
              for key, text, why in blocked]
    return "\n".join(lines)


def cover_letter(fm: dict) -> str:
    doi = fm["release_doi"] or "[release DOI — not yet minted]"
    return f"""# Cover letter — {fm['venue']['name']}

{STAMP}
<!-- Regenerate with `python tools/paper_a_front_matter.py --write` after editing
     docs/submission/paper_a_front_matter.yaml. -->

Dear Editors,

We submit for your consideration our manuscript, "{_one_line(fm['title'])}", as a
{_one_line(fm['article_type']).lower()}.

{_one_line(fm['editor_significance'])}

The manuscript's central result is deliberately a cautionary one, and we believe it is the more
useful for that: a mechanistic espresso extraction model recalibrated to whole-cup observations
predicted the complete held-out coarse- and fine-grind corpus (44 records, 132 named-solute
observations) with 8.4 % pooled mean absolute percentage error, against 8.8 % for a trained
level-only comparator — a paired difference of −0.394 percentage points, favouring the mechanistic
model, whose primary clustered percentile sensitivity range contains zero, with the mechanistic
model the worse predictor on 62 of 132 held-out observations. Those dependence-aware ranges are
fixed-predictor sensitivity ranges with no calibrated coverage and no predeclared practical margin,
so we claim neither superiority nor equivalence nor absence of incremental skill; what we report is
that acceptable held-out endpoint accuracy does not by itself establish that the kinetic mechanism
transferred. Time-resolved observations of the same system retained substantially stronger
information about the extraction rate.

All headline values are generated from an archived, machine-readable result bundle, and the
analysis code, environment specification, figure source data and supplementary material are
deposited at {doi}.

{_letter_declarations(fm)}

Yours sincerely,

{_placeholder(fm['corresponding_author'], 'corresponding author')}
on behalf of {_placeholder(fm['authors'], 'the authors')}
"""


def draft_blocks(fm: dict) -> dict[str, str]:
    """The canonical working draft's generated blocks.

    Round-10 P1-1 added the ABSTRACT. The draft used to carry its own, hand-maintained one whose
    central transfer claim had drifted from the venue manuscript's — different vocabulary ("not
    identifiable" versus "weakly separated"), a different headline framing ("an incremental skill of
    only ≈4.5 % relative"), a conclusion the venue abstract does not draw ("adds little beyond the
    transferred level"), and narration of an earlier version of the analysis. CI called the two files
    content-aligned on the strength of a curated phrase list that none of those differences touched.

    Both files now render the abstract from this one source. The draft still carries no Declarations
    section: declarations are a submission artefact, so only the conversion and package render them.
    """
    return {
        "title": f"**Title.** {_one_line(fm['title'])}",
        "abstract": _one_line(fm["abstract"]),
    }


TARGETS = (
    (MANUSCRIPT, manuscript_blocks),
    (DRAFT, draft_blocks),
    (PACKAGE, package_blocks),
)


# ── driver ────────────────────────────────────────────────────────────────────────────────────
def check(fm: dict) -> list[str]:
    """Return a list of drift descriptions; empty means every rendering is current."""
    problems: list[str] = []
    for path, builder in TARGETS:
        text = path.read_text(encoding="utf-8")
        for name, body in builder(fm).items():
            try:
                current = block(text, name)
            except (KeyError, IndexError):
                problems.append(f"{path.name}: missing front-matter block `{name}`")
                continue
            if current != body.strip():
                problems.append(f"{path.name}: `{name}` block is stale")
    if not HIGHLIGHTS.exists() or HIGHLIGHTS.read_text(encoding="utf-8") != highlights_file(fm):
        problems.append(f"{HIGHLIGHTS.name}: stale")
    if not COVER_LETTER.exists() or COVER_LETTER.read_text(encoding="utf-8") != cover_letter(fm):
        problems.append(f"{COVER_LETTER.name}: stale")
    return problems


def write(fm: dict) -> None:
    for path, builder in TARGETS:
        text = path.read_text(encoding="utf-8")
        for name, body in builder(fm).items():
            text = splice(text, name, body)
        path.write_text(text, encoding="utf-8")
        print(f"    wrote front matter into {path.name}")
    HIGHLIGHTS.write_text(highlights_file(fm), encoding="utf-8")
    print(f"    wrote {HIGHLIGHTS.name}")
    COVER_LETTER.write_text(cover_letter(fm), encoding="utf-8")
    print(f"    wrote {COVER_LETTER.name}")


def submission_gaps(fm: dict) -> list[str]:
    gaps = [k for k in REQUIRED_BEFORE_SUBMISSION if not fm.get(k)]
    if (fm.get("novelty_search") or {}).get("status") != "complete":
        gaps.append("novelty_search")
    return gaps


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else list(argv)
    fm = load()

    if "--check-submission-ready" in argv:
        gaps = submission_gaps(fm)
        for g in gaps:
            print(f"    UNRESOLVED: {g}")
        # Reported separately from the field list because these are the ones that would put an
        # unsupported representation in front of an editor, not merely leave a blank (P0-7).
        for key, text, why in unsupported_letter_assertions(fm):
            print(f"    COVER LETTER BLOCKED: cannot assert \"{text}\" — {why} (`{key}`)")
        print(f"{len(gaps)} unresolved submission-metadata field(s)")
        return 1 if gaps else 0

    if "--write" in argv:
        write(fm)
        return 0

    problems = check(fm)
    for p in problems:
        print(f"    DRIFT: {p}")
    print(f"front matter: {len(problems)} drifted rendering(s); "
          f"abstract {word_count(fm['abstract'])} words; "
          f"{len(fm['keywords'])} keywords; {len(fm['highlights'])} highlights")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
