"""Generate Paper 1's supplementary material from the archived machine-readable records.

Third review P0-3: the main text repeatedly said material was "reported in the supplement" while
the submission directory contained only the manuscript, package and Highlights. Every such promise
was a dangling reference.

Fourth review P0-5: the supplement then existed but read as a review ledger rather than a journal
supplement -- review-ticket headings, repository paths, producer function names, adjudication prose
in capitals, non-sequential numbering, and no figures at all. This module now emits TWO documents:

  * ``PAPER_A_JFE_SUPPLEMENT.md`` -- the submitted SI. Sequentially numbered within each item type
    (Methods S1-S2, Note S1, Tables S1-S5, Figures S1-S4), figures physically bundled, and no
    repository paths, producer names, or implementation-status prose.
  * ``PAPER_A_SI_PROVENANCE.md`` -- the reproducibility audit that receives everything stripped out
    of the SI: which producer emitted each table, which archived record it was rendered from, and
    the record's own notes. Not submitted.

Both are GENERATED, for the same reason the bibliography and front matter are: a hand-maintained
supplement drifts from the producers whose numbers it reports.

    python tools/paper_a_supplement.py            # report drift (exit 1 if stale)
    python tools/paper_a_supplement.py --write    # regenerate both documents and bundle figures
"""
from __future__ import annotations

import json
import pathlib
import re
import shutil
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
RESOURCE = REPO / "docs" / "paper1_resource"
SUBMISSION = REPO / "docs" / "submission"
OUT = SUBMISSION / "PAPER_A_JFE_SUPPLEMENT.md"
PROVENANCE = SUBMISSION / "PAPER_A_SI_PROVENANCE.md"
BUNDLE = SUBMISSION / "figures"

FIGURE_SRC = REPO / "docs" / "figures" / "paper_a"
CAPTIONS = REPO / "docs" / "figures" / "PAPER_A_CAPTIONS.md"

OBJECTIVE_JSON = RESOURCE / "PAPER_A_OBJECTIVE_FAMILY_PANELS.json"
EXTERNAL_JSON = RESOURCE / "PAPER_A_EXTERNAL_PANEL_LOSSES.json"
ENDPOINT_JSON = RESOURCE / "PAPER_A_ENDPOINT_PROPAGATION.json"
CORPUS_JSON = RESOURCE / "PAPER_A_TRANSFER_CORPUS_CONTRACTS.json"
LOSS_JSON = RESOURCE / "PAPER_A_COMPARATOR_LOSS_ROBUSTNESS.json"
CONVERGENCE_JSON = RESOURCE / "PAPER_A_NUMERICAL_CONVERGENCE.json"
PANEL_JSON = REPO / "docs" / "figures" / "paper_a" / "results.json"
TABLE7_AUDIT = RESOURCE / "PAPER_A_TABLE7_UNITS_AUDIT.md"

#: The SI is a submitted document, so it carries no repository path (fourth review P0-5); the
#: provenance record, which is not submitted, names the generator explicitly.
SI_STAMP = "<!-- Generated from the archived result records. Do not edit by hand. -->"
STAMP = ("<!-- GENERATED by tools/paper_a_supplement.py from the archived result bundles. "
         "Do not edit by hand. -->")

#: Supplementary figures, in presentation order, mapped to their producer stem. The mapping is the
#: one declared in docs/figures/PAPER_A_CAPTIONS.md; `_check_figure_map` fails if the two disagree,
#: so the SI cannot silently bundle a different image from the one the caption describes.
FIGURES = (("S1", "fig3_holdouts"),
           ("S2", "fig5_joint_residual"),
           ("S3", "fig7_per_group_diagnostics"),
           ("S4", "fig8_residuals_vs_conditions"))


def _load(p: pathlib.Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


# ── Supplementary Methods S1: identifiability definitions and objective construction ───────────
def methods_s1() -> str:
    rec = _load(OBJECTIVE_JSON)
    lo, hi = rec["rate_domain"]
    return f"""### Supplementary Methods S1

**Identifiability definitions and construction of the objective family.**

*Structural* identifiability asks whether parameters are uniquely determined by noise-free,
continuously observed data under a given observation map. It is a property of the model and the
observation map alone, decided analytically, and it is not what this paper measures.

*Practical* identifiability asks whether the parameters are localized by the data actually
available: a finite design, finite noise, a chosen objective and a bounded parameter domain. This
paper evaluates practical localization only. Structural identifiability of the full model under the
relevant observation maps is not assessed, and nothing here should be read as a claim about it in
either direction. Because a practical statement is conditional on all four of those, every such claim
in this paper is scoped to the tested model, observation map, parameter domain and objective, and
the formal term is used only as shorthand for that scoped statement.

The near-optimal sets reported throughout are *declared threshold sets* on a profiled objective,
not confidence regions: no explicit likelihood or noise model is specified, so no calibrated
coverage is claimed. Where a set reaches the boundary of the tested rate domain it is reported as
censored, because its width is then a property of the domain rather than of the data.

The compensation studied here is the two-parameter case of the broader phenomenon of sloppiness, in
which model behaviour depends on a few stiff parameter combinations while remaining nearly
invariant along many sloppy ones. Sloppiness and practical non-identifiability are related but not
equivalent; the profile is reported directly rather than inferring localization from eigenvalue
spectra.

**The objective family.** The rate multiplier is profiled on a {rec['n_rate_grid']}-point geometric
grid spanning {lo}–{hi}. At each candidate rate the solid-inventory level is optimized **for the
objective being profiled**, not once under a common least-squares fit: ordinary least squares for
the sum-of-squares objective, weighted least squares with weights \\(1/y_i^2\\) for relative-L2, and
iteratively reweighted least squares (IRLS) for Huber. Each curve is therefore an objective-specific
profile — a one-dimensional section through that objective's own joint minimum, rather than one
least-squares section rescored under three different outer losses. Each level solve is exact for its
objective (closed-form for the first two, converged IRLS for the third), so no alternating search is
involved. Three objectives are evaluated at every grid point:

1. *Unweighted concentration-scale sum of squares*, the primary objective; level by ordinary least
   squares, \\(c^\\ast = \\sum_i f_i y_i / \\sum_i f_i^2\\).
2. *Relative L2*, which divides each residual by its observation, so every observation contributes
   equally in proportional terms and small concentrations are not down-weighted; level by weighted
   least squares, \\(c^\\ast = \\sum_i w_i f_i y_i / \\sum_i w_i f_i^2\\) with \\(w_i = 1/y_i^2\\).
3. *Huber*, with {rec['huber_delta_rule']}. This limits the influence of large residuals without
   discarding them; level by IRLS, reweighting \\(w_i = \\min(1, \\delta/|r_i|)\\) to convergence.

A near-optimal set at threshold t is the set of profiled grid points whose objective lies within a
factor (1 + t) of the profiled minimum. Thresholds of 2, 5, 10 and 20 % are reported so that the
headline 10 % figure can be seen as one point in a monotone family rather than a chosen cut."""


# ── Supplementary Methods S2: endpoint-proxy and external-trajectory processing ────────────────
def methods_s2() -> str:
    endpoint = _load(ENDPOINT_JSON)
    ext = _load(EXTERNAL_JSON)
    rates = ", ".join(str(r) for r in ext["rates"])
    return f"""### Supplementary Methods S2

**Endpoint and external-trajectory processing.**

*Collection endpoint.* The source campaign reports a beverage **mass** of 40 ± 2 g, and the model
stops at a matched collected mass: the integration terminates at `t_end = M_target / Q`, where `Q`
is the source's flow column. That column is published in mL s⁻¹ but is consumed by the source model
as a mass flow in g s⁻¹, so the stopping rule returns the time at which `M_target` **grams** have
been collected. Density enters the solver when the flow is converted to a superficial velocity and
when the outlet concentration is volume-averaged; it does not convert the stopping rule into a
volume target. Every reported analysis is repeated at 38, 40 and 42 g, which is the campaign's own
declared collection tolerance rather than an invented bracket. The spread across the three endpoints
is a sensitivity analysis over that tolerance; it is not a propagated measurement uncertainty, and
should not be read as an uncertainty interval on any measurement.

One ambiguity is inherited rather than resolved. The source's flow column carries a volumetric label
and a mass consumption, and the two cannot both be right. The source's arithmetic is preserved
because every frozen parameter used here was estimated under it; if instead the published label is
correct, the realised cup is about 2 % smaller than stated, which lies inside the ±2 g window swept
above.

Two distinct estimands are reported at the three endpoints, and they are kept apart deliberately.
The first is the blind discrepancy of the source model at the optimal grind, which measures how far
an uncalibrated prediction sits from the measurement. The second is the complete transfer benchmark
of Supplementary Table S3: fit inventory and rate on the nine optimal-grind conditions at the
endpoint, freeze the calibration, predict every held-out coarse and fine observation at the same
endpoint, refit the level-only comparator at the same endpoint, and repeat the paired clustered
resampling. An endpoint-induced shift common to both predictors cancels in the model-minus-comparator
contrast even when it materially moves the blind residual, so a single reported sensitivity would
be misleading for one estimand or the other.

Estimand of the transfer benchmark: {endpoint['estimand']}

*External trajectory.* The external dissolved-solids series is a time-resolved trajectory measured
on different equipment from the primary campaign, at {ext['T_C']} °C and {ext['pressure_bar']} bar.
It is used as a shape stress test, not as rate validation. Three processing choices are each swept
because none is determined by the published record: the time offset between the machine's start
signal and the first collected fraction; whether the first fraction is retained or dropped, since
it is the one most affected by that offset; and the loss used to score the fit. Rates swept:
{rates}.

Two losses are reported because they weight the trajectory differently. *Profiled MAPE* weights
every fraction by the reciprocal of its observation, so the small early dissolved-solids bins
dominate it. *nRMSE* is the root-mean-square residual after a least-squares level, expressed as a
percentage of the mean observation, so bins are weighted by absolute residual instead. The full
sensitivity is Supplementary Table S4."""


# ── Supplementary Note S1: the dimensional audit of the inventory constraint ───────────────────
def note_s1() -> str:
    """The scientific content of the Table 7 audit, without the repository history.

    The archived audit doubles as a change record -- it carries a review ticket in its title, a
    "Recommendation (implemented in this PR)" section and an "owed; out of scope here" section.
    Reproducing it verbatim put all of that in the submitted SI (fourth review P0-5). The numbers
    are still read from the archived document rather than retyped, so the note cannot drift from
    it; only the sections that are repository bookkeeping are dropped.
    """
    body = TABLE7_AUDIT.read_text(encoding="utf-8")
    keep = ("The two quantities being equated", "The conversion, from first principles",
            "Basis-sensitivity of the caffeine Table 7 value", "Why the numeric rate is not secure",
            "What survives (the qualitative claim)")
    sections = re.split(r"(?m)^## ", body)
    picked = []
    for sec in sections[1:]:
        title = sec.splitlines()[0].strip()
        if title in keep:
            # Demote one level so the audit's sections nest under the note, and strip the
            # repository paths that identify where each number is stored.
            text = "#### " + sec.rstrip()
            text = re.sub(r"\s*\(`[^`]*\.(?:md|py)`(?:\s+L\d+)?\)", "", text)
            text = re.sub(r"The analysis code[^\n]*\n[^\n]*\n", "The reported intersection ", text)
            picked.append(text)
    missing = [k for k in keep if f"\n## {k}" not in body and not body.startswith(f"## {k}")]
    if missing:
        raise SystemExit(f"Table 7 audit is missing expected sections: {missing}")

    return ("""### Supplementary Note S1

**Dimensional audit of the orthogonal same-campaign inventory assay.**

This is the audit the main text refers to when it states that the assay and the model's fitted
inventory are not demonstrably commensurate. The intersection of the measured dry-coffee assay with
the profiled inventory curve equates two quantities in mg mL⁻¹ whose physical volume bases are not
shown to match, and the assay's basis alone is ambiguous by roughly a factor of three — far larger
than the ±10 % perturbation that was propagated. The valley passing near an independently measured
inventory of the same order of magnitude is a real and useful *qualitative* result; the specific
implied rate is not a secure quantitative constraint.

"""
            + "\n\n".join(picked))


# ── Supplementary Table S1: fitted parameters and boundary flags ───────────────────────────────
def table_s1() -> str:
    obj = _load(OBJECTIVE_JSON)
    panels = _load(PANEL_JSON)
    n = obj["n_rate_grid"]
    lo, hi = obj["rate_domain"]

    rows = []
    for panel, pd in obj["panels"].items():
        variety, solute = panel.split(":")
        res = pd["objective_family"]["sse"]
        s = res["sets"]["10pct"]
        flags = [w for w, on in (("lower", s["lower_censored"]), ("upper", s["upper_censored"]))
                 if on]
        rows.append(
            f"| {variety} | {solute} | {pd['n_conditions']} | {res['rate_at_min']:.3f} | "
            f"{'yes' if res['at_boundary'] else 'no'} | {s['rate_lo']:.3f}–{s['rate_hi']:.3f} | "
            f"{', '.join(flags) if flags else 'none'} |")

    curv = []
    for key, p in sorted(panels.items()):
        if not key.startswith("panel_"):
            continue
        ev = p["hessian_eigenvalues"]
        d = p["sloppy_direction_lnrate_lncs0"]
        curv.append(
            f"| {p['variety']} | {p['solute']} | {p['rate_star']:.3f} | {p['c_s0_star']:.3f} | "
            f"{p['condition_number']:.3g} | {ev[0]:.3g}, {ev[1]:.3g} | "
            f"({d[0]:+.3f}, {d[1]:+.3f}) | {p['local_curvature_coupling']:+.3f} |")

    return f"""### Supplementary Table S1

**Fitted parameters and boundary flags for every solute × variety panel.**

The rate multiplier is profiled over {lo}–{hi} on a {n}-point geometric grid under the primary
unweighted sum-of-squares objective; the solid-inventory level at each rate is the ordinary
least-squares minimizer for that objective (the other two objectives use their own level solvers —
see Supplementary Methods S1). "Minimum on boundary" flags a panel whose profiled optimum sits at an edge
of the tested domain, in which case the point estimate is a property of the domain. The 10 %
near-optimal range is likewise censored where it reaches an edge.

| variety | solute | conditions | rate at minimum | minimum on boundary | 10 % near-optimal range | range censored |
|---|---|---:|---:|---|---|---|
{chr(10).join(rows)}

**Local curvature at the joint optimum.** Computed for the two panels shown in main-text Figure 2,
on natural-log parameters, by central finite differences. The sloppy direction is the unit
eigenvector of the smallest eigenvalue, in (ln rate, ln inventory) coordinates; a direction near
the antidiagonal is the inventory–rate compensation seen directly.

| variety | solute | rate at optimum | inventory level (mg mL⁻¹) | condition number | Hessian eigenvalues | sloppy direction | curvature coupling |
|---|---|---:|---:|---:|---|---|---:|
{chr(10).join(curv)}
"""


# ── Supplementary Table S2: the full objective × threshold family ──────────────────────────────
def table_s2() -> str:
    rec = _load(OBJECTIVE_JSON)
    n = rec["n_rate_grid"]
    lo, hi = rec["rate_domain"]
    rows = []
    for panel, pd in rec["panels"].items():
        variety, solute = panel.split(":")
        for obj in rec["objectives"]:
            res = pd["objective_family"][obj]
            for thr in ("2pct", "5pct", "10pct", "20pct"):
                s = res["sets"][thr]
                k = round(s["frac_within"] * n)
                flags = []
                if s["lower_censored"]:
                    flags.append("lower")
                if s["upper_censored"]:
                    flags.append("upper")
                rows.append(
                    f"| {variety} | {solute} | {obj} | {thr.replace('pct', ' %')} | "
                    f"{k}/{n} | {s['frac_within']:.3f} | {s['rate_lo']:.3f} | {s['rate_hi']:.3f} | "
                    f"{s['log_width']:.3f} | {res['rate_at_min']:.3f} | "
                    f"{'yes' if res['at_boundary'] else 'no'} | "
                    f"{', '.join(flags) if flags else 'none'} |")

    interior = sum(1 for pd in rec["panels"].values() for obj in rec["objectives"]
                   if not pd["objective_family"][obj]["at_boundary"])
    censored = sum(1 for pd in rec["panels"].values() for obj in rec["objectives"]
                   if pd["objective_family"][obj]["sets"]["10pct"]["lower_censored"]
                   or pd["objective_family"][obj]["sets"]["10pct"]["upper_censored"])
    total = len(rec["panels"]) * len(rec["objectives"])

    return f"""### Supplementary Table S2

**The complete objective and threshold family: all six solute × variety panels, three objective
families, four near-optimal thresholds.**

Rate domain {lo}–{hi} on a {n}-point geometric grid. The count `k/{n}` is the number of tested rate
points inside the near-optimal set; the denominator is printed so the fraction cannot be read
without it. Censoring flags record whether the set reaches the tested lower or upper boundary, in
which case its width is a property of the tested domain rather than of the data. Objective
construction is Supplementary Methods S1.

| variety | solute | objective | threshold | points in set | fraction | rate low | rate high | log width | rate at minimum | minimum on boundary | set censored |
|---|---|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**Reading.** The objective minimum is interior in {interior} of {total} panel × objective cells, so
the interior minimum of the illustrative Arabica-caffeine panel is *not* a universal feature. The
10 % near-optimal set reaches a tested boundary in {censored} of {total} cells. The breadth of the
near-optimal set is therefore robust to the objective, while the location of the point minimum is
not.
"""


def _wrapped(name: str, body: str) -> str:
    """Emit a delegated transfer block inside its markers.

    The markers are the contract `tests/test_paper_a_model_contract.py` binds against: they let a
    test assert that the primary interval and the corpus stamp appear in the *intended semantic
    block* rather than anywhere in a 500-line file, which is the round-8 P1-3 defect.
    """
    return f"<!-- {name}:begin -->\n{body}\n<!-- {name}:end -->"


def _transfer_text():
    """Import the transfer-block generator regardless of how this module was loaded.

    The tests import `tools/paper_a_supplement.py` by path, so `tools/` is not guaranteed to be
    on `sys.path`; a bare `import paper_a_transfer_text` works from the CLI and fails under
    pytest, which is exactly the kind of lane-dependent breakage this file exists to prevent.
    """
    import importlib
    import sys as _sys

    here = str(pathlib.Path(__file__).resolve().parent)
    if here not in _sys.path:
        _sys.path.insert(0, here)
    return importlib.import_module("paper_a_transfer_text")


# ── Supplementary Table S3: endpoint propagation ───────────────────────────────────────────────
def table_s3() -> str:
    """Round-7 P1-6: main table, SI table and reading are rendered from ONE canonical record at
    ONE precision. The reading is COMPOSED from the archived numbers rather than stored as prose
    beside them, so it cannot drift from the table it reads.

    Round-8: the per-endpoint sweep and its reading now come from
    `tools.paper_a_transfer_text`, the single owner of every transfer-derived publication block,
    so the SI table, the main-text table and the caption cannot render the same result three
    different ways. Only the per-group breakdown, which is SI-only, is composed here.
    """
    TT = _transfer_text()

    rec = _load(ENDPOINT_JSON)
    sweep = _wrapped("paper-a:transfer-endpoint-table-supp",
                     TT.block_supplement_endpoint_table(rec, _load(CORPUS_JSON),
                                                        _load(LOSS_JSON)))

    per_group = []
    for r in rec["rows"]:
        for g, v in sorted(r["per_fit"].items()):
            per_group.append(
                f"| {r['m_target_g']:.0f} g | {g} | {v['model_macro_mape']:.2f} | "
                f"{v['const_macro_mape']:.2f} | "
                f"{v['model_macro_mape'] - v['const_macro_mape']:+.2f} |")

    const_mapes = {round(r["pooled_const_mape"], 2) for r in rec["rows"]}
    note_on_comparator = (
        f"The level-only comparator's pooled MAPE is {sorted(const_mapes)[0]:.2f} % at "
        + ("ALL THREE endpoints" if len(const_mapes) == 1 else "each endpoint") +
        ", and that is a correctness check rather than a coincidence: the comparator is fitted to "
        "MEASURED concentrations, which do not depend on where the solver terminates. Only the "
        "mechanistic predictor moves with the endpoint. If the comparator had moved too, the "
        "pipeline would not be doing what this analysis claims.")

    return f"""### Supplementary Table S3

**Endpoint propagation: the complete transfer-versus-comparator benchmark at 38, 40 and 42 g.**

For each endpoint the whole procedure is repeated — fit inventory and rate on the nine
optimal-grind conditions at that endpoint, freeze the calibration, predict all held-out coarse and
fine observations at the same endpoint, refit the optimal-grind-trained level-only comparator at the
same endpoint, and repeat the clustered resampling of the paired loss under every declared scheme.
Processing is described in Supplementary Methods S2.

{sweep}

**Per group.** Macro MAPE for each variety × solute group at each endpoint.

| endpoint | group | model macro MAPE (%) | comparator macro MAPE (%) | difference (pp) |
|---|---|---:|---:|---:|
{chr(10).join(per_group)}

{note_on_comparator}

**Not the same quantity as the blind-residual sweep.** {rec['note']}
"""


# ── Supplementary Table S4: the external panel under both losses ───────────────────────────────
def table_s4() -> str:
    rec = _load(EXTERNAL_JSON)
    rows = []
    for case, d in rec["per_case"].items():
        rows.append(
            f"| {case} | {d['time_offset_s']:.0f} | "
            f"{'included' if d['first_bin_included'] else 'dropped'} | "
            f"{d['fraction_min_mape']:.2f} | {d['fraction_best_rate']} | "
            f"{d['fraction_range_ratio']:.2f} | "
            f"{d['fraction_min_nrmse']:.2f} | {d['fraction_best_rate_nrmse']} | "
            f"{d['fraction_range_ratio_nrmse']:.2f} | "
            f"{d['cup_range_ratio']:.2f} |")
    return f"""### Supplementary Table S4

**External dissolved-solids trajectory under both losses, for every time-alignment and first-bin
choice.**

Conditions and loss definitions are given in Supplementary Methods S2.

| case | time offset (s) | first bin | min MAPE (%) | best rate (MAPE) | range ratio (MAPE) | min nRMSE (%) | best rate (nRMSE) | range ratio (nRMSE) | cup range ratio |
|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**Reading.** {rec['finding']}

The cup range ratio is 1.00 in every case. That is algebraic, not empirical: with one integrated
scalar and one free multiplicative level, the model matches the scalar exactly at every rate.
"""


# ── Supplementary Table S5: PDE discretisation and solver-tolerance convergence ────────────────
def table_s5() -> str:
    rec = _load(CONVERGENCE_JSON)
    rows = []
    for _k, v in rec["cells"].items():
        rows.append(
            f"| {v['n_axial_nodes']} | {v['solver_tolerance']:.0e} | {v['whole_cup']:.5f} | "
            f"{v['early']:.5f} | {v['middle']:.5f} | {v['late']:.5f} | {v['rate_at_min']:.3f} | "
            f"{v['range_ratio']:.4f} | {v['rel_dev_whole_cup_pct']:.4f} | "
            f"{v['rel_dev_late_pct']:.4f} | {v['rel_dev_range_ratio_pct']:.4f} |")
    w = rec["worst_case_rel_dev_pct"]
    return f"""### Supplementary Table S5

**Convergence of the spatial discretisation and the integration tolerance.**

This is convergence of the **spatial discretisation and integration tolerance**, which is a
different quantity from the rate-parameter-grid convergence reported in the main text. It is
included because the paper's temporal-information result depends on the shape of the outlet
trajectory, so the numerics producing that shape are load-bearing.

Numerical scheme: {rec['scheme']}.

Panel: {rec['panel']}, granulometry {rec['granulometry']}, {rec['n_conditions']} conditions.
Deviations are measured against the finest cell tested. **Scope of this table:**
{rec['reading_scope']}. Nothing outside that scope is certified by it.

| axial nodes | rel/abs tolerance | whole cup | early | middle | late | rate at minimum | range ratio | dev. cup (%) | dev. late (%) | dev. range ratio (%) |
|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
{chr(10).join(rows)}

Concentrations are in mg mL⁻¹ on the model's internal basis; deviations are relative to the finest
cell.

**Reading.** {rec['reading']}

Worst-case relative deviation across all nine cells: whole cup {w['whole_cup']:.4f} %, late
fraction {w['late_fraction']:.4f} %, profile range ratio {w['range_ratio']:.4f} %. The profiled
minimum location is identical in every cell.

**Solver diagnostics.** {rec['solver_warnings']}
"""


# ── Supplementary Figures S1–S4 ────────────────────────────────────────────────────────────────
def _caption_map() -> dict[str, tuple[str, str]]:
    """{number: (producer stem, caption paragraph)} parsed from the caption document."""
    text = CAPTIONS.read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r"(?m)^### Figure (S\d+) \(`([^`]+)`\)\s*\n+(\*\*Figure S\d+\..*?)(?=\n###|\Z)",
                         text, re.S):
        out[m.group(1)] = (m.group(2), " ".join(m.group(3).split()))
    return out


def _check_figure_map(caps: dict[str, tuple[str, str]]) -> None:
    for number, stem in FIGURES:
        if number not in caps:
            raise SystemExit(f"caption document defines no Figure {number}")
        if caps[number][0] != stem:
            raise SystemExit(
                f"Figure {number} bundles `{stem}` but the caption document assigns it "
                f"`{caps[number][0]}` — the SI would show a different image from the one described")
    extra = sorted(set(caps) - {n for n, _ in FIGURES})
    if extra:
        raise SystemExit(f"caption document defines supplementary figures the SI omits: {extra}")


def figures() -> str:
    caps = _caption_map()
    _check_figure_map(caps)
    parts = []
    for number, stem in FIGURES:
        _, caption = caps[number]
        parts.append(f"""### Supplementary Figure {number}

![Supplementary Figure {number}](figures/{stem}.png)

{caption}""")
    return "\n\n---\n\n".join(parts)


def bundle_figures() -> list[str]:
    """Copy the rendered supplementary figures next to the SI so the bundle is self-contained."""
    BUNDLE.mkdir(parents=True, exist_ok=True)
    written = []
    for _number, stem in FIGURES:
        for ext in ("png", "pdf"):
            src = FIGURE_SRC / f"{stem}.{ext}"
            if not src.exists():
                raise SystemExit(f"supplementary figure not rendered: {src.relative_to(REPO)}")
            shutil.copyfile(src, BUNDLE / src.name)
            written.append(src.name)
    return written


def missing_figures() -> list[str]:
    return [f"{stem}.{ext}" for _n, stem in FIGURES for ext in ("png", "pdf")
            if not (BUNDLE / f"{stem}.{ext}").exists()]


# ── Supplementary Tables S6 and S7: the resampling design and the corpus it partitions ────────
def table_s6() -> str:
    """Round-8 P0-2/P1-1: the exact resampling design, so a reader can reconstruct every cluster.

    Round 8 found the general Methods naming a superseded primary unit. Prose and table are now
    rendered from the same archived design object, so they cannot disagree with each other or
    with the producer.
    """
    TT = _transfer_text()
    body = _wrapped("paper-a:transfer-scheme-table",
                    TT.block_supplement_scheme_table(_load(ENDPOINT_JSON), _load(CORPUS_JSON),
                                                     _load(LOSS_JSON)))
    return f"""### Supplementary Table S6

{body}
"""


def table_s7() -> str:
    """Round-8 P1-4: the held-out corpus published as a table, not only as a hash.

    A reviewer should not have to reverse-engineer corpus membership from the source CSV, and a
    count alone cannot distinguish the complete corpus from a different set of the same size.
    """
    TT = _transfer_text()
    body = _wrapped("paper-a:transfer-corpus-manifest",
                    TT.block_supplement_corpus_manifest(_load(ENDPOINT_JSON), _load(CORPUS_JSON),
                                                        _load(LOSS_JSON)))
    return f"""### Supplementary Table S7

{body}
"""


def build() -> str:
    parts = [
        "# Supplementary material",
        "",
        SI_STAMP,
        "",
        "**Separating Extractable Content from Extraction Rate in Espresso Models: Limits of "
        "Whole-Cup Measurements and the Value of Time-Resolved Data**",
        "",
        "Every item here is cited by the main text. Items are numbered sequentially within each "
        "type: Supplementary Methods S1–S2, Supplementary Note S1, Supplementary Tables S1–S7 and "
        "Supplementary Figures S1–S4.",
        "",
        "---",
        "",
        methods_s1(), "", "---", "",
        methods_s2(), "", "---", "",
        note_s1(), "", "---", "",
        table_s1(), "", "---", "",
        table_s2(), "", "---", "",
        table_s3(), "", "---", "",
        table_s4(), "", "---", "",
        table_s5(), "", "---", "",
        table_s6(), "", "---", "",
        table_s7(), "", "---", "",
        figures(),
    ]
    return "\n".join(parts).rstrip() + "\n"


# ── the provenance record: everything the journal SI must not carry ────────────────────────────
def build_provenance() -> str:
    rows = []
    for item, record, producer in (
        ("Methods S1", OBJECTIVE_JSON, None),
        ("Methods S2", ENDPOINT_JSON, None),
        ("Note S1", TABLE7_AUDIT, None),
        ("Table S1", OBJECTIVE_JSON, "objective_family"),
        ("Table S1 (curvature)", PANEL_JSON, None),
        ("Table S2", OBJECTIVE_JSON, "objective_family"),
        ("Table S3", ENDPOINT_JSON, None),
        ("Table S4", EXTERNAL_JSON, None),
        ("Table S5", CONVERGENCE_JSON, None),
    ):
        rec = _load(record) if record.suffix == ".json" else {}
        prod = rec.get("producer", "—")
        field = producer or rec.get("producer_field", "")
        rows.append(f"| {item} | `{record.relative_to(REPO)}` | `{prod}` | "
                    f"{'`' + field + '`' if field else '—'} |")

    fig_rows = [f"| Supplementary Figure {n} | `{(FIGURE_SRC / (stem + '.png')).relative_to(REPO)}` "
                f"| `{stem}` |" for n, stem in FIGURES]

    conv = _load(CONVERGENCE_JSON)
    obj = _load(OBJECTIVE_JSON)
    panels = _load(PANEL_JSON)

    return f"""# Paper A — supplementary-material provenance

{STAMP}

**Not part of the submission.** This record holds the repository detail that the fourth review
required be removed from the journal SI (P0-5): which producer emitted each supplementary item,
which archived record it was rendered from, and the record's own internal notes. The SI itself is
`PAPER_A_JFE_SUPPLEMENT.md`; both are generated by `tools/paper_a_supplement.py`, so this table
cannot drift from what was actually rendered.

## Item → record → producer

| supplementary item | archived record | producer | field |
|---|---|---|---|
{chr(10).join(rows)}

## Figures

Rendered images are copied into `docs/submission/figures/` (PNG for the Markdown SI, PDF for
typesetting) by `tools/paper_a_supplement.py --write`. The number → producer assignment is pinned
in `FIGURES` and cross-checked against `docs/figures/PAPER_A_CAPTIONS.md`; a mismatch is a hard
error, so the SI cannot bundle a different image from the one its caption describes.

| supplementary item | rendered source | producer stem |
|---|---|---|
{chr(10).join(fig_rows)}

## Record notes carried by the producers

**Objective family.** {obj['note']}

**Numerical convergence.** Reference cell `{conv['reference_cell']}`; production configuration
`{conv['production_cell']}`; producer `{conv['producer']}`.

**Curvature panels.** `{PANEL_JSON.relative_to(REPO)}` schema version
{panels['schema_version']}, source commit `{panels['source_commit']}`.

## Analyses cited in the audit trail but not in the SI

The dimensional audit `{TABLE7_AUDIT.relative_to(REPO)}` also records the manuscript demotion it
prompted, the guard phrase locking that demotion, and what a future quantitative version of the
constraint would require. Those are repository history and future work; Supplementary Note S1
reproduces only the audit's scientific content.
"""


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else list(argv)
    fresh, prov = build(), build_provenance()
    if "--write" in argv:
        OUT.write_text(fresh, encoding="utf-8")
        PROVENANCE.write_text(prov, encoding="utf-8")
        n = len(bundle_figures())
        print(f"wrote {OUT.relative_to(REPO)}")
        print(f"wrote {PROVENANCE.relative_to(REPO)}")
        print(f"bundled {n} supplementary figure files into {BUNDLE.relative_to(REPO)}")
        return 0
    rc = 0
    for path, text in ((OUT, fresh), (PROVENANCE, prov)):
        if not path.exists():
            print(f"MISSING: {path.relative_to(REPO)} — run with --write")
            rc = 1
        elif path.read_text(encoding="utf-8") != text:
            print(f"STALE: {path.relative_to(REPO)} — run with --write")
            rc = 1
    if gone := missing_figures():
        print(f"MISSING FIGURES in {BUNDLE.relative_to(REPO)}: {', '.join(gone)} — run with --write")
        rc = 1
    if rc == 0:
        print("supplement, provenance record and figure bundle are current")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
