"""Generate Paper 1's supplementary material from the archived machine-readable records.

Third review P0-3: the main text repeatedly said material was "reported in the supplement" --
the extended identifiability discussion, the full objective and threshold family, the Table 7
dimensional audit, the external-panel loss comparison -- while the submission directory contained
only the manuscript, package and Highlights. Every such promise was a dangling reference.

The supplement is GENERATED, for the same reason the bibliography and front matter are: a
hand-maintained supplement drifts from the producers whose numbers it reports. Tables come from
the archived JSON bundles; notes come from the archived audit documents.

Items the main text cites but whose analysis has NOT been run are emitted as explicit
NOT-YET-AVAILABLE stubs rather than omitted or invented. `tools/paper_a_consistency.py` fails while
any cited item is missing, and the stub says exactly what must be run to fill it.

    python tools/paper_a_supplement.py            # report drift (exit 1 if stale)
    python tools/paper_a_supplement.py --write    # regenerate
"""
from __future__ import annotations

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
RESOURCE = REPO / "docs" / "paper1_resource"
OUT = REPO / "docs" / "submission" / "PAPER_A_JFE_SUPPLEMENT.md"

OBJECTIVE_JSON = RESOURCE / "PAPER_A_OBJECTIVE_FAMILY_PANELS.json"
EXTERNAL_JSON = RESOURCE / "PAPER_A_EXTERNAL_PANEL_LOSSES.json"
ENDPOINT_JSON = RESOURCE / "PAPER_A_ENDPOINT_PROPAGATION.json"
CONVERGENCE_JSON = RESOURCE / "PAPER_A_NUMERICAL_CONVERGENCE.json"
TABLE7_AUDIT = RESOURCE / "PAPER_A_TABLE7_UNITS_AUDIT.md"

STAMP = ("<!-- GENERATED by tools/paper_a_supplement.py from the archived result bundles. "
         "Do not edit by hand. -->")


def _load(p: pathlib.Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


# ── Table S1: the full objective x threshold family, all six panels ───────────────────────────
def table_s1() -> str:
    rec = _load(OBJECTIVE_JSON)
    n = rec["n_rate_grid"]
    lo, hi = rec["rate_domain"]
    rows = []
    for panel, pd in rec["panels"].items():
        variety, solute = panel.split(":")
        for obj in rec["objectives"]:
            res = pd["objective_family"][obj]
            for thr in ("2pct", "5pct", "10pct", "20pct"):
                s = res["sets"][thr]
                k = round(s["frac_within"] * n)
                flags = []
                if s["lower_censored"]:
                    flags.append("lower")
                if s["upper_censored"]:
                    flags.append("upper")
                rows.append(
                    f"| {variety} | {solute} | {obj} | {thr.replace('pct', ' %')} | "
                    f"{k}/{n} | {s['frac_within']:.3f} | {s['rate_lo']:.3f} | {s['rate_hi']:.3f} | "
                    f"{s['log_width']:.3f} | {res['rate_at_min']:.3f} | "
                    f"{'yes' if res['at_boundary'] else 'no'} | "
                    f"{', '.join(flags) if flags else 'none'} |")

    interior = sum(1 for pd in rec["panels"].values() for obj in rec["objectives"]
                   if not pd["objective_family"][obj]["at_boundary"])
    censored = sum(1 for pd in rec["panels"].values() for obj in rec["objectives"]
                   if pd["objective_family"][obj]["sets"]["10pct"]["lower_censored"]
                   or pd["objective_family"][obj]["sets"]["10pct"]["upper_censored"])
    total = len(rec["panels"]) * len(rec["objectives"])

    return f"""### Supplementary Table S1

**The complete objective and threshold family: all six solute x variety panels, three objective
families, four near-optimal thresholds.**

Rate domain {lo}–{hi} on a {n}-point geometric grid. `k/{n}` is the number of tested rate points
inside the near-optimal set; the denominator is printed so the fraction cannot be read without it.
Censoring flags record whether the set reaches the tested lower or upper boundary, in which case
its width is a property of the tested domain rather than of the data.

Producer: `{rec['producer']}` (field `{rec['producer_field']}`).
Huber tuning: {rec['huber_delta_rule']}.

| variety | solute | objective | threshold | points in set | fraction | rate low | rate high | log width | rate at minimum | minimum on boundary | set censored |
|---|---|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**Reading.** The objective minimum is interior in {interior} of {total} panel x objective cells, so
the interior minimum of the illustrative Arabica-caffeine panel is *not* a universal feature. The
10 % near-optimal set reaches a tested boundary in {censored} of {total} cells. The breadth of the
near-optimal set is therefore robust to the objective, while the location of the point minimum is
not.
"""


# ── Table S3: endpoint propagation through the full benchmark ─────────────────────────────────
def table_s3() -> str:
    rec = _load(ENDPOINT_JSON)
    rows = []
    for r in rec["rows"]:
        lo, hi = r["clustered_range_within_group"]
        glo, ghi = r["clustered_range_whole_group"]
        rows.append(
            f"| {r['v_target_ml']:.0f} mL | {r['pooled_model_mape']:.2f} | "
            f"{r['pooled_const_mape']:.2f} | {r['paired_difference_pp']:+.3f} | "
            f"[{lo:+.2f}, {hi:+.2f}] | {'excludes 0' if not (lo <= 0 <= hi) else 'includes 0'} | "
            f"[{glo:+.2f}, {ghi:+.2f}] | {r['n_model_worse_than_const']} of {r['n_points']} | "
            f"{r['skill_vs_const']:.3f} |")
    per_group = []
    for r in rec["rows"]:
        for g, v in sorted(r["per_fit"].items()):
            per_group.append(
                f"| {r['v_target_ml']:.0f} mL | {g} | {v['model_macro_mape']:.2f} | "
                f"{v['const_macro_mape']:.2f} | "
                f"{v['model_macro_mape'] - v['const_macro_mape']:+.2f} |")

    return f"""### Supplementary Table S3

**Endpoint propagation: the complete transfer-versus-null benchmark at 38, 40 and 42 mL.**

For each endpoint proxy the whole procedure is repeated — fit inventory and rate on the nine
optimal-grind conditions at that endpoint, freeze the calibration, predict all held-out coarse and
fine observations at the same endpoint, refit the optimal-grind-trained level-only constant at the
same endpoint, and repeat the primary clustered resampling of the paired loss.

Estimand: {rec['estimand']}

| endpoint | model pooled MAPE (%) | level-only null (%) | paired difference (pp) | primary range, conditions within group (pp) | | secondary range, whole groups (pp) | model worse on | skill vs null |
|---|---:|---:|---:|---:|---|---:|---:|---:|
{chr(10).join(rows)}

**Per group.** Macro MAPE for each variety × solute group at each endpoint.

| endpoint | group | model macro MAPE (%) | null macro MAPE (%) | difference (pp) |
|---|---|---:|---:|---:|
{chr(10).join(per_group)}

**Reading.** {rec['reading']}

{rec['note_on_the_null']}

**Not the same quantity as the blind-residual sweep.** {rec['note']}
"""


# ── Table S5: the external panel under both losses ────────────────────────────────────────────
def table_s5() -> str:
    rec = _load(EXTERNAL_JSON)
    rates = rec["rates"]
    rows = []
    for case, d in rec["per_case"].items():
        rows.append(
            f"| {case} | {d['time_offset_s']:.0f} | "
            f"{'included' if d['first_bin_included'] else 'dropped'} | "
            f"{d['fraction_min_mape']:.2f} | {d['fraction_best_rate']} | "
            f"{d['fraction_range_ratio']:.2f} | "
            f"{d['fraction_min_nrmse']:.2f} | {d['fraction_best_rate_nrmse']} | "
            f"{d['fraction_range_ratio_nrmse']:.2f} | "
            f"{d['cup_range_ratio']:.2f} |")
    return f"""### Supplementary Table S5

**External dissolved-solids panel under both losses, for every time-alignment and first-bin
choice.**

Swept rates: {', '.join(str(r) for r in rates)}. Conditions: {rec['T_C']} °C, {rec['pressure_bar']} bar.

Two losses are reported because they weight the trajectory differently. **Profiled MAPE** weights
every fraction by 1/y, so the small early dissolved-solids bins dominate it. **nRMSE** is the
root-mean-square residual after a least-squares level, expressed as a percentage of the mean
observation, so bins are weighted by absolute residual instead.

Producer: `{rec['producer']}`.

| case | time offset (s) | first bin | min MAPE (%) | best rate (MAPE) | range ratio (MAPE) | min nRMSE (%) | best rate (nRMSE) | range ratio (nRMSE) | cup range ratio |
|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**Reading.** {rec['finding']}

The cup range ratio is 1.00 in every case. That is algebraic, not empirical: with one integrated
scalar and one free multiplicative level, the model matches the scalar exactly at every rate.
"""


# ── Note S2: the Table 7 dimensional audit ────────────────────────────────────────────────────
def note_s2() -> str:
    body = TABLE7_AUDIT.read_text(encoding="utf-8")
    # Demote the audit's own headings so they nest under the supplementary note.
    body = "\n".join(("#" + ln) if ln.startswith("#") else ln for ln in body.splitlines())
    return f"""### Supplementary Note S2

**Dimensional audit of the orthogonal same-campaign inventory assay.**

This is the audit the main text refers to when it states that the assay and the model's fitted
inventory are not demonstrably commensurate. Reproduced from
`docs/paper1_resource/PAPER_A_TABLE7_UNITS_AUDIT.md`.

{body}
"""


def note_s1() -> str:
    return """### Supplementary Note S1

**Extended treatment of structural and practical identifiability.**

The main text's related-work section is deliberately compact because the identifiability literature
it draws on is mature. This note records the distinctions the paper relies on.

*Structural* identifiability asks whether parameters are uniquely determined by noise-free,
continuously observed data under a given observation map. It is a property of the model and the
observation map alone, decided analytically, and it is not what this paper measures.

*Practical* identifiability asks whether the parameters are localized by the data actually
available: a finite design, finite noise, a chosen objective and a bounded parameter domain. A
model can be structurally identifiable and practically non-identifiable, which is the situation
studied here. Because a practical statement is conditional on all four of those, every such claim
in this paper is scoped to the tested model, observation map, parameter domain and objective, and
the formal term is used only as shorthand for that scoped statement.

The near-optimal sets reported throughout are *declared threshold sets* on a profiled objective,
not confidence regions: no explicit likelihood or noise model is specified, so no calibrated
coverage is claimed. Where a set reaches the boundary of the tested rate domain it is reported as
censored, because its width is then a property of the domain rather than of the data.

The compensation studied here is the two-parameter case of the broader phenomenon of sloppiness,
in which model behaviour depends on a few stiff parameter combinations while remaining nearly
invariant along many sloppy ones. Sloppiness and practical non-identifiability are related but not
equivalent; the paper reports the profile directly rather than inferring localization from
eigenvalue spectra.
"""


# ── Table S6: PDE discretisation and solver-tolerance convergence ─────────────────────────────
def table_s6() -> str:
    rec = _load(CONVERGENCE_JSON)
    rows = []
    for _k, v in rec["cells"].items():
        rows.append(
            f"| {v['n_axial_nodes']} | {v['solver_tolerance']:.0e} | {v['whole_cup']:.5f} | "
            f"{v['early']:.5f} | {v['middle']:.5f} | {v['late']:.5f} | {v['rate_at_min']:.3f} | "
            f"{v['range_ratio']:.4f} | {v['rel_dev_whole_cup_pct']:.4f} | "
            f"{v['rel_dev_late_pct']:.4f} | {v['rel_dev_range_ratio_pct']:.4f} |")
    w = rec["worst_case_rel_dev_pct"]
    return f"""### Supplementary Table S6

**Convergence of the PDE discretisation and the solver tolerance.**

This is convergence of the **spatial discretisation and integration tolerance**, which is a
different quantity from the rate-parameter-grid convergence reported in the main text. It is
included because the paper's temporal-information result depends on the shape of the outlet
trajectory, so the numerics producing that shape are load-bearing.

Numerical scheme: {rec['scheme']}.

Panel: {rec['panel']}, granulometry {rec['granulometry']}, {rec['n_conditions']} conditions.
Reference cell (deviations are measured against it): `{rec['reference_cell']}`.
Production configuration: `{rec['production_cell']}`.
Producer: `{rec['producer']}`.

| axial nodes | rel/abs tolerance | whole cup | early | middle | late | rate at minimum | range ratio | dev. cup (%) | dev. late (%) | dev. range ratio (%) |
|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
{chr(10).join(rows)}

Concentrations are in mg mL⁻¹ on the model's internal basis; deviations are relative to the
reference cell.

**Reading.** {rec['reading']}

Worst-case relative deviation across all nine cells: whole cup {w['whole_cup']:.4f} %, late
fraction {w['late_fraction']:.4f} %, profile range ratio {w['range_ratio']:.4f} %. The profiled
minimum location is invariant across every cell.

**Solver warnings.** {rec['solver_warnings']}
"""


# ── stubs for items whose analysis has not been run ───────────────────────────────────────────
def stub(number: str, title: str, what_to_run: str) -> str:
    return f"""### Supplementary Table {number}

**{title}**

> **NOT YET AVAILABLE.** This item is cited by the main text but the analysis behind it has not
> been run. It is emitted as an explicit stub rather than omitted, so that the dangling reference
> is visible rather than silent.
>
> To fill it: {what_to_run}
"""


def build() -> str:
    parts = [
        "# Supplementary material",
        "",
        STAMP,
        "",
        "**Separating Extractable Content from Extraction Rate in Espresso Models: Limits of "
        "Whole-Cup Measurements and the Value of Time-Resolved Data**",
        "",
        "Every item here is cited by the main text. Tables are generated from the archived "
        "machine-readable result bundles named beneath each one; notes are reproduced from the "
        "archived audit records. Items whose analysis has not been run are marked as such rather "
        "than omitted.",
        "",
        "---",
        "",
        note_s1(), "", "---", "",
        note_s2(), "", "---", "",
        table_s1(), "", "---", "",
        table_s3(), "", "---", "",
        table_s5(), "", "---", "",
        table_s6(),
    ]
    return "\n".join(parts).rstrip() + "\n"


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else list(argv)
    fresh = build()
    if "--write" in argv:
        OUT.write_text(fresh, encoding="utf-8")
        print(f"wrote {OUT.relative_to(REPO)}")
        return 0
    if not OUT.exists():
        print(f"MISSING: {OUT.relative_to(REPO)} — run with --write")
        return 1
    if OUT.read_text(encoding="utf-8") != fresh:
        print(f"STALE: {OUT.relative_to(REPO)} — run with --write")
        return 1
    print("supplement is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
