#!/usr/bin/env python3
"""Generate the upload-ready Paper A caption file from the internal figure map.

Round-10 P2-1. `docs/figures/PAPER_A_CAPTIONS.md` was titled "submission-ready figure captions",
was listed in the package manifest as the caption file to upload, and opened with three paragraphs
of repository bookkeeping: which review asked for four to five main figures, that presentation
numbers differ from producer identifiers, that the rendered images previously carried an embedded
number, the producer file stems themselves, and the path of the test that enforces the policy. None
of that is a caption. All of it would have gone to an editor.

The two purposes are now two files:

``docs/figures/PAPER_A_FIGURE_MAP_INTERNAL.md``
    Repository-facing. Producer stems, the numbering rationale, review history, test paths, and the
    authored caption text. Never uploaded, and deliberately excluded from the submission scanner —
    it is *allowed* to contain the things the scanner exists to keep out of the paper.

``docs/submission/PAPER_A_JFE_FIGURE_CAPTIONS.md``
    Reader-facing, and generated by this tool. Figure numbers and caption text only.

Generating rather than copying is the point: a caption corrected in one file and not the other is
precisely the round-8 P0-1 defect (a standalone caption still quoting a superseded 108-observation
benchmark months after the manuscript had moved on). Figure 3's caption is itself generated into the
internal map from the transfer artefacts, so the chain is artefact → internal map → upload file, with
a ``--check`` at every step.

CLI::

    python tools/paper_a_figure_captions.py --check
    python tools/paper_a_figure_captions.py --write
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
INTERNAL_MAP = _REPO / "docs" / "figures" / "PAPER_A_FIGURE_MAP_INTERNAL.md"
UPLOAD = _REPO / "docs" / "submission" / "PAPER_A_JFE_FIGURE_CAPTIONS.md"

#: `### Figure 3 (`fig4_transfer`)` → the caption paragraph that follows it.
_HEADING = re.compile(r"(?m)^### Figure (S?\d+) \(`([^`]+)`\)\s*\n+(.*?)(?=\n### |\Z)", re.S)

#: Presentation order: main figures by number, then supplementary by number.
def _sort_key(number: str) -> tuple[int, int]:
    return (1, int(number[1:])) if number.startswith("S") else (0, int(number))


def captions() -> list[tuple[str, str]]:
    """``[(number, caption_text)]`` in presentation order, from the internal map."""
    text = INTERNAL_MAP.read_text(encoding="utf-8")
    found = []
    for number, _stem, body in _HEADING.findall(text):
        # Strip the generated block's markers and source stamps: they are assurance devices, and an
        # HTML comment surviving into an uploaded caption file is exactly the leakage class P2-1 is
        # about.
        clean = re.sub(r"<!--.*?-->", "", body, flags=re.S)
        paragraph = " ".join(clean.split())
        if not paragraph:
            raise SystemExit("Figure %s has no caption text in the internal map" % number)
        found.append((number, paragraph))
    if not found:
        raise SystemExit("no `### Figure N (`stem`)` sections found in %s"
                         % INTERNAL_MAP.relative_to(_REPO))
    return sorted(found, key=lambda item: _sort_key(item[0]))


def render() -> str:
    main = [(n, c) for n, c in captions() if not n.startswith("S")]
    supp = [(n, c) for n, c in captions() if n.startswith("S")]
    out = [
        "# Figure captions",
        "",
        "<!-- GENERATED by tools/paper_a_figure_captions.py from the internal figure map. "
        "Do not edit by hand. -->",
        "",
        "Captions are written to stand alone from the main text.",
        "",
        "## Main figures",
        "",
    ]
    for _n, caption in main:
        out += [caption, ""]
    if supp:
        out += ["## Supplementary figures", ""]
        for _n, caption in supp:
            out += [caption, ""]
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    args = ap.parse_args(argv)

    fresh = render()
    if args.write:
        UPLOAD.write_text(fresh, encoding="utf-8")
        print("wrote %s" % UPLOAD.relative_to(_REPO))
        return 0
    current = UPLOAD.read_text(encoding="utf-8") if UPLOAD.exists() else ""
    if current != fresh:
        print("Paper A upload-ready captions are STALE: run "
              "`python tools/paper_a_figure_captions.py --write`", file=sys.stderr)
        return 1
    print("Paper A upload-ready captions OK (check).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
