"""RP-D-LC-001b — corrected lateral-only virtual fixture: geometry, frozen configuration,
observable contract, admission gates and decision semantics.

PRE-EXECUTION. No lattice-Boltzmann solve is performed anywhere in this module, and none has
been performed for this tranche. Everything here is design: deterministic geometry, the frozen
forcing law, the plane/record contract, the negative-control and reachable-set admission
arithmetic, and the decision ordering. The slow driver that will eventually consume it is
``puckworks/validation/slow/rp_d_lc_001b.py`` and it refuses to run until an approved freeze
artifact exists.

RP-D-LC-001 (``docs/analysis/rp_d_lc_001/``) is CLOSED and IMMUTABLE: disposition
``INVALID_EXECUTION``, cross-model transfer UNADJUDICATED (not negative). Nothing in this module
reads, rewrites, repairs or reinterprets that bundle. 001b asks the SAME Stage-A question with a
corrected virtual apparatus; it is not a new question, not Stage B, not a Foundry screen, not a
new evidence rung, not a new registered component, and it authorizes neither Paper 4 nor any
wider RP-D work.

Two defects of the 001 execution are remedied here, and only those two:

  D1  the two resolutions were not the same dimensionless problem (001 erratum E5), and the
      forcing was high enough that the internal fields failed their own forcing-independence
      requirement (E2).  ->  a resolution-dependent forcing law g(S) = g_ref (S_ref/S)^3 that
      holds the design Reynolds number invariant, at a tenfold reduced reference forcing.

  D2  the bridge aperture was a hole through a thin divider, so opening it WIDENED THE AXIAL
      CHANNEL as well as creating a lateral path: with zero lateral driver the identical-path
      control still measured ``observed R - network R = 0.014277334586`` (001 erratum E7).
      ->  a lateral-only bridge whose lane-facing ports are present in the blocked fixture too,
      so the blocked/open difference is EXACTLY the connecting duct and nothing else.

and one measurement defect is closed: 001 recorded only ``sum(u_x)`` and could not evaluate mass
conservation at all (E4/E4b). Here every required plane retains BOTH ``sum(u_x)`` (the volume
flux the inverse consumes) and ``sum(rho*u_x)`` (the conserved mass flux), never conflated.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
from fractions import Fraction

import numpy as np

from puckworks.analysis import rp_d_lc_virtual_fixture as vf001

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]

PROGRAM_ID = "RP-D-LATERAL-CROSS-MODEL"
TRANCHE_ID = "RP-D-LC-001B"
SCHEMA_VERSION = 1

#: The exact authority this tranche was branched from. Verified by test, never inferred from HEAD.
BASE_COMMIT = "7d656811e6bf99d447dcd4f6eac04cac233a99f4"
BASE_TREE = "e31dc057a3e4d933ca71888b39e8b4d27ee6970d"

#: The closed predecessor. Its record is immutable and its failure is part of the durable
#: scientific record; this tranche re-executes the question, it does not repair that bundle.
PREDECESSOR = {
    "tranche": "RP-D-LC-001",
    "bundle": "docs/analysis/rp_d_lc_001",
    "disposition": "INVALID_EXECUTION",
    "cross_model_transfer_adjudicated": False,
    "evidence_use": "DIAGNOSTIC_ONLY_INVALID_EXECUTION",
    "axial_artifact_at_zero_lateral_driver": 0.014277334586,
    "note": "unadjudicated, NOT negative; field-derived truth insufficiently invariant with forcing",
}

BUNDLE_REL = "docs/analysis/rp_d_lc_001b"
PROTOCOL_PATH = BUNDLE_REL + "/PROTOCOL.md"
RUNS_REL = BUNDLE_REL + "/runs"
FREEZE_REL = RUNS_REL + "/bridge_freeze.json"

INPUT_FILES = (
    PROTOCOL_PATH,
    BUNDLE_REL + "/VIRTUAL_FIXTURE_SPEC.md",
    BUNDLE_REL + "/EXECUTION_MATRIX.md",
    "puckworks/analysis/rp_d_lc_001b_virtual_fixture.py",
    "puckworks/validation/slow/rp_d_lc_001b.py",
    "puckworks/models/brewer2026/lb_reference.py",
    "puckworks/analysis/screen_wp6_lateral_identifiability.py",
    "puckworks/analysis/rp_d_lc_virtual_fixture.py",
    "puckworks/models/lateral_coupling.py",
)

#: Copied BYTE-IDENTICAL from the 001 tranche. The claim ceiling is not renegotiated by a
#: re-execution; a test asserts the two tuples are equal.
CLAIM_CEILING = tuple(vf001.CLAIM_CEILING)

#: The Stage-A question, unchanged from 001. This tranche asks it again with a corrected
#: apparatus; it does not ask a new one.
QUESTION = (
    "When the ground truth is generated by an independently implemented, spatially resolved 3D "
    "creeping-flow solver rather than by model1_two_path, does the WP6-LC-IDENT boundary inverse "
    "recover the virtual fixture's independently field-derived effective lateral-coupling "
    "number Xi?"
)


# ==========================================================================================
# 1. FROZEN BASE GEOMETRY TEMPLATE — the corrected LATERAL-ONLY bridge
# ==========================================================================================
# All lengths are BASE VOXELS; a fixture at resolution S replicates every base voxel into an
# S^3 block, so two resolutions are EXACTLY geometrically similar. Flow is +x. The box is
# periodic in x (the common plenum wraps) and closed by solid no-slip walls on both y and both
# z faces, so no periodic lateral bypass can exist.
#
# The x layout is unchanged from 001. The y layout is NOT: the divider is thickened from 2 to 6
# base voxels and given an internal three-layer structure
#
#       lane 1 | port row A | duct row | port row B | lane 2
#        1..8      9..10       11..12      13..14      15..22
#
# The BLOCKED fixture opens port rows A and B over the bridge footprint but leaves the duct row
# SOLID. The OPEN fixture additionally opens the duct row. Consequently:
#
#   * the blocked/open difference is EXACTLY the duct-row footprint — the intended lateral
#     connection and nothing else;
#   * the lane-facing recesses (the ports) are common-mode: they exist in the denominator of
#     R as well as the numerator, so R compares the SAME axial network with the lateral
#     connection off and on. That is precisely what the two-node model's R means, and it is
#     what 001's blocked fixture did not provide;
#   * both ports sit at the SAME x footprint, so traversing the bridge produces no axial
#     displacement;
#   * the divider is fully solid in x immediately outside the footprint, so the bridge is
#     axially end-capped and no route through it connects two different x stations.

BASE = {
    # ---- x: [common plenum] [upstream segment] [transition] [downstream segment] -> wrap ----
    "nx": 56,
    "plenum_half": 4,                      # plenum = {x : min(x, nx - x) < 4} = {53,54,55,0,1,2,3}
    "lane_lo": 4, "lane_hi": 52,
    "seg_top_lo": 4, "seg_top_hi": 23,     # 20 base voxels
    "trans_lo": 24, "trans_hi": 32,        # 9 base voxels, both lanes at h_low, hosts the bridge
    "seg_bot_lo": 33, "seg_bot_hi": 52,    # 20 base voxels
    "bridge_centre": 28,
    # ---- y: wall | lane 1 | port A | duct | port B | lane 2 | wall ----
    "ny": 24,
    "lane1_lo": 1, "lane1_hi": 8,
    "portA_lo": 9, "portA_hi": 10,
    "duct_lo": 11, "duct_hi": 12,
    "portB_lo": 13, "portB_hi": 14,
    "lane2_lo": 15, "lane2_hi": 22,
    # ---- z: wall | fluid | wall ; the conductance contrast is the slot height ----
    "nz": 8,
    "z_lo": 1,
    "h_high": 6, "h_low": 4,
}

#: Predeclared bridge CANDIDATE family. ``w`` (the footprint's x extent, base voxels) must be odd
#: so the bridge is centred on the mirror plane x = bridge_centre; ``kz`` counts base voxels
#: upward from z_lo. w = 9 fills the transition band exactly.
BRIDGE_CANDIDATES = tuple(
    {"w": w, "kz": kz} for w in (3, 5, 7, 9) for kz in (1, 2, 3, 4)
)

#: Minimum resolved feature, in LATTICE voxels, carried over unchanged from 001 where it was
#: justified by the measured plane-channel law error(%) = 50/h^2. kz = 1 is 2 lattice voxels at
#: S_COARSE (a ~12 % element error) and is therefore excluded from the scientific subset; it
#: remains a declared candidate so the exclusion is visible rather than silent.
MIN_FEATURE_VOX = 4
CHANNEL_ERR_LAW_PCT = "50/h^2"

S_SMOKE = 1
S_COARSE = 2
S_FINE = 3
SCIENTIFIC_RESOLUTIONS = (S_COARSE, S_FINE)

#: The scientific bridge subset: every candidate whose smallest feature is resolved at S_COARSE.
SCIENTIFIC_BRIDGE_CANDIDATES = tuple(
    b for b in BRIDGE_CANDIDATES
    if b["kz"] * S_COARSE >= MIN_FEATURE_VOX and b["w"] * S_COARSE >= MIN_FEATURE_VOX
)

#: Predeclared one-voxel adversarial perturbations (carried over from 001, retargeted to this
#: template's lane-1 downstream segment). Coordinates are BASE voxels; each flips exactly one
#: lattice voxel (plug) or one lattice-voxel-thick slab at any S.
PERTURBATIONS = {
    "one_voxel_plug": {"kind": "plug", "base": (40, 4, 2)},
    "one_voxel_slab": {"kind": "slab", "base_x": 23, "lane": 1},
}


def _base_is_plenum(x: int) -> bool:
    return min(x, BASE["nx"] - x) < BASE["plenum_half"]


def _base_lane_height(x: int, lane: int) -> int:
    """Slot height (base voxels, counted up from z_lo) of ``lane`` at base station ``x``."""
    if BASE["seg_top_lo"] <= x <= BASE["seg_top_hi"]:
        return BASE["h_high"] if lane == 1 else BASE["h_low"]
    if BASE["seg_bot_lo"] <= x <= BASE["seg_bot_hi"]:
        return BASE["h_low"] if lane == 1 else BASE["h_high"]
    return BASE["h_low"]                       # the transition band: both lanes low


def bridge_x_range(w: int):
    """Inclusive base-voxel x range of a bridge of footprint width ``w``."""
    w = int(w)
    if w % 2 != 1:
        raise ValueError("bridge w must be odd so the footprint is centred on the mirror plane, "
                         "got %r" % (w,))
    half = (w - 1) // 2
    lo, hi = BASE["bridge_centre"] - half, BASE["bridge_centre"] + half
    if lo < BASE["trans_lo"] or hi > BASE["trans_hi"]:
        raise ValueError("bridge w=%r does not fit the transition band" % (w,))
    return lo, hi


def _validate_bridge(bridge):
    w, kz = int(bridge["w"]), int(bridge["kz"])
    bridge_x_range(w)
    if not 1 <= kz <= BASE["h_low"]:
        raise ValueError("bridge kz must lie in 1..%d, got %r" % (BASE["h_low"], kz))
    return w, kz


def base_mask(bridge=None, connected=False, variant="mirror"):
    """The frozen base template as a boolean SOLID mask of shape (nx, ny, nz).

    ``bridge`` None  -> the REFERENCE fixture: the divider is continuous, there is no bridge
                        structure at all. Used only for the common blocked characterisation.
    ``bridge`` dict  -> a bridge of footprint ``{w, kz}``. ``connected`` False opens the two
                        lane-facing PORT rows only (the BLOCKED fixture); True additionally opens
                        the DUCT row that joins them (the OPEN fixture).
    ``variant``      -> 'mirror' (lane 2 carries the reversed segment order) or 'identical'
                        (both lanes ordered like lane 1 — the negative control, for which the
                        cross-product gap X = g1t*g2b - g2t*g1b vanishes exactly and no lateral
                        pressure difference drives the bridge at any conductance).
    """
    if variant not in ("mirror", "identical"):
        raise ValueError("variant must be 'mirror' or 'identical', got %r" % (variant,))
    if bridge is None and connected:
        raise ValueError("connected=True requires a bridge footprint")
    nx, ny, nz = BASE["nx"], BASE["ny"], BASE["nz"]
    solid = np.ones((nx, ny, nz), dtype=bool)
    z_lo, z_hi_full = BASE["z_lo"], BASE["z_lo"] + BASE["h_high"] - 1
    for x in range(nx):
        if _base_is_plenum(x):
            solid[x, 1:ny - 1, z_lo:z_hi_full + 1] = False      # one common, full-section node
            continue
        for lane, (ylo, yhi) in ((1, (BASE["lane1_lo"], BASE["lane1_hi"])),
                                 (2, (BASE["lane2_lo"], BASE["lane2_hi"]))):
            h = _base_lane_height(x, 1 if variant == "identical" else lane)
            solid[x, ylo:yhi + 1, z_lo:z_lo + h] = False
    if bridge is not None:
        w, kz = _validate_bridge(bridge)
        xlo, xhi = bridge_x_range(w)
        rows = [(BASE["portA_lo"], BASE["portA_hi"]), (BASE["portB_lo"], BASE["portB_hi"])]
        if connected:
            rows.append((BASE["duct_lo"], BASE["duct_hi"]))
        for ylo, yhi in rows:
            solid[xlo:xhi + 1, ylo:yhi + 1, z_lo:z_lo + kz] = False
    return solid


def scale(mask_b, S: int):
    """Replicate a base mask S times on every axis — exact geometric similarity."""
    if not isinstance(S, int) or isinstance(S, bool) or S < 1:
        raise ValueError("S must be a positive int, got %r" % (S,))
    return np.repeat(np.repeat(np.repeat(mask_b, S, axis=0), S, axis=1), S, axis=2)


def mirror_x(mask, S: int):
    """The exact voxel-index x reflection about the mirror planes x = 0 and x = bridge_centre."""
    return np.roll(np.flip(mask, axis=0), S, axis=0)


def swap_paths(mask):
    """The exact path swap: reflect y about the divider mid-plane, exchanging lane 1 and lane 2.
    An index transformation of the SAME array — the swapped fixture is never rebuilt. The y
    layout is palindromic (wall|8|2|2|2|8|wall), so the flip maps port row A onto port row B and
    the duct row onto itself."""
    return np.flip(mask, axis=1)


def _apply_perturbation(mask, S: int, name: str):
    spec = PERTURBATIONS[name]
    out = mask.copy()
    if spec["kind"] == "plug":
        bx, by, bz = spec["base"]
        out[bx * S, by * S, bz * S] = True                      # exactly one lattice voxel
    elif spec["kind"] == "slab":
        x = (spec["base_x"] + 1) * S - 1
        ylo, yhi = BASE["lane1_lo"] * S, (BASE["lane1_hi"] + 1) * S - 1
        zlo = (BASE["z_lo"] + BASE["h_low"]) * S
        zhi = (BASE["z_lo"] + BASE["h_high"]) * S - 1
        out[x, ylo:yhi + 1, zlo:zhi + 1] = True
    else:                                                        # pragma: no cover - frozen set
        raise ValueError("unknown perturbation kind %r" % (spec["kind"],))
    return out


#: The three fixture states. Named so a record can never be ambiguous about which one produced it.
FIXTURE_STATES = ("reference_blocked", "blocked", "open")


def fixture_state(bridge, connected) -> str:
    if bridge is None:
        return "reference_blocked"
    return "open" if connected else "blocked"


def build_fixture(S: int, bridge=None, connected=False, variant="mirror", swapped=False,
                  perturbation=None):
    """The full virtual fixture at resolution S, with its frozen region and plane indices."""
    mask = scale(base_mask(bridge=bridge, connected=connected, variant=variant), S)
    if swapped:
        mask = swap_paths(mask)
    if perturbation is not None:
        mask = _apply_perturbation(mask, S, perturbation)
    return mask, fixture_meta(S, bridge=bridge, connected=connected, variant=variant,
                              swapped=swapped, perturbation=perturbation, mask=mask)


def fixture_meta(S, bridge=None, connected=False, variant="mirror", swapped=False,
                 perturbation=None, mask=None):
    """Every frozen index the observable calculation is allowed to use. Nothing here is fitted."""
    nx, ny, nz = BASE["nx"] * S, BASE["ny"] * S, BASE["nz"] * S
    meta = {
        "S": S, "variant": variant, "swapped": bool(swapped), "perturbation": perturbation,
        "bridge": None if bridge is None else {"w": int(bridge["w"]), "kz": int(bridge["kz"])},
        "connected": bool(connected),
        "state": fixture_state(bridge, connected),
        "shape": (nx, ny, nz),
        "lane1_y": (BASE["lane1_lo"] * S, (BASE["lane1_hi"] + 1) * S),
        "lane2_y": (BASE["lane2_lo"] * S, (BASE["lane2_hi"] + 1) * S),
        "divider_y": (BASE["portA_lo"] * S, (BASE["portB_hi"] + 1) * S),
        "duct_y": (BASE["duct_lo"] * S, (BASE["duct_hi"] + 1) * S),
        "lane_x": (BASE["lane_lo"] * S, (BASE["lane_hi"] + 1) * S),
        # ---- node surfaces: plenum planes abutting the lane ends, the only planes whose
        # cross-section is ONE connected common region, i.e. a genuine network node ----
        "x_node_in": BASE["lane_lo"] * S - 1,
        "x_node_out": (BASE["lane_hi"] + 1) * S,
        "node_offsets": (1, 2),
        # ---- outlet-flux measurement planes ----
        "x_meas_a": (BASE["lane_hi"] + 1) * S - 1,       # primary, immediately before the plenum
        "x_meas_b": 48 * S,                               # second frozen plane (plane invariance)
        "x_meas_in": BASE["lane_lo"] * S,                 # lane inlet plane
        # ---- transverse (bridge) instrumentation ----
        "y_face1": BASE["portA_lo"] * S - 1,              # last lane-1 row before the divider
        "y_face2": BASE["lane2_lo"] * S,                  # first lane-2 row after the divider
        "y_portA_in": BASE["portA_lo"] * S,               # first port-A row
        "y_duct_a": BASE["duct_lo"] * S,                  # first duct row
        "y_duct_b": (BASE["duct_hi"] + 1) * S - 1,        # last duct row
        "y_portB_out": (BASE["portB_hi"] + 1) * S - 1,    # last port-B row
        "axial_conservation_planes": axial_conservation_planes(S),
    }
    if bridge is not None:
        w, kz = _validate_bridge(bridge)
        xlo, xhi = bridge_x_range(w)
        meta["bridge_x"] = (xlo * S, (xhi + 1) * S)
        meta["bridge_z"] = (BASE["z_lo"] * S, (BASE["z_lo"] + kz) * S)
    else:
        meta["bridge_x"] = None
        meta["bridge_z"] = None
    if mask is not None:
        meta["mask_sha256"] = mask_hash(mask)
        meta["n_solid"] = int(mask.sum())
        meta["n_fluid"] = int((~mask).sum())
    return meta


#: Frozen axial conservation planes, in BASE stations. Spread over the whole lane traverse and
#: deliberately including one inside the transition band: the bridge is transverse, so the TOTAL
#: axial flux is conserved across it even where the per-lane split is not.
AXIAL_CONSERVATION_BASE = (4, 10, 16, 22, 28, 34, 40, 46)


def axial_conservation_planes(S: int):
    """Lattice x indices of the frozen axial conservation plane set (the primary outlet plane
    is included so the conservation set and the observable plane cannot drift apart)."""
    return tuple(b * S for b in AXIAL_CONSERVATION_BASE) + ((BASE["lane_hi"] + 1) * S - 1,)


def mask_hash(mask) -> str:
    """SHA-256 of the packed boolean mask plus its shape — the geometry's identity."""
    h = hashlib.sha256()
    h.update(("%d,%d,%d|" % mask.shape).encode())
    h.update(np.packbits(np.ascontiguousarray(mask, dtype=bool)).tobytes())
    return h.hexdigest()


def is_mirror_symmetric(mask, S: int) -> bool:
    """Exact voxel-index mirror test: swap_paths(mirror_x(mask)) == mask."""
    return bool(np.array_equal(swap_paths(mirror_x(mask, S)), mask))


def _periodic_x_components(fluid):
    from scipy import ndimage
    nx = fluid.shape[0]
    lab, n_raw = ndimage.label(np.concatenate([fluid, fluid], axis=0))
    a, b = lab[:nx], lab[nx:]
    parent = {}

    def find(k):
        parent.setdefault(k, k)
        while parent[k] != k:
            parent[k] = parent[parent[k]]
            k = parent[k]
        return k

    for u, v in set(zip(a[fluid].ravel().tolist(), b[fluid].ravel().tolist())):
        ru, rv = find(u), find(v)
        if ru != rv:
            parent[ru] = rv
    return int(n_raw), {find(int(v)) for v in np.unique(a[fluid])}


def connectivity(mask, meta):
    """Connected-component audit: the fluid space must form ONE component under x-periodic /
    y,z-walled connectivity, and no fluid may touch a y or z face (no periodic lateral bypass)."""
    fluid = ~mask
    n_raw, comps = _periodic_x_components(fluid)
    y_face = bool(fluid[:, 0, :].any() or fluid[:, -1, :].any())
    z_face = bool(fluid[:, :, 0].any() or fluid[:, :, -1].any())
    return {"n_components_raw": n_raw, "n_components_periodic": len(comps),
            "fluid_on_y_face": y_face, "fluid_on_z_face": z_face,
            "single_connected": len(comps) == 1,
            "no_lateral_bypass": not (y_face or z_face)}


def lane_connection(mask, meta):
    """Is there a lateral connection between the lanes INSIDE the lane region?

    Global connectivity cannot answer this — the common plenum joins the lanes at both ends by
    design. The question is answered on the lane traverse alone, with the plenum excluded: the
    lanes must be joined in the OPEN fixture and separate in the blocked and reference ones.
    """
    from scipy import ndimage
    S = meta["S"]
    xlo, xhi = meta["lane_x"]
    sub = mask[xlo:xhi]
    lab, _ = ndimage.label(~sub)
    l1lo, l1hi = meta["lane1_y"]
    l2lo, l2hi = meta["lane2_y"]
    c1 = set(np.unique(lab[:, l1lo:l1hi, :]).tolist()) - {0}
    c2 = set(np.unique(lab[:, l2lo:l2hi, :]).tolist()) - {0}
    return {"lane1_components": len(c1), "lane2_components": len(c2),
            "lanes_joined_in_lane_region": bool(c1 & c2)}


def bridge_topology(mask, meta):
    """Structural audit of the bridge itself, on the mask alone.

    ``axial_end_caps_solid``  — the divider cross-section immediately outside the footprint in
                                x is fully solid on both sides, so no route through the bridge
                                connects two different x stations;
    ``bridge_x_span``         — the observed x extent of divider-band fluid inside the lane
                                region, which must equal the footprint exactly;
    ``ports_present``         — both lane-facing port rows carry fluid over the footprint;
    ``duct_present``          — the connecting duct row carries fluid (open fixture only).
    """
    S = meta["S"]
    dlo, dhi = meta["divider_y"]
    lxlo, lxhi = meta["lane_x"]
    band = mask[lxlo:lxhi, dlo:dhi, :]
    idx = np.argwhere(~band)
    out = {"divider_band_fluid_voxels": int(idx.shape[0])}
    if meta["bridge"] is None:
        out.update(bridge_x_span=None, axial_end_caps_solid=True, ports_present=False,
                   duct_present=False, bridge_x_expected=None)
        return out
    bxlo, bxhi = meta["bridge_x"]
    bzlo, bzhi = meta["bridge_z"]
    span = (int(idx[:, 0].min()) + lxlo, int(idx[:, 0].max()) + lxlo) if idx.size else None
    caps = bool(mask[bxlo - 1, dlo:dhi, :].all() and mask[bxhi, dlo:dhi, :].all())
    pA = (BASE["portA_lo"] * S, (BASE["portA_hi"] + 1) * S)
    pB = (BASE["portB_lo"] * S, (BASE["portB_hi"] + 1) * S)
    du = meta["duct_y"]
    ports = bool((~mask[bxlo:bxhi, pA[0]:pA[1], bzlo:bzhi]).all()
                 and (~mask[bxlo:bxhi, pB[0]:pB[1], bzlo:bzhi]).all())
    duct = bool((~mask[bxlo:bxhi, du[0]:du[1], bzlo:bzhi]).all())
    out.update(bridge_x_span=span, bridge_x_expected=(bxlo, bxhi - 1),
               axial_end_caps_solid=caps, ports_present=ports, duct_present=duct)
    return out


def blocked_open_delta(S: int, bridge, variant="mirror"):
    """The exact voxel difference between the blocked and open fixtures. It must be the duct-row
    footprint and nothing else — this is the whole point of the corrected apparatus."""
    blk, meta = build_fixture(S, bridge=bridge, connected=False, variant=variant)
    opn, _ = build_fixture(S, bridge=bridge, connected=True, variant=variant)
    diff = np.argwhere(blk != opn)
    bxlo, bxhi = meta["bridge_x"]
    dylo, dyhi = meta["duct_y"]
    bzlo, bzhi = meta["bridge_z"]
    expected = {"x": set(range(bxlo, bxhi)), "y": set(range(dylo, dyhi)),
                "z": set(range(bzlo, bzhi))}
    got = {"x": set(diff[:, 0].tolist()), "y": set(diff[:, 1].tolist()),
           "z": set(diff[:, 2].tolist())}
    n_expected = len(expected["x"]) * len(expected["y"]) * len(expected["z"])
    return {
        "n_differing_voxels": int(diff.shape[0]),
        "n_expected": n_expected,
        "is_exactly_the_duct_footprint": bool(diff.shape[0] == n_expected and got == expected),
        "solid_in_blocked_fluid_in_open": bool(diff.size and blk[tuple(diff.T)].all()
                                               and not opn[tuple(diff.T)].any()),
    }


def minimum_feature_report(S: int, bridge):
    """Every critical feature's size in LATTICE voxels, and whether it clears MIN_FEATURE_VOX."""
    w, kz = _validate_bridge(bridge)
    feats = {
        "lane_width": (BASE["lane1_hi"] - BASE["lane1_lo"] + 1) * S,
        "slot_height_low": BASE["h_low"] * S,
        "slot_height_high": BASE["h_high"] * S,
        "port_row_depth": (BASE["portA_hi"] - BASE["portA_lo"] + 1) * S,
        "duct_row_depth": (BASE["duct_hi"] - BASE["duct_lo"] + 1) * S,
        "bridge_transverse_length": (BASE["portB_hi"] - BASE["portA_lo"] + 1) * S,
        "bridge_footprint_x": w * S,
        "bridge_height_kz": kz * S,
    }
    return {"features_vox": feats, "min_feature_vox": MIN_FEATURE_VOX,
            "all_resolved": all(v >= MIN_FEATURE_VOX for v in feats.values()),
            "under_resolved": sorted(k for k, v in feats.items() if v < MIN_FEATURE_VOX)}


# ==========================================================================================
# 2. COUPON GEOMETRY
# ==========================================================================================

def build_axial_coupon(S: int, level: str, orientation: str = "x"):
    """A straight x-periodic duct coupon reproducing one axial segment: same slot height, same
    lane width, same length and the same wall treatment (a 1-base outer wall on one side, the
    6-base divider on the other), cropped so the y wrap joins solid to solid. ``orientation``
    'y' rotates the CROSS-SECTION (not the flow axis, which must stay +x) so the same duct is
    calibrated in two lattice orientations and anisotropy is reported rather than assumed away.
    """
    if level not in ("high", "low"):
        raise ValueError("level must be 'high' or 'low', got %r" % (level,))
    if orientation not in ("x", "y"):
        raise ValueError("orientation must be 'x' or 'y', got %r" % (orientation,))
    h = BASE["h_high"] if level == "high" else BASE["h_low"]
    lx = BASE["seg_top_hi"] - BASE["seg_top_lo"] + 1                  # 20 base voxels
    ny_b = BASE["portB_hi"] + 1                                       # wall + lane 1 + divider
    solid_b = np.ones((lx, ny_b, BASE["nz"]), dtype=bool)
    solid_b[:, BASE["lane1_lo"]:BASE["lane1_hi"] + 1, BASE["z_lo"]:BASE["z_lo"] + h] = False
    mask = scale(solid_b, S)
    if orientation == "y":
        mask = np.ascontiguousarray(np.swapaxes(mask, 1, 2))
    meta = {"S": S, "kind": "axial_coupon", "level": level, "orientation": orientation,
            "length_vox": lx * S, "shape": tuple(int(v) for v in mask.shape),
            "mask_sha256": mask_hash(mask), "n_fluid": int((~mask).sum())}
    return mask, meta


#: Bridge-coupon geometry, frozen and NOT tuned against any assembled-fixture output. ``divider``
#: is the full transverse traverse (port A + duct + port B); ``plenum`` is the depth of the
#: reservoir on each side; ``span`` is the walled extent perpendicular to both.
BRIDGE_COUPON = {"plenum": 6, "span": 13, "divider": 6}


def build_bridge_coupon(S: int, w: int, kz: int):
    """AXIS-ROTATED bridge coupon: the whole three-layer divider traverse (port A -> duct ->
    port B) rebuilt so the transverse bridge axis lies along the solver's +x lattice direction.
    The existing x-directed kernel therefore measures the transverse conductance directly, with
    no invented anisotropy correction. Plena of the transition-band slot height sit on both
    sides and join through the x wrap, exactly as the fixture's common node does.

    Only the CONNECTED bridge has a coupon: the blocked bridge conducts nothing by construction.
    """
    w, kz = _validate_bridge({"w": w, "kz": kz})
    p, span, div = BRIDGE_COUPON["plenum"], BRIDGE_COUPON["span"], BRIDGE_COUPON["divider"]
    nx_b = 2 * p + div                       # flow axis == the fixture's transverse (y) axis
    ny_b = span                              # the fixture's x axis, walled
    nz_b = BASE["nz"]
    solid_b = np.ones((nx_b, ny_b, nz_b), dtype=bool)
    # plena: full transition-band slot height, walled in the span direction
    solid_b[:p, 1:span - 1, BASE["z_lo"]:BASE["z_lo"] + BASE["h_low"]] = False
    solid_b[p + div:, 1:span - 1, BASE["z_lo"]:BASE["z_lo"] + BASE["h_low"]] = False
    # the bridge traverse itself: footprint w centred in the span, height kz
    c = span // 2
    lo, hi = c - (w - 1) // 2, c + (w - 1) // 2
    solid_b[p:p + div, lo:hi + 1, BASE["z_lo"]:BASE["z_lo"] + kz] = False
    mask = scale(solid_b, S)
    meta = {"S": S, "kind": "bridge_coupon", "w": w, "kz": kz,
            "length_vox": div * S, "shape": tuple(int(v) for v in mask.shape),
            "mask_sha256": mask_hash(mask), "n_fluid": int((~mask).sum()),
            "geometry": dict(BRIDGE_COUPON)}
    return mask, meta


# ==========================================================================================
# 3. FROZEN SOLVER CONFIGURATION AND THE DIMENSIONLESS SIMILARITY LAW
# ==========================================================================================
# 001 ran S = 2 and S = 3 at IDENTICAL lattice g and nu with every length proportional to S. For
# a Stokes slot, u ~ g L^2 / nu and Re ~ g L^3 / nu^2, so that comparison spanned a factor
# (3/2)^3 = 3.375 in Reynolds number: two different dimensionless problems (001 erratum E5).
#
# 001b holds the design Reynolds number invariant by scaling the forcing with resolution:
#
#       g(S) = G_REF * (S_REF / S)^3
#
# At S_REF = 2 the central forcing is 2.0e-6, a TENFOLD reduction from 001's 2.0e-5 — inside the
# x8-x10 reduction the 001 decision recorded as design guidance. At S = 3 the reduction is
# x33.75. The reduction is a PREDICTION to be tested by this protocol's own forcing ladder; it
# is never assumed, and it may not be used to rescue the 001 execution.

TAU_PLUS = 2.0
TAU_CROSS_CHECK = 1.2
NU = (TAU_PLUS - 0.5) / 3.0                  # = 0.5 exactly, matching lb_reference.solve
S_REF = 2
G_REF = 2.0e-6
FORCING_FACTORS = (Fraction(1, 2), Fraction(1), Fraction(2))
FORCING_LEVELS = ("low", "central", "high")

RTOL = 1.0e-7
CHECK = 200
MIN_STEPS = 2000
MAX_STEPS = 60000
CONVERGENCE_AUDIT_FACTOR = 1.5

#: Characteristic length for the design Reynolds number: the LOW slot height, the smallest
#: flow-carrying feature common to every configuration, in lattice voxels.
SIMILARITY_LENGTH_BASE = BASE["h_low"]


def forcing_central(S: int) -> float:
    """The frozen central body force at resolution ``S``. Constructed as an exact rational so
    the two resolutions carry no rounded duplicate literals."""
    if not isinstance(S, int) or isinstance(S, bool) or S < 1:
        raise ValueError("S must be a positive int, got %r" % (S,))
    return float(Fraction(G_REF) * Fraction(S_REF ** 3, S ** 3))


def forcing_ladder(S: int):
    """The componentwise x0.5 / x1 / x2 forcing ladder at resolution ``S``, exact by rational
    construction around that resolution's own central forcing."""
    g0 = Fraction(forcing_central(S))
    return {name: float(g0 * f) for name, f in zip(FORCING_LEVELS, FORCING_FACTORS)}


def design_reynolds(S: int, g=None) -> float:
    """The dimensionless group held invariant across resolutions:

        Re_design = g * L^3 / nu^2,     L = SIMILARITY_LENGTH_BASE * S   (lattice voxels)

    It is computed from FROZEN DESIGN INPUTS ONLY — no solver output enters it — so it can be
    and is asserted equal at S = 2 and S = 3 before any run exists.
    """
    g = forcing_central(S) if g is None else float(g)
    L = SIMILARITY_LENGTH_BASE * S
    return g * L ** 3 / NU ** 2


def design_mach_scale(S: int, g=None) -> float:
    """A DIAGNOSTIC lattice-velocity scale, u ~ g L^2 / nu, times sqrt(3). It is deliberately NOT
    held invariant (it falls as 1/S under the frozen law); low Mach is a numerical admissibility
    condition, not a similarity parameter, and 001 erratum E2 records that the two are related
    but not interchangeable."""
    g = forcing_central(S) if g is None else float(g)
    L = SIMILARITY_LENGTH_BASE * S
    return float(np.sqrt(3.0)) * g * L ** 2 / NU


# ---- frozen tolerances (software/discretisation, NOT experimental uncertainties) ----------
TOL_MASS_REL = 1.0e-3          # mass-flux (rho*u) plane-to-plane spread — ADJUDICATIVE
TOL_VOLUME_FLUX_REL = 1.0e-3   # volume-flux (u) plane-to-plane spread — DIAGNOSTIC continuity
TOL_LINEARITY_REL = 1.0e-4     # componentwise forcing invariance of every truth component
TOL_MACH = 0.03
TOL_CONVERGENCE_REL = 1.0e-4
TOL_PLANE_REL = 5.0e-3
TOL_SWAP_R_REL = 5.0e-3
TOL_SWAP_XI_REL = 5.0e-2
TOL_RETURN_PATH_R_REL = 1.0e-3      # Arm J, carried over unchanged from 001 erratum E1
TOL_RETURN_PATH_S_ABS = 5.0e-4
TOL_NODE_OFFSET_R_REL = 5.0e-3
_RECORD_DP = 12


# ---- resolution consistency (NOT an asymptotic convergence-order estimate) -----------------
# Two resolutions can support a frozen CONSISTENCY test and nothing stronger. Its tolerance is
# derived BEFORE any 001b output from the discretisation law Arm A of the 001 tranche measured
# on the canonical plane channel — error(%) = 50/h^2, i.e. a fractional element error
#
#       delta(h) = 0.5 / h^2
#
# for a slot of height h lattice voxels. Between S_COARSE and S_FINE each governing feature's
# element error changes by |delta(h_coarse) - delta(h_fine)|; the tolerance is KAPPA_RES times
# the sum over the features that govern the quantity. Nothing about 001b agreement enters it.
KAPPA_RES = 2.0
RESOLUTION_CONSISTENCY_PROVENANCE = (
    "docs/analysis/rp_d_lc_001/VIRTUAL_FIXTURE_SPEC.md §5 — measured plane-channel law "
    "error(%) = 50/h^2 over h = 3..31 lattice units (Arm A of the closed RP-D-LC-001 tranche)"
)

#: Which base-voxel features govern which quantity. A quantity built only from the lane ducts is
#: governed by the two slot heights; anything carrying the bridge conductance is additionally
#: governed by the bridge's own smallest feature.
RESOLUTION_GOVERNING_FEATURES = {
    "R": ("h_low", "h_high"),
    "s": ("h_low", "h_high"),
    "C": ("h_low", "h_high"),
    "c_field": ("h_low", "h_high"),
    "A_field": ("h_low", "h_high"),
    "G_lat_field": ("h_low", "h_high", "bridge_kz"),
    "Xi_field": ("h_low", "h_high", "bridge_kz"),
    "Xi_hat": ("h_low", "h_high", "bridge_kz"),
    "Xi_coupon": ("h_low", "h_high", "bridge_kz"),
}


def element_error(h_vox: float) -> float:
    """Fractional element-level discretisation error of a slot of height ``h_vox`` lattice
    voxels, from the measured plane-channel law error(%) = 50/h^2."""
    if h_vox <= 0:
        raise ValueError("h_vox must be positive, got %r" % (h_vox,))
    return 0.5 / float(h_vox) ** 2


def _feature_base_size(name, bridge):
    if name == "h_low":
        return BASE["h_low"]
    if name == "h_high":
        return BASE["h_high"]
    if name == "bridge_kz":
        return int(bridge["kz"])
    raise KeyError(name)                                          # pragma: no cover - frozen set


def resolution_consistency_tolerance(quantity: str, bridge) -> float:
    """The frozen relative tolerance for the S_COARSE / S_FINE consistency test of ``quantity``.

    Derived ex ante from the measured discretisation law and the resolved feature sizes only —
    never from observed agreement between the 001b results.
    """
    feats = RESOLUTION_GOVERNING_FEATURES[quantity]
    total = 0.0
    for f in feats:
        b = _feature_base_size(f, bridge)
        total += abs(element_error(b * S_COARSE) - element_error(b * S_FINE))
    return KAPPA_RES * total


# ==========================================================================================
# 4. THE OBSERVABLE / CONSERVATION CONTRACT
# ==========================================================================================
# The INVERSE observable and the CONSERVATION diagnostic are different quantities and are kept
# explicitly separate. 001 conflated them: its "mass conservation" control measured sum(u_x),
# a VOLUME-flux proxy, and the rho fields needed to form sum(rho*u_x) were never retained, so
# actual mass conservation could not be evaluated at all (errata E4 / E4b).
#
#   * the WP6 / Route-A inverse consumes PRESSURE-NORMALISED VOLUME FLUX — unchanged:
#         R = (Q/dP)_open / (Q0/dP0)_blocked          s = q1 / (q1 + q2)
#     with Q, q1, q2 formed from sum(u_x). This contract is preserved; it is NOT replaced by
#     mass flux, and no new pressure component or Route-B formulation is introduced.
#
#   * CONSERVATION is evaluated on the DENSITY-WEIGHTED flux sum(rho*u_x), which is what a
#     weakly compressible solver actually conserves.
#
# sum(u) is never called a mass flux, and successful mass conservation is never inferred from
# cancellation in a ratio.

#: Frozen compact-record field names for an axial measurement plane. Every reported normalised
#: observable must be reproducible from these alone.
AXIAL_PLANE_FIELDS = (
    "plane_id",        # frozen name of the plane
    "orientation",     # 'x' — the plane's normal
    "index",           # lattice index along the normal
    "n_fluid",         # fluid-node count on the plane (its area in lattice cells)
    "sum_ux",          # SUM of u_x over fluid nodes — VOLUME flux, lattice units, +x positive
    "sum_rho_ux",      # SUM of rho*u_x over the SAME nodes — MASS flux, lattice units
    "rho_mean", "rho_sd",
    "p_mean", "p_sd",  # p = rho/3 - g*x, fluid-area averaged; sd reports nonuniformity
)

#: Frozen compact-record field names for a transverse (bridge-control) plane.
TRANSVERSE_PLANE_FIELDS = (
    "plane_id",
    "orientation",     # 'y'
    "index",
    "n_fluid",
    "sum_uy",          # SUM of u_y over the footprint — VOLUME flux, +y positive = lane1 -> lane2
    "sum_rho_uy",      # SUM of rho*u_y over the SAME nodes — MASS flux
    "footprint_x", "footprint_z",
    "sign_convention",
)

SIGN_CONVENTION_AXIAL = "positive_is_plus_x_downstream"
SIGN_CONVENTION_TRANSVERSE = "positive_is_lane1_to_lane2_along_plus_y"

#: How each retained quantity is used. Adjudicative quantities can fail an execution; diagnostic
#: ones are reported and never converted into a verdict.
QUANTITY_ROLES = {
    "sum_ux": "diagnostic_and_inverse_input",
    "sum_rho_ux": "adjudicative_conservation",
    "sum_uy": "diagnostic_and_truth_input",
    "sum_rho_uy": "adjudicative_conservation",
    "p_mean": "inverse_input_and_truth_input",
    "p_sd": "diagnostic_nonuniformity",
    "rho_mean": "diagnostic",
    "rho_sd": "diagnostic",
}


def axial_plane_record(plane_id, x, ux, rho, mask, g, y_slice=None):
    """The frozen compact record for one axial plane.

    ``ux`` is the solver's returned ux array, which already carries the +g/2 force half-shift;
    solid nodes are excluded here because the kernel leaves g/2 there rather than 0. No
    normalisation is applied: raw sums plus ``n_fluid`` are retained so any area-averaged or
    normalised quantity downstream is exactly reproducible.
    """
    fl = ~mask[x]
    if y_slice is not None:
        fl = fl.copy()
        fl[:y_slice[0]] = False
        fl[y_slice[1]:] = False
    u = ux[x][fl]
    r = rho[x][fl]
    p = r / 3.0 - g * x
    return {
        "plane_id": plane_id, "orientation": "x", "index": int(x), "n_fluid": int(fl.sum()),
        "sum_ux": float(u.sum()), "sum_rho_ux": float((r * u).sum()),
        "rho_mean": float(r.mean()) if r.size else float("nan"),
        "rho_sd": float(r.std()) if r.size else float("nan"),
        "p_mean": float(p.mean()) if p.size else float("nan"),
        "p_sd": float(p.std()) if p.size else float("nan"),
    }


def transverse_plane_record(plane_id, y, uy, rho, mask, footprint_x, footprint_z):
    """The frozen compact record for one transverse bridge-control plane."""
    xs, xe = footprint_x
    zs, ze = footprint_z
    sub_mask = mask[xs:xe, y, zs:ze]
    fl = ~sub_mask
    u = uy[xs:xe, y, zs:ze][fl]
    r = rho[xs:xe, y, zs:ze][fl]
    return {
        "plane_id": plane_id, "orientation": "y", "index": int(y), "n_fluid": int(fl.sum()),
        "sum_uy": float(u.sum()), "sum_rho_uy": float((r * u).sum()),
        "footprint_x": (int(xs), int(xe)), "footprint_z": (int(zs), int(ze)),
        "sign_convention": SIGN_CONVENTION_TRANSVERSE,
    }


def _spread(values):
    v = [float(x) for x in values]
    if not v:
        return float("nan")
    m = sum(v) / len(v)
    if m == 0.0:
        return float("nan")
    return (max(v) - min(v)) / abs(m)


def conservation_residuals(axial_records, transverse_records=()):
    """Plane-to-plane residuals, mass and volume kept apart.

    ``mass_flux_residual`` is ADJUDICATIVE against ``TOL_MASS_REL``. ``volume_flux_residual`` is
    the 001-compatible DIAGNOSTIC proxy and can never on its own decide an execution — nor can a
    small mass residual be inferred from it.
    """
    out = {
        "n_axial_planes": len(axial_records),
        "mass_flux_residual": _spread(r["sum_rho_ux"] for r in axial_records),
        "volume_flux_residual": _spread(r["sum_ux"] for r in axial_records),
        "tol_mass_rel": TOL_MASS_REL,
        "tol_volume_flux_rel": TOL_VOLUME_FLUX_REL,
        "mass_flux_residual_role": "adjudicative",
        "volume_flux_residual_role": "diagnostic",
    }
    out["mass_conservation_pass"] = bool(out["mass_flux_residual"] <= TOL_MASS_REL)
    out["volume_flux_uniformity_pass"] = bool(out["volume_flux_residual"] <= TOL_VOLUME_FLUX_REL)
    if transverse_records:
        out["n_transverse_planes"] = len(transverse_records)
        out["bridge_mass_flux_residual"] = _spread(r["sum_rho_uy"] for r in transverse_records)
        out["bridge_volume_flux_residual"] = _spread(r["sum_uy"] for r in transverse_records)
        out["bridge_mass_flux_pass"] = bool(out["bridge_mass_flux_residual"] <= TOL_MASS_REL)
    return out


# ==========================================================================================
# 5. BOUNDARY-ONLY INFERENCE — imported, never re-derived
# ==========================================================================================
# The anti-circularity boundary is the 001 contract, unchanged and IMPORTED rather than copied,
# so the two tranches cannot drift apart: infer_from_boundary accepts exactly BOUNDARY_KEYS and
# raises on anything else, and it delegates to the existing verified WP6 inverse.

BOUNDARY_KEYS = tuple(vf001.BOUNDARY_KEYS)
infer_from_boundary = vf001.infer_from_boundary

#: Keys that must NEVER appear in a boundary record. Named explicitly so the allowlist test can
#: demonstrate rejection rather than merely assert a set equality.
FORBIDDEN_BOUNDARY_KEYS = (
    "c_field", "c_truth", "Xi_field", "Xi_truth", "G_lat_field", "G_lat_coupon",
    "q_lat", "p_face1_open", "p_face2_open", "bridge", "w", "kz",
    "sum_rho_ux", "sum_rho_uy", "aperture", "mask_sha256",
)


def assert_boundary_record(record):
    """Validate a boundary record against the frozen allowlist BEFORE it reaches the inverse."""
    keys = tuple(sorted(record))
    if keys != tuple(sorted(BOUNDARY_KEYS)):
        raise ValueError(
            "boundary record must carry exactly %r; got %r — the anti-circularity contract "
            "forbids passing any truth-side quantity to the inverse." % (sorted(BOUNDARY_KEYS),
                                                                         list(keys)))
    return dict(record)


# ==========================================================================================
# 6. NEGATIVE-CONTROL ARTIFACT METRICS AND THE ARTIFACT BUDGET
# ==========================================================================================
# The decisive pre-execution control: with the two lanes IDENTICAL the cross-product gap
# X = g1t*g2b - g2t*g1b is exactly zero, so no lateral pressure difference drives the bridge at
# any conductance and the two-node network predicts R = 1 and s = 1/2 for ANY positive G_lat.
# Opening the bridge must therefore leave the axial conductance materially unchanged. In 001 it
# did not: the residual was R - 1 = 0.014277334586.
#
# The budget is set BEFORE any 001b output, from the repository's established 0.1 % observable
# nuisance scale (the Route-A isolation bound of 001 erratum E1, TOL_RETURN_PATH_R_REL = 1e-3)
# applied to the same observable the inverse consumes. Its consequence for the science is
# bounded ex ante in ``artifact_budget_justification()``: across the whole WP6 transition window
# a 1e-3 artifact biases Xi_hat by under ~6 %, far inside the factor-of-two recovery criterion.

ARTIFACT_BUDGET_R_ABS = 1.0e-3
ARTIFACT_BUDGET_PROVENANCE = (
    "programme 0.1 % observable-level nuisance scale; identical to TOL_RETURN_PATH_R_REL frozen "
    "in RP-D-LC-001 erratum E1 for the Route-A isolation gate"
)
#: Conservative, non-common-mode upper bound on the numerical uncertainty of R: the frozen
#: mass-conservation tolerance taken at full value, assuming NO cancellation between the open
#: and blocked runs. Derived from an existing frozen tolerance, never from observed agreement.
NUMERICAL_UNCERTAINTY_R_ABS = TOL_MASS_REL


def artifact_metrics(C_open, C_blocked, R_identical, R_identical_mass=None,
                     numerical_uncertainty=NUMERICAL_UNCERTAINTY_R_ABS):
    """Every required form of the zero-lateral-driver axial artifact, physical and normalised.

    The ADJUDICATIVE metric is ``pressure_normalised_R_change`` = ``R_identical - 1``: it is the
    quantity the inverse consumes, in the pressure-normalised form Route A requires. The
    mass-flux form is retained as a separate DIAGNOSTIC and is never substituted for it.
    """
    signed = float(C_open) - float(C_blocked)
    return {
        "signed_conductance_change": signed,
        "absolute_conductance_change": abs(signed),
        "relative_conductance_change": signed / float(C_blocked),
        "pressure_normalised_R_change": float(R_identical) - 1.0,
        "mass_flux_R_change": (None if R_identical_mass is None
                               else float(R_identical_mass) - 1.0),
        "numerical_uncertainty_R_abs": float(numerical_uncertainty),
        "adjudicative_metric": "pressure_normalised_R_change",
        "budget_R_abs": ARTIFACT_BUDGET_R_ABS,
        "within_budget": bool(abs(float(R_identical) - 1.0) <= ARTIFACT_BUDGET_R_ABS),
    }


# ==========================================================================================
# 7. REACHABLE-SET PROTECTION
# ==========================================================================================
# The two-node mirror network's forward map is exact (WP6-LC-IDENT DECISIVE_EXPERIMENT.md §7):
#
#       R - 1 = [c^2 / (1 - c^2)] * [Xi / (1 + Xi)]
#
# so as Xi -> infinity, R - 1 approaches the hard ceiling c^2/(1-c^2) from below. An observation
# above that ceiling is reproducible by NO (c, Xi) pair: the inverse absorbs the excess by
# inflating c_hat, which is exactly what happened at 001's largest aperture (observed
# R - 1 = 0.1338 against a ceiling of 0.1155 at c_field = 0.3218).
#
# 001b admits a bridge candidate only if its PREDICTED signal, plus the measured axial-artifact
# bound, plus a conservative numerical-uncertainty bound, stays below the ceiling by a material
# predeclared margin.

#: Safety margin as a fraction of the ceiling. Justified by conditioning, not by taste: with
#: eps = (R-1)/K the inverse gives Xi = eps/(1-eps), so the RELATIVE error amplification is
#: d(ln Xi)/d(ln eps) = 1/(1-eps). Requiring eps <= 0.90 caps that amplification at 10x.
REACHABLE_SAFETY_MARGIN_FRACTION = 0.10
REACHABLE_MARGIN_JUSTIFICATION = (
    "eps = (R-1)/K, Xi = eps/(1-eps), d(ln Xi)/d(ln eps) = 1/(1-eps); the frozen margin caps the "
    "inverse's relative-error amplification at 10x"
)
#: Conservative allowance applied to the reference-blocked c_field before it is used in the
#: ceiling. The bridge ports sit in the transition band, symmetric between the lanes and split
#: symmetrically by the bridge plane, so to first order they cancel in the contrast; 5 % is a
#: generous bound on the residual. A SMALLER c gives a SMALLER ceiling, so this is strictly
#: conservative for admission.
C_FIELD_GATE_ALLOWANCE = 0.05


def reachable_ceiling(c: float) -> float:
    """The two-node model's hard ceiling on R - 1 at the given signed axial contrast."""
    c = float(c)
    if not -1.0 < c < 1.0:
        raise ValueError("contrast c must lie strictly in (-1, 1), got %r" % (c,))
    return c * c / (1.0 - c * c)


def predicted_R_minus_1(c: float, Xi: float) -> float:
    """The exact forward map R - 1 = [c^2/(1-c^2)] * [Xi/(1+Xi)]."""
    Xi = float(Xi)
    if Xi < 0.0:
        raise ValueError("Xi must be non-negative, got %r" % (Xi,))
    return reachable_ceiling(c) * (Xi / (1.0 + Xi))


def max_admissible_Xi(c: float, artifact_bound: float,
                      numerical_uncertainty: float = NUMERICAL_UNCERTAINTY_R_ABS,
                      margin_fraction: float = REACHABLE_SAFETY_MARGIN_FRACTION) -> float:
    """The largest Xi that can satisfy the admission inequality at this contrast, or 0.0 if the
    artifact and numerical bounds already consume the whole margin."""
    K = reachable_ceiling(c)
    headroom = K * (1.0 - margin_fraction) - float(artifact_bound) - float(numerical_uncertainty)
    if headroom <= 0.0:
        return 0.0
    frac = headroom / K
    if frac >= 1.0:                                              # pragma: no cover - unreachable
        return float("inf")
    return frac / (1.0 - frac)


def reachable_set_admission(c_field_reference, Xi_predicted, artifact_bound,
                            numerical_uncertainty=NUMERICAL_UNCERTAINTY_R_ABS,
                            margin_fraction=REACHABLE_SAFETY_MARGIN_FRACTION,
                            c_allowance=C_FIELD_GATE_ALLOWANCE):
    """The frozen admission test:

        predicted_signal + axial_artifact_bound + numerical_uncertainty_bound
            <  reachable_ceiling - frozen_safety_margin

    ``c_field_reference`` comes from the P0 reference-blocked fixture. It NEVER comes from a
    mirror open case, so no primary output can enter the gate that decides which candidate is
    frozen. The point estimate is not permitted to sit microscopically inside the ceiling: the
    margin is a fixed, predeclared fraction of the ceiling with a conditioning justification.
    """
    c_gate = (1.0 - float(c_allowance)) * abs(float(c_field_reference))
    K = reachable_ceiling(c_gate)
    margin = margin_fraction * K
    signal = predicted_R_minus_1(c_gate, Xi_predicted)
    lhs = signal + float(artifact_bound) + float(numerical_uncertainty)
    rhs = K - margin
    return {
        "c_field_reference": float(c_field_reference),
        "c_gate": c_gate, "c_allowance": float(c_allowance),
        "reachable_ceiling": K,
        "safety_margin": margin,
        "safety_margin_fraction": float(margin_fraction),
        "safety_margin_justification": REACHABLE_MARGIN_JUSTIFICATION,
        "predicted_signal": signal,
        "axial_artifact_bound": float(artifact_bound),
        "numerical_uncertainty_bound": float(numerical_uncertainty),
        "lhs": lhs, "rhs": rhs,
        "headroom": rhs - lhs,
        "admitted": bool(lhs < rhs),
        "max_admissible_Xi": max_admissible_Xi(c_gate, artifact_bound, numerical_uncertainty,
                                               margin_fraction),
    }


def artifact_budget_justification(c_field_reference,
                                  Xi_lo=vf001.XI_WINDOW_LO, Xi_hi=vf001.XI_WINDOW_HI,
                                  artifact=ARTIFACT_BUDGET_R_ABS):
    """Bound, ex ante, what the artifact budget costs the science: the relative bias it can
    induce in Xi_hat at each end of the WP6 transition window. Derived from the exact forward map
    and the frozen budget only — no 001b output exists or is consulted."""
    c = (1.0 - C_FIELD_GATE_ALLOWANCE) * abs(float(c_field_reference))
    K = reachable_ceiling(c)
    out = {"c_gate": c, "reachable_ceiling": K, "artifact": float(artifact), "ends": {}}
    for name, Xi in (("window_lo", float(Xi_lo)), ("window_hi", float(Xi_hi))):
        eps = Xi / (1.0 + Xi)
        d_eps_rel = (artifact / K) / eps
        out["ends"][name] = {
            "Xi": Xi, "signal_R_minus_1": K * eps,
            "relative_signal_perturbation": d_eps_rel,
            "amplification": 1.0 / (1.0 - eps),
            "relative_Xi_bias": d_eps_rel / (1.0 - eps),
        }
    out["max_relative_Xi_bias"] = max(v["relative_Xi_bias"] for v in out["ends"].values())
    out["factor_of_two_criterion"] = 1.0
    out["well_inside_factor_of_two"] = bool(out["max_relative_Xi_bias"] < 0.25)
    return out


# ==========================================================================================
# 8. DETERMINISTIC CANDIDATE SELECTION (the bridge freeze rule)
# ==========================================================================================
# Committed BEFORE any coupon output exists and applied MECHANICALLY. It reads coupon-predicted
# Xi and the P1 artifact bound only — never a mirror full-fixture observable.

XI_WINDOW_LO = vf001.XI_WINDOW_LO
XI_WINDOW_HI = vf001.XI_WINDOW_HI
XI_WINDOW_PROVENANCE = vf001.XI_WINDOW_PROVENANCE
N_LOG_TARGETS = 3

FREEZE_RULE = (
    "From the SCIENTIFIC bridge candidates that (a) pass the identical-path axial-artifact "
    "budget at BOTH scientific resolutions and (b) pass the reachable-set admission test, take: "
    "the candidate with the largest coupon-predicted Xi strictly below XI_WINDOW_LO; the one "
    "with the smallest coupon-predicted Xi strictly above XI_WINDOW_HI; and the candidates "
    "nearest to each of 3 log-spaced targets inside the window. Deduplicate preserving order. "
    "Ties are broken on smaller w, then smaller kz. The rule reads coupon output and the "
    "identical-path artifact ONLY; no mirror full-fixture R, s or Xi_hat may be inspected before "
    "the freeze file exists."
)


def log_targets(lo=None, hi=None, n=N_LOG_TARGETS):
    lo = XI_WINDOW_LO if lo is None else lo
    hi = XI_WINDOW_HI if hi is None else hi
    return [float(np.exp(t)) for t in np.linspace(np.log(lo), np.log(hi), n + 2)[1:-1]]


def _cand_key(c):
    return (int(c["w"]), int(c["kz"]))


def select_bridges(candidates):
    """Apply FREEZE_RULE. ``candidates`` is an iterable of dicts with ``w``, ``kz``,
    ``Xi_coupon`` and ``admitted``. Returns the frozen ordered selection. Deterministic: no RNG,
    no floating-point tie ambiguity (ties resolve on the integer geometry)."""
    adm = [c for c in candidates if c.get("admitted")]
    picked, seen = [], set()

    def take(sub, key):
        if not sub:
            return
        best = sorted(sub, key=key)[0]
        k = _cand_key(best)
        if k not in seen:
            seen.add(k)
            picked.append(best)

    below = [c for c in adm if c["Xi_coupon"] < XI_WINDOW_LO]
    take(below, lambda c: (-c["Xi_coupon"], _cand_key(c)))
    above = [c for c in adm if c["Xi_coupon"] > XI_WINDOW_HI]
    take(above, lambda c: (c["Xi_coupon"], _cand_key(c)))
    inside = [c for c in adm if XI_WINDOW_LO <= c["Xi_coupon"] <= XI_WINDOW_HI]
    for t in log_targets():
        take(inside, lambda c, t=t: (abs(np.log(c["Xi_coupon"]) - np.log(t)), _cand_key(c)))
    return picked


# ==========================================================================================
# 9. DECISION SEMANTICS — carried forward from 001, fail-closed
# ==========================================================================================
# Execution validity is the first gate and it dominates. If any clause-1 control fails, the
# disposition is INVALID_EXECUTION, clauses 2-7 are NOT REACHED (adjudicative: false), the
# cross-model transfer question stays UNADJUDICATED, and no negative cross-model claim may be
# made. Recovery numbers may be reported only as clearly labelled diagnostics.

DISPOSITIONS = (
    "CROSS_MODEL_RECOVERY",
    "MECHANISM_ONLY",
    "NO_CROSS_MODEL_TRANSFER",
    "INVALID_EXECUTION",
    "DESIGN_MISSED_TARGET",
)

#: A pre-execution stop, NOT a scientific disposition: no solve of the primary experiment ran.
DESIGN_BLOCKED = "DESIGN_BLOCKED_PRE_EXECUTION"

#: Execution-validity controls, in evaluation order. ``required`` controls roll into clause 1.
VALIDITY_CONTROLS = (
    ("convergence", True, "every scientific run converges before MAX_STEPS"),
    ("low_mach_regime", True, "max Mach <= TOL_MACH (a Mach condition ONLY — not a Re condition)"),
    ("componentwise_creeping_flow_control", True,
     "every Stokes-proportional component divided by g has relative spread <= TOL_LINEARITY_REL "
     "across the resolution's own x0.5/x1/x2 ladder"),
    ("mass_conservation", True,
     "plane-to-plane sum(rho*u_x) spread <= TOL_MASS_REL — MEASURED, not proxied"),
    ("bridge_mass_flux_consistency", True,
     "the four transverse bridge-control planes carry the same sum(rho*u_y) within TOL_MASS_REL"),
    ("topology", True,
     "exact mirror symmetry, one connected fluid domain, no periodic lateral bypass, axial end "
     "caps solid, blocked/open delta exactly the duct footprint, lanes joined in the lane region "
     "only when open"),
    ("negative_control_axial_artifact", True,
     "identical-path |R - 1| <= ARTIFACT_BUDGET_R_ABS at both resolutions for the frozen bridge"),
    ("reachable_set_admission", True,
     "the frozen bridge satisfies the admission inequality with the frozen safety margin"),
    ("measurement_plane_invariance", True, "|s(x_meas_a) - s(x_meas_b)| <= TOL_PLANE_REL"),
    ("resolution_consistency", True,
     "S_COARSE vs S_FINE agreement within the ex-ante derived per-quantity tolerance — a frozen "
     "CONSISTENCY test, NOT an asymptotic convergence-order estimate"),
    ("route_a_isolation_gate", True,
     "Arm J: |R_obstructed/R_nominal - 1| <= TOL_RETURN_PATH_R_REL and |ds| <= "
     "TOL_RETURN_PATH_S_ABS in every decision-carrying case"),
    ("coarse_graining_surface_stability", True,
     "the frozen node-surface offsets do not change window membership, factor-of-two status or "
     "the classification"),
    ("boundary_inference_forcing_stability", True,
     "R, s, c_hat, Xi_hat stable across the forcing ladder within TOL_LINEARITY_REL"),
    ("volume_flux_uniformity", False,
     "DIAGNOSTIC continuity with 001's frozen proxy; never decides an execution"),
    ("backend_cross_check", False,
     "reference/Taichi where available; absent -> NOT PERFORMED, never 'passed'"),
    ("determinism", True, "an identical configuration reproduces the compact record exactly"),
)

#: The seven decision clauses, in execution order. Clause 1 is execution validity and dominates.
DECISION_CLAUSES = (
    {"n": 1, "name": "execution_valid",
     "inputs": "every required VALIDITY_CONTROLS entry",
     "tolerance": "each control's own frozen tolerance",
     "authority": "PROTOCOL.md §9-§10",
     "fail": "INVALID_EXECUTION; clauses 2-7 NOT REACHED",
     "later_clauses_adjudicative_after_failure": False},
    {"n": 2, "name": "window_population",
     "inputs": "Xi_field per frozen bridge, per resolution",
     "tolerance": ">=3 cases with XI_WINDOW_LO <= Xi_field <= XI_WINDOW_HI at EACH resolution",
     "authority": "WP6-LC-IDENT post-hoc 1 % continuous window, copied not restated",
     "fail": "DESIGN_MISSED_TARGET",
     "later_clauses_adjudicative_after_failure": False},
    {"n": 3, "name": "factor_of_two_recovery",
     "inputs": "Xi_hat, Xi_field for every window case",
     "tolerance": "inverse status == 'ok' and 0.5 <= Xi_hat/Xi_field <= 2.0",
     "authority": "PROTOCOL.md §10", "fail": "MECHANISM_ONLY or NO_CROSS_MODEL_TRANSFER",
     "later_clauses_adjudicative_after_failure": True},
    {"n": 4, "name": "contrast_recovery",
     "inputs": "c_hat, c_field for every window case",
     "tolerance": "sign(c_hat) == sign(c_field) and |c_hat - c_field| <= 0.10",
     "authority": "PROTOCOL.md §10", "fail": "MECHANISM_ONLY or NO_CROSS_MODEL_TRANSFER",
     "later_clauses_adjudicative_after_failure": True},
    {"n": 5, "name": "monotonicity",
     "inputs": "Xi_hat vs Xi_field over the frozen bridge family, per resolution",
     "tolerance": "strictly monotone", "authority": "PROTOCOL.md §10",
     "fail": "NO_CROSS_MODEL_TRANSFER",
     "later_clauses_adjudicative_after_failure": True},
    {"n": 6, "name": "path_swap",
     "inputs": "R, s, c_field, c_hat, Xi_field, Xi_hat under the exact swap transform",
     "tolerance": "sign of (s - 1/2), c_field and c_hat reversed; R, Xi_field, Xi_hat preserved "
                  "within TOL_SWAP_R_REL / TOL_SWAP_XI_REL",
     "authority": "PROTOCOL.md §10", "fail": "NO_CROSS_MODEL_TRANSFER",
     "later_clauses_adjudicative_after_failure": True},
    {"n": 7, "name": "resolution_stability_of_classification",
     "inputs": "the clause-2..6 classification at S_COARSE and S_FINE",
     "tolerance": "identical classification", "authority": "PROTOCOL.md §10",
     "fail": "NO_CROSS_MODEL_TRANSFER",
     "later_clauses_adjudicative_after_failure": True},
)


def decide(controls, clauses):
    """Frozen decision, fail-closed.

    ``controls`` maps a VALIDITY_CONTROLS name to True (pass), False (fail) or None
    (NOT_EVALUATED). ``clauses`` maps clause numbers 2..7 to computed booleans. A required
    control that is None is fail-closed: it cannot pass an execution.
    """
    required = [n for n, req, _ in VALIDITY_CONTROLS if req]
    failed = [n for n in required if controls.get(n) is False]
    not_eval = [n for n in required if controls.get(n) is None]
    valid = not failed and not not_eval
    out = {
        "execution_valid": valid,
        "failed_controls": failed,
        "not_evaluated_required_controls": not_eval,
        "primary_cause": (failed[0] if failed else (not_eval[0] if not_eval else None)),
        "clauses": [],
        "cross_model_transfer_adjudicated": False,
    }
    if not valid:
        out["disposition"] = "INVALID_EXECUTION"
        out["evidence_use"] = "DIAGNOSTIC_ONLY_INVALID_EXECUTION"
        for spec in DECISION_CLAUSES:
            n = spec["n"]
            if n == 1:
                out["clauses"].append({"n": 1, "name": spec["name"], "pass": False,
                                       "adjudicative": True, "status": "FAILED"})
                continue
            out["clauses"].append({
                "n": n, "name": spec["name"], "pass": None, "adjudicative": False,
                "status": "DIAGNOSTIC_ONLY_NOT_REACHED",
                "diagnostic_computed_pass": (None if clauses.get(n) is None
                                             else bool(clauses.get(n))),
            })
        return out

    out["clauses"].append({"n": 1, "name": "execution_valid", "pass": True,
                           "adjudicative": True, "status": "PASSED"})
    stop = False
    for spec in DECISION_CLAUSES[1:]:
        n = spec["n"]
        got = clauses.get(n)
        if stop:
            out["clauses"].append({"n": n, "name": spec["name"], "pass": None,
                                   "adjudicative": False,
                                   "status": "DIAGNOSTIC_ONLY_NOT_REACHED",
                                   "diagnostic_computed_pass": (None if got is None
                                                                else bool(got))})
            continue
        ok = bool(got)
        out["clauses"].append({"n": n, "name": spec["name"], "pass": ok, "adjudicative": True,
                               "status": "PASSED" if ok else "FAILED"})
        if not ok and not spec["later_clauses_adjudicative_after_failure"]:
            stop = True
    passes = {c["n"]: c["pass"] for c in out["clauses"]}
    if passes.get(2) is False:
        out["disposition"] = "DESIGN_MISSED_TARGET"
    elif all(passes.get(n) for n in range(1, 8)):
        out["disposition"] = "CROSS_MODEL_RECOVERY"
        out["cross_model_transfer_adjudicated"] = True
    elif passes.get(5) and passes.get(6) and passes.get(7) and not (passes.get(3)
                                                                    and passes.get(4)):
        out["disposition"] = "MECHANISM_ONLY"
        out["cross_model_transfer_adjudicated"] = True
    else:
        out["disposition"] = "NO_CROSS_MODEL_TRANSFER"
        out["cross_model_transfer_adjudicated"] = True
    out["evidence_use"] = ("ADJUDICATED" if out["cross_model_transfer_adjudicated"]
                           else "DIAGNOSTIC_ONLY")
    return out


# ==========================================================================================
# 10. EXECUTION PHASES AND THE PLANNED MATRIX
# ==========================================================================================

EXECUTION_PHASES = (
    {"id": "P0", "name": "common blocked characterisation",
     "purpose": "establish the reference-blocked c_field, A1, A2 and the axial coupons; retain "
                "every volume- and mass-flux diagnostic",
     "reveals": "reference-blocked internals and coupon conductances only",
     "authorised_now": False},
    {"id": "P1", "name": "candidate identical-path controls",
     "purpose": "measure the zero-lateral-driver axial artifact directly, per candidate, at both "
                "resolutions",
     "reveals": "identical-path blocked/open observables only; NO mirror recovery case is run "
                "or inspected",
     "authorised_now": False},
    {"id": "P2", "name": "admissibility and bridge freeze",
     "purpose": "apply the artifact budget, then the reachable-set admission test, then the "
                "coupon-only FREEZE_RULE; write and hash the freeze artifact",
     "reveals": "bridge coupon conductances only",
     "authorised_now": False},
    {"id": "P3", "name": "primary mirror / path-swap experiment",
     "purpose": "the experiment the tranche exists to perform",
     "reveals": "the primary observables — may execute only from an expressly approved frozen head",
     "authorised_now": False},
    {"id": "P4", "name": "Arm J return-path nuisance isolation",
     "purpose": "repeat the plenum obstruction for every decision-carrying case and gate Route-A "
                "isolation on R and s",
     "reveals": "obstructed counterparts of the primary cases",
     "authorised_now": False},
)

#: Arm J, preserved from the 001 programme and NOT silently dropped to shrink the matrix.
ARM_J = {
    "purpose": "isolate the common-return-plenum nuisance: 001 erratum E1 showed the ABSOLUTE "
               "lane conductance is not separable from the plenum (-1.84 % / -1.88 % under an "
               "extreme obstruction) while the pressure-normalised ratio R moved only 3.7e-4. "
               "Arm J converts that single smoke-scale probe into a gated control.",
    "relationship_to_corrected_geometry": "unchanged by the bridge redesign — the obstruction "
               "touches only plenum voxels and preserves both fixture symmetries, so it applies "
               "to the lateral-only bridge exactly as it applied to the 001 aperture. The "
               "corrected blocked reference makes it STRICTER, because the ports are now "
               "common-mode and cannot mask a return-path movement.",
    "status": "decision_bearing",
    "gate": {"R_rel": TOL_RETURN_PATH_R_REL, "s_abs": TOL_RETURN_PATH_S_ABS},
    "fail_semantics": "INVALID_EXECUTION — never a relaxed second tolerance and never a switch "
                      "to Route B, which remains unauthorized",
    "ordering": "after P3's nominal cases, before adjudication",
    "planned_solves": 20,
    "matrix": "5 frozen bridges x {blocked, open} x {S=2, S=3}, central forcing, plenum obstructed",
}


def _matrix_rows():
    rows = []
    n_sci = len(SCIENTIFIC_BRIDGE_CANDIDATES)

    # ---- P0 --------------------------------------------------------------------------------
    for S in SCIENTIFIC_RESOLUTIONS:
        for level in FORCING_LEVELS:
            rows.append({"phase": "P0", "kind": "reference_blocked_ladder", "S": S,
                         "forcing_level": level, "forcing": forcing_ladder(S)[level],
                         "state": "reference_blocked", "variant": "mirror", "bridge": None,
                         "arm": "P0", "class": "mandatory",
                         "record": "axial planes (volume+mass), node pressures, face pressures"})
    for S in SCIENTIFIC_RESOLUTIONS:
        for level in ("high", "low"):
            for orient in ("x", "y"):
                rows.append({"phase": "P0", "kind": "axial_coupon", "S": S,
                             "forcing_level": "central", "forcing": forcing_central(S),
                             "state": "coupon", "variant": level, "bridge": None,
                             "arm": "P0", "class": "mandatory",
                             "record": "duct conductance Q/(g L), both lattice orientations"})

    # ---- P1 --------------------------------------------------------------------------------
    for b in SCIENTIFIC_BRIDGE_CANDIDATES:
        for S in SCIENTIFIC_RESOLUTIONS:
            for connected in (False, True):
                rows.append({"phase": "P1", "kind": "identical_path_control", "S": S,
                             "forcing_level": "central", "forcing": forcing_central(S),
                             "state": "open" if connected else "blocked", "variant": "identical",
                             "bridge": dict(b), "arm": "P1", "class": "mandatory",
                             "record": "axial planes (volume+mass), transverse planes, node and "
                                       "face pressures, R_identical"})

    # ---- P2 --------------------------------------------------------------------------------
    for b in SCIENTIFIC_BRIDGE_CANDIDATES:
        for S in SCIENTIFIC_RESOLUTIONS:
            rows.append({"phase": "P2", "kind": "bridge_coupon", "S": S,
                         "forcing_level": "central", "forcing": forcing_central(S),
                         "state": "coupon", "variant": "bridge", "bridge": dict(b),
                         "arm": "P2", "class": "conditional_on_P1",
                         "record": "transverse bridge conductance G_bridge_coupon"})

    # ---- P3 (conditional on the freeze) ----------------------------------------------------
    n_frozen = N_LOG_TARGETS + 2
    for i in range(n_frozen):
        for S in SCIENTIFIC_RESOLUTIONS:
            for level in FORCING_LEVELS:
                for connected in (False, True):
                    rows.append({"phase": "P3", "kind": "primary_mirror", "S": S,
                                 "forcing_level": level, "forcing": forcing_ladder(S)[level],
                                 "state": "open" if connected else "blocked", "variant": "mirror",
                                 "bridge": "frozen_%d" % i, "arm": "P3",
                                 "class": "conditional_on_freeze",
                                 "record": "full compact record + boundary record + field truth"})
    for i in range(n_frozen):
        for S in SCIENTIFIC_RESOLUTIONS:
            for connected in (False, True):
                rows.append({"phase": "P3", "kind": "path_swap_control", "S": S,
                             "forcing_level": "central", "forcing": forcing_central(S),
                             "state": "open" if connected else "blocked", "variant": "mirror",
                             "swapped": True, "bridge": "frozen_%d" % i, "arm": "G",
                             "class": "conditional_on_freeze",
                             "record": "full compact record"})
    for pert in sorted(PERTURBATIONS):
        for connected in (False, True):
            rows.append({"phase": "P3", "kind": "adversarial_perturbation", "S": S_FINE,
                         "forcing_level": "central", "forcing": forcing_central(S_FINE),
                         "state": "open" if connected else "blocked", "variant": "mirror",
                         "perturbation": pert, "bridge": "frozen_0", "arm": "I",
                         "class": "conditional_on_freeze", "record": "full compact record"})
    for S in SCIENTIFIC_RESOLUTIONS:
        rows.append({"phase": "P3", "kind": "forced_step_convergence_audit", "S": S,
                     "forcing_level": "central", "forcing": forcing_central(S),
                     "state": "open", "variant": "mirror", "bridge": "frozen_0", "arm": "A",
                     "class": "conditional_on_freeze",
                     "record": "observables at 1.5x the converged step count"})

    # ---- P4 Arm J --------------------------------------------------------------------------
    for i in range(n_frozen):
        for S in SCIENTIFIC_RESOLUTIONS:
            for connected in (False, True):
                rows.append({"phase": "P4", "kind": "arm_j_return_path", "S": S,
                             "forcing_level": "central", "forcing": forcing_central(S),
                             "state": "open" if connected else "blocked", "variant": "mirror",
                             "obstructed": True, "bridge": "frozen_%d" % i, "arm": "J",
                             "class": "conditional_on_P3",
                             "record": "R, s and the induced c_hat / Xi_hat movements"})

    # ---- determinism replicates --------------------------------------------------------------
    # Each replicate repeats a case its OWN phase already runs, so a replicate can never reveal
    # something the phase is not permitted to see: P1's is an identical-path case, not a mirror
    # one, and P0's is the bridge-free reference.
    for phase, state, variant, bridge in (("P0", "reference_blocked", "mirror", None),
                                          ("P1", "blocked", "identical", "first_scientific"),
                                          ("P3", "blocked", "mirror", "frozen_0")):
        rows.append({"phase": phase, "kind": "determinism_replicate", "S": S_COARSE,
                     "forcing_level": "central", "forcing": forcing_central(S_COARSE),
                     "state": state, "variant": variant, "bridge": bridge,
                     "arm": "determinism", "class": "diagnostic_only",
                     "record": "byte-identical compact record"})
    assert n_sci  # the family must be non-empty
    return rows


def execution_matrix():
    """The complete planned matrix with exact solve counts. NOTHING here has been executed."""
    rows = _matrix_rows()
    by_phase, by_class = {}, {}
    for r in rows:
        by_phase[r["phase"]] = by_phase.get(r["phase"], 0) + 1
        by_class[r["class"]] = by_class.get(r["class"], 0) + 1
    mandatory = by_class.get("mandatory", 0)
    return {
        "tranche": TRANCHE_ID,
        "solves_executed": 0,
        "rows": rows,
        "n_rows": len(rows),
        "by_phase": by_phase,
        "by_class": by_class,
        "mandatory_scheduled": mandatory,
        "conditional": len(rows) - mandatory - by_class.get("diagnostic_only", 0),
        "diagnostic_only": by_class.get("diagnostic_only", 0),
        "maximum_possible": len(rows),
        "ordering": "P0 -> P1 -> P2 (freeze) -> P3 -> P4, strictly; within a phase, rows in the "
                    "order emitted here",
        "early_stop": {
            "P1": "if NO candidate meets ARTIFACT_BUDGET_R_ABS at both resolutions, stop with "
                  "DESIGN_BLOCKED_PRE_EXECUTION; P2, P3 and P4 are not run",
            "P2": "if fewer than 3 admitted candidates have coupon-predicted Xi inside the "
                  "window, stop and report the calibration-to-assembly gap; do not re-select",
            "P3": "any run reaching MAX_STEPS is UNCONVERGED and stops the phase; no retry at a "
                  "looser tolerance",
            "P4": "a breached Route-A isolation bound gives INVALID_EXECUTION, never a relaxed "
                  "second tolerance",
        },
        "rerun_policy": "no replicates — every case is deterministic with no RNG; one replicate "
                        "per phase is run solely to demonstrate byte-identical reproduction",
        "compute_note": "PLANNING INFORMATION ONLY, not an admission criterion: no wall-time "
                        "estimate is asserted, because none has been measured for this geometry",
    }


# ==========================================================================================
# 11. CANONICAL SERIALISATION, HASHING AND THE EXECUTION AUTHORITY
# ==========================================================================================

def _round(o, nd=_RECORD_DP):
    if isinstance(o, float):
        return round(o, nd)
    if isinstance(o, dict):
        return {k: _round(v, nd) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_round(v, nd) for v in o]
    return o


def canonical_json(obj) -> str:
    """The one serialisation used for every hashed artifact: sorted keys, no insignificant
    whitespace, ASCII-escaped, floats rounded to a frozen precision so a record hash cannot move
    on a platform's last binary digit."""
    return json.dumps(_round(obj), sort_keys=True, separators=(",", ":"), ensure_ascii=True,
                      allow_nan=True)


def record_hash(obj) -> str:
    return hashlib.sha256(canonical_json(obj).encode("utf-8")).hexdigest()


def _sha_file(rel):
    p = REPO_ROOT / rel
    if not p.exists():
        return None
    return hashlib.sha256(p.read_bytes()).hexdigest()


def protocol_config():
    """The frozen machine-readable configuration. Hashing this is how a future stage proves it
    executed the configuration that was reviewed."""
    return {
        "schema_version": SCHEMA_VERSION,
        "program_id": PROGRAM_ID, "tranche_id": TRANCHE_ID,
        "question": QUESTION,
        "base_commit": BASE_COMMIT, "base_tree": BASE_TREE,
        "predecessor": PREDECESSOR,
        "claim_ceiling": list(CLAIM_CEILING),
        "solver": {"kernel": "brewer2026.lb_reference", "backend": "reference",
                   "tau_plus": TAU_PLUS, "tau_cross_check": TAU_CROSS_CHECK, "nu": NU,
                   "rtol": RTOL, "check": CHECK, "min_steps": MIN_STEPS, "max_steps": MAX_STEPS,
                   "convergence_audit_factor": CONVERGENCE_AUDIT_FACTOR,
                   "pressure_definition": "p = rho/3 - g*x, fluid-area averaged",
                   "boundary_mode": "ROUTE_A periodic body force + resolved common plenum",
                   "seed": None, "rng": "none"},
        "forcing": {
            "law": "g(S) = G_REF * (S_REF/S)^3",
            "S_ref": S_REF, "g_ref": G_REF,
            "central": {str(S): forcing_central(S) for S in SCIENTIFIC_RESOLUTIONS},
            "ladder": {str(S): forcing_ladder(S) for S in SCIENTIFIC_RESOLUTIONS},
            "factors": [str(f) for f in FORCING_FACTORS],
            "similarity": {
                "held_invariant": "Re_design = g L^3 / nu^2 with L = h_low * S",
                "value": {str(S): design_reynolds(S) for S in SCIENTIFIC_RESOLUTIONS},
                "diagnostic_mach_scale": {str(S): design_mach_scale(S)
                                          for S in SCIENTIFIC_RESOLUTIONS},
            },
            "reduction_vs_001": {"S2": vf001.G_PRIMARY / forcing_central(2),
                                 "S3": vf001.G_PRIMARY / forcing_central(3)},
        },
        "tolerances": {
            "TOL_MASS_REL": TOL_MASS_REL, "TOL_VOLUME_FLUX_REL": TOL_VOLUME_FLUX_REL,
            "TOL_LINEARITY_REL": TOL_LINEARITY_REL, "TOL_MACH": TOL_MACH,
            "TOL_CONVERGENCE_REL": TOL_CONVERGENCE_REL, "TOL_PLANE_REL": TOL_PLANE_REL,
            "TOL_SWAP_R_REL": TOL_SWAP_R_REL, "TOL_SWAP_XI_REL": TOL_SWAP_XI_REL,
            "TOL_RETURN_PATH_R_REL": TOL_RETURN_PATH_R_REL,
            "TOL_RETURN_PATH_S_ABS": TOL_RETURN_PATH_S_ABS,
            "TOL_NODE_OFFSET_R_REL": TOL_NODE_OFFSET_R_REL,
            "ARTIFACT_BUDGET_R_ABS": ARTIFACT_BUDGET_R_ABS,
            "NUMERICAL_UNCERTAINTY_R_ABS": NUMERICAL_UNCERTAINTY_R_ABS,
            "REACHABLE_SAFETY_MARGIN_FRACTION": REACHABLE_SAFETY_MARGIN_FRACTION,
            "C_FIELD_GATE_ALLOWANCE": C_FIELD_GATE_ALLOWANCE,
            "KAPPA_RES": KAPPA_RES,
        },
        "resolution_consistency": {
            "kind": "FROZEN_RESOLUTION_CONSISTENCY_TEST_NOT_A_CONVERGENCE_ORDER_ESTIMATE",
            "law": CHANNEL_ERR_LAW_PCT, "kappa": KAPPA_RES,
            "provenance": RESOLUTION_CONSISTENCY_PROVENANCE,
            "governing_features": {k: list(v) for k, v in RESOLUTION_GOVERNING_FEATURES.items()},
            "example_tolerances": {
                "%d_%d" % (b["w"], b["kz"]): {
                    q: resolution_consistency_tolerance(q, b)
                    for q in sorted(RESOLUTION_GOVERNING_FEATURES)
                } for b in SCIENTIFIC_BRIDGE_CANDIDATES
            },
        },
        "observables": {
            "inverse_consumes": "PRESSURE_NORMALISED_VOLUME_FLUX",
            "R": "(Q/dP)_open / (Q0/dP0)_blocked with Q from sum(u_x)",
            "s": "q1/(q1+q2) with q from sum(u_x)",
            "conservation_evaluated_on": "DENSITY_WEIGHTED_MASS_FLUX sum(rho*u_x)",
            "axial_plane_fields": list(AXIAL_PLANE_FIELDS),
            "transverse_plane_fields": list(TRANSVERSE_PLANE_FIELDS),
            "sign_convention_axial": SIGN_CONVENTION_AXIAL,
            "sign_convention_transverse": SIGN_CONVENTION_TRANSVERSE,
            "roles": dict(QUANTITY_ROLES),
            "record_decimal_places": _RECORD_DP,
        },
        "boundary_keys": list(BOUNDARY_KEYS),
        "forbidden_boundary_keys": list(FORBIDDEN_BOUNDARY_KEYS),
        "freeze_rule": FREEZE_RULE,
        "xi_window": {"lo": XI_WINDOW_LO, "hi": XI_WINDOW_HI,
                      "provenance": XI_WINDOW_PROVENANCE},
        "validity_controls": [{"name": n, "required": r, "requirement": d}
                              for n, r, d in VALIDITY_CONTROLS],
        "decision_clauses": [dict(c) for c in DECISION_CLAUSES],
        "dispositions": list(DISPOSITIONS),
        "design_blocked_stop": DESIGN_BLOCKED,
        "arm_j": ARM_J,
        "phases": [dict(p) for p in EXECUTION_PHASES],
    }


def fixture_spec_config():
    """The machine-readable geometry specification, including the topology invariants a reviewer
    can check without running anything."""
    out = {
        "schema_version": SCHEMA_VERSION,
        "base_template": dict(BASE),
        "resolutions": {"smoke": S_SMOKE, "coarse": S_COARSE, "fine": S_FINE,
                        "scientific": list(SCIENTIFIC_RESOLUTIONS)},
        "bridge_candidates": [dict(b) for b in BRIDGE_CANDIDATES],
        "scientific_bridge_candidates": [dict(b) for b in SCIENTIFIC_BRIDGE_CANDIDATES],
        "min_feature_vox": MIN_FEATURE_VOX,
        "channel_error_law_pct": CHANNEL_ERR_LAW_PCT,
        "fixture_states": list(FIXTURE_STATES),
        "perturbations": {k: dict(v) for k, v in PERTURBATIONS.items()},
        "coupons": {"axial_length_base": BASE["seg_top_hi"] - BASE["seg_top_lo"] + 1,
                    "bridge": dict(BRIDGE_COUPON)},
        "mirror_transform": "swap_paths(mirror_x(mask, S)) == mask, exact array equality",
        "path_swap_transform": "flip(mask, axis=1) — an index map on the SAME array",
        "geometries": {},
    }
    for S in SCIENTIFIC_RESOLUTIONS:
        for b in SCIENTIFIC_BRIDGE_CANDIDATES:
            key = "S%d_w%d_kz%d" % (S, b["w"], b["kz"])
            entry = {}
            for state, connected in (("blocked", False), ("open", True)):
                mask, meta = build_fixture(S, bridge=b, connected=connected)
                entry[state] = {
                    "mask_sha256": meta["mask_sha256"], "n_fluid": meta["n_fluid"],
                    "mirror_symmetric": is_mirror_symmetric(mask, S),
                    "connectivity": connectivity(mask, meta),
                    "lane_connection": lane_connection(mask, meta),
                    "bridge_topology": bridge_topology(mask, meta),
                }
            entry["delta"] = blocked_open_delta(S, b)
            entry["min_feature"] = minimum_feature_report(S, b)
            entry["planes"] = {k: v for k, v in
                               build_fixture(S, bridge=b, connected=True)[1].items()
                               if k.startswith(("x_", "y_")) or k == "axial_conservation_planes"}
            out["geometries"][key] = entry
    for S in SCIENTIFIC_RESOLUTIONS:
        mask, meta = build_fixture(S, bridge=None)
        out["geometries"]["S%d_reference_blocked" % S] = {
            "mask_sha256": meta["mask_sha256"], "n_fluid": meta["n_fluid"],
            "mirror_symmetric": is_mirror_symmetric(mask, S),
            "connectivity": connectivity(mask, meta),
            "lane_connection": lane_connection(mask, meta),
            "bridge_topology": bridge_topology(mask, meta),
        }
    return out


def preflight_status():
    """The status artifact. Deliberately NOT named result.json or decision.md: nothing here is
    an executed result."""
    return {
        "schema_version": SCHEMA_VERSION,
        "tranche": TRANCHE_ID,
        "status": "PRE_EXECUTION_PREFLIGHT_FROZEN_PENDING_EXACT_HEAD_REVIEW",
        "solves_executed": 0,
        "lb_solver_invoked": False,
        "disposition": None,
        "cross_model_transfer_adjudicated": False,
        "predecessor": PREDECESSOR,
        "claim_ceiling": list(CLAIM_CEILING),
        "protocol_config_sha256": record_hash(protocol_config()),
        "fixture_spec_sha256": record_hash(fixture_spec_config()),
        "execution_matrix_sha256": record_hash(execution_matrix()),
        "input_file_sha256": {f: _sha_file(f) for f in INPUT_FILES},
        "stage_b_authorised": False,
        "paper_4_authorised": False,
        "card_box_5": "OPEN",
        "card_box_6": "closed on its existing mathematical result",
    }


def execution_authority(stage: str, backend: str = "reference"):
    """Everything a future stage must record so its output can never be attributed to a head
    that did not produce it."""
    import platform
    import subprocess

    def git(*a):
        try:
            return subprocess.run(["git", *a], cwd=REPO_ROOT, capture_output=True,
                                  text=True, check=True).stdout.strip()
        except Exception:                                        # pragma: no cover - env limit
            return None

    try:
        import scipy
        scipy_v = scipy.__version__
    except Exception:                                            # pragma: no cover - env limit
        scipy_v = None
    return {
        "stage": stage,
        "tranche": TRANCHE_ID,
        "source_commit": git("rev-parse", "HEAD"),
        "source_tree": git("rev-parse", "HEAD^{tree}"),
        "working_tree_clean": (git("status", "--porcelain") == ""),
        "base_commit": BASE_COMMIT, "base_tree": BASE_TREE,
        "protocol_sha256": _sha_file(PROTOCOL_PATH),
        "geometry_spec_sha256": _sha_file(BUNDLE_REL + "/VIRTUAL_FIXTURE_SPEC.md"),
        "protocol_config_sha256": record_hash(protocol_config()),
        "fixture_spec_sha256": record_hash(fixture_spec_config()),
        "execution_matrix_sha256": record_hash(execution_matrix()),
        "input_file_sha256": {f: _sha_file(f) for f in INPUT_FILES},
        "backend": backend,
        "dependencies": {"python": platform.python_version(), "numpy": np.__version__,
                         "scipy": scipy_v},
        "seed": None,
        "solver_config": {"tau_plus": TAU_PLUS, "nu": NU, "rtol": RTOL, "check": CHECK,
                          "min_steps": MIN_STEPS, "max_steps": MAX_STEPS},
    }


class FreezeMissing(RuntimeError):
    """Raised when a stage that requires the bridge freeze is invoked without a matching one."""


def require_freeze(stage: str, path=None):
    """Fail-closed freeze gate. A primary stage refuses to execute when the freeze artifact is
    absent, malformed, or bound to a different configuration than the one about to run."""
    p = pathlib.Path(path) if path is not None else (REPO_ROOT / FREEZE_REL)
    if not p.exists():
        raise FreezeMissing(
            "stage %r requires the bridge freeze artifact %s, which does not exist. The "
            "candidate and aperture must be frozen — and reviewed — before any primary mirror "
            "output is generated." % (stage, FREEZE_REL))
    try:
        doc = json.loads(p.read_text())
    except Exception as exc:
        raise FreezeMissing("bridge freeze artifact %s is not readable JSON: %s" % (p, exc))
    want = {"protocol_config_sha256": record_hash(protocol_config()),
            "fixture_spec_sha256": record_hash(fixture_spec_config()),
            "execution_matrix_sha256": record_hash(execution_matrix())}
    bad = {k: (doc.get(k), v) for k, v in want.items() if doc.get(k) != v}
    if bad:
        raise FreezeMissing(
            "bridge freeze artifact does not match the execution authority for stage %r: %s. "
            "A freeze binds a specific configuration; re-freezing after review is a new "
            "decision, not a repair." % (stage, sorted(bad)))
    if not doc.get("frozen_bridges"):
        raise FreezeMissing("bridge freeze artifact carries no frozen_bridges")
    return doc


# ==========================================================================================
# 12. GENERATED ARTIFACTS
# ==========================================================================================

_GENERATED = (
    ("protocol.json", protocol_config),
    ("fixture_spec.json", fixture_spec_config),
    ("execution_matrix.json", execution_matrix),
    ("preflight_status.json", preflight_status),
)


GENERATED_DIR = REPO_ROOT / BUNDLE_REL / "generated"


def _gen_path(name):
    return GENERATED_DIR / name


def write():
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for name, fn in _GENERATED:
        p = _gen_path(name)
        p.write_text(canonical_json(fn()) + "\n")
        written.append(str(p.relative_to(REPO_ROOT)))
    return written


def verify():
    """Regenerate and compare. Any drift between the module and the committed artifacts is an
    error, exactly as in the 001 bundle."""
    bad = []
    for name, fn in _GENERATED:
        p = _gen_path(name)
        if not p.exists():
            bad.append((name, "MISSING"))
            continue
        if p.read_text() != canonical_json(fn()) + "\n":
            bad.append((name, "DRIFT"))
    return {"ok": not bad, "problems": bad}


def main(argv=None):                                             # pragma: no cover - thin CLI
    import argparse
    ap = argparse.ArgumentParser(description="RP-D-LC-001b preflight artifacts (no solver runs)")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--verify", action="store_true")
    a = ap.parse_args(argv)
    if a.write:
        for p in write():
            print("wrote", p)
    if a.verify:
        r = verify()
        print("verify:", "OK" if r["ok"] else r["problems"])
        return 0 if r["ok"] else 1
    return 0


if __name__ == "__main__":                                       # pragma: no cover
    raise SystemExit(main())
