"""RP-D-LC-001 — deterministic 3D lateral-coupling virtual fixture (geometry, observables,
boundary-only inference, decision rule and bundle regeneration).

    CROSS_MODEL_NUMERICAL_VERIFICATION
    DETERMINISTIC_SYNTHETIC_GEOMETRY
    NOT_EXPERIMENTAL_VALIDATION
    NOT_REAL_PUCK_INFERENCE
    NOT_A_REGISTRY_STATUS_PROMOTION
    NOT_A_PUBLICATION_RESULT_YET

The scientific question (docs/analysis/rp_d_lc_001/PROTOCOL.md): when the ground truth is
generated by a spatially resolved 3D creeping-flow LB solver rather than by ``model1_two_path``,
does the WP6-LC-IDENT boundary inverse recover the fixture's independently calculated effective
lateral-coupling number Xi?

THIS MODULE IS SPLIT ALONG THE ANTI-CIRCULARITY CONTRACT (PROTOCOL §6) and the split is enforced
by ``tests/test_rp_d_lc_virtual_fixture.py``:

  * the TRUTH pipeline (``field_truth``, ``coupon_truth``) reads prescribed geometry and internal
    LB fields and NEVER calls the WP6 inverse;
  * the BOUNDARY-INFERENCE pipeline (``BoundaryRecord``, ``infer_from_boundary``) accepts ONLY
    the six boundary numbers plus orientation/convergence metadata, and calls the existing
    verified inverse ``screen_wp6_lateral_identifiability.invert`` — never a local copy.

Heavy LB execution lives in ``puckworks/validation/slow/rp_d_lc_001.py`` and writes compact
scalar run records under ``docs/analysis/rp_d_lc_001/runs/``. This module is CI-safe: it never
runs the solver, it re-derives every published number from those committed records.

    python -m puckworks.analysis.rp_d_lc_virtual_fixture --write
    python -m puckworks.analysis.rp_d_lc_virtual_fixture --verify
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import pathlib

import numpy as np

from puckworks.analysis import screen_wp6_lateral_identifiability as wp6

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]

PROGRAM_ID = "RP-D-LATERAL-CROSS-MODEL"
TRANCHE_ID = "RP-D-LC-001"
SCHEMA_VERSION = 1
BASE_COMMIT = "bbbc2b5f44be3bc5f0ee5951985e5f8594bbc6e1"
BUNDLE_REL = "docs/analysis/rp_d_lc_001"
PROTOCOL_PATH = BUNDLE_REL + "/PROTOCOL.md"
RUNS_REL = BUNDLE_REL + "/runs"

INPUT_FILES = (
    PROTOCOL_PATH,
    BUNDLE_REL + "/VIRTUAL_FIXTURE_SPEC.md",
    BUNDLE_REL + "/BOUNDARY_TOPOLOGY_ADJUDICATION.md",
    "puckworks/analysis/rp_d_lc_virtual_fixture.py",
    "puckworks/validation/slow/rp_d_lc_001.py",
    "puckworks/models/brewer2026/lb_reference.py",
    "puckworks/analysis/screen_wp6_lateral_identifiability.py",
    "puckworks/models/lateral_coupling.py",
)

CLAIM_CEILING = (
    "deterministic synthetic geometry",
    "single-phase steady creeping flow",
    "cross-model numerical verification only",
    "no experimental validation",
    "no real coffee morphology",
    "no real-puck Xi",
    "no transverse coffee permeability estimate",
    "no evidence that espresso occupies any Xi regime",
    "no apparatus precision established",
    "no evidence-rung or registry-status promotion",
    "no claim of a validated espresso digital twin",
    "lateral_coupling_feasibility card box 5 remains OPEN",
    "lateral_coupling_feasibility card box 6 remains closed on its existing mathematical result",
    "Paper 4 remains unauthorized",
)

# ==========================================================================================
# 1. FROZEN BASE GEOMETRY TEMPLATE  (PROTOCOL §7, VIRTUAL_FIXTURE_SPEC.md)
# ==========================================================================================
# All lengths are BASE VOXELS. A fixture at resolution S is the base mask replicated S times
# along every axis (np.repeat), so two resolutions are EXACTLY geometrically similar: every base
# voxel becomes an S^3 block and no length ratio changes. Flow is along +x; the box is periodic
# in x (the common plenum wraps, see BOUNDARY_TOPOLOGY_ADJUDICATION.md) and is closed by solid
# no-slip walls on both y and both z faces, so there is no periodic lateral bypass.

BASE = {
    # ---- x: [common plenum] [upstream segment] [transition] [downstream segment] -> wrap ----
    "nx": 56,
    "plenum_half": 4,      # plenum = {x : min(x, nx - x) < plenum_half}  = {53,54,55,0,1,2,3}
    "lane_lo": 4, "lane_hi": 52,       # inclusive; the divider spans exactly this range
    "seg_top_lo": 4, "seg_top_hi": 23,   # 20 base voxels
    "trans_lo": 24, "trans_hi": 32,      # 9 base voxels, both lanes at h_low, hosts the bridge
    "seg_bot_lo": 33, "seg_bot_hi": 52,  # 20 base voxels
    "bridge_centre": 28,
    # ---- y: wall | lane 1 | divider | lane 2 | wall ----
    "ny": 20,
    "lane1_lo": 1, "lane1_hi": 8,
    "div_lo": 9, "div_hi": 10,
    "lane2_lo": 11, "lane2_hi": 18,
    # ---- z: wall | fluid | wall ; conductance contrast is the slot height ----
    "nz": 8,
    "z_lo": 1,
    "h_high": 6, "h_low": 4,
}

#: Predeclared aperture CANDIDATE family (PROTOCOL §9 step 1). kx must be odd so the aperture is
#: centred on the mirror plane x = bridge_centre; kz counts base voxels upward from z_lo.
APERTURE_CANDIDATES = tuple(
    {"kx": kx, "kz": kz} for kx in (1, 3, 5, 7, 9) for kz in (1, 2, 3, 4)
)

#: Scientific resolutions (base-voxel replication factor). S_SMOKE carries no scientific claim.
S_SMOKE = 1
S_COARSE = 2
S_FINE = 3
SCIENTIFIC_RESOLUTIONS = (S_COARSE, S_FINE)

#: Predeclared one-voxel adversarial perturbations (PROTOCOL §10 Arm I). Coordinates are BASE
#: voxels; the perturbation flips exactly ONE lattice voxel inside that base cell at any S.
PERTURBATIONS = {
    # a single solid voxel dropped into lane 1's downstream (low) segment
    "one_voxel_plug": {"kind": "plug", "base": (40, 4, 2)},
    # lane 1's upstream/transition boundary moved by exactly one lattice voxel (a one-voxel-thick
    # slab), which is the smallest perturbation that changes a SEGMENT LENGTH rather than a point
    "one_voxel_slab": {"kind": "slab", "base_x": 23, "lane": 1},
}

#: WP6-LC-IDENT's post-hoc 1 % continuous factor-of-two window. The screen records the crossings
#: at full precision in `sensitivity_envelopes.continuous_window_post_hoc.floors.1pct`; those exact
#: values are copied here unrounded, and the DECISION uses the authorized rounded bounds below.
#: The two differ by <5e-7 in Xi — far below any discretisation effect this tranche can resolve —
#: and the widths are asserted consistent by tests, so no evidence label is restated or moved.
XI_WINDOW_LO_SCREEN_EXACT = 0.241134413907
XI_WINDOW_HI_SCREEN_EXACT = 3.945979529349
XI_WINDOW_LO = 0.241134
XI_WINDOW_HI = 3.945980
#: That window is a POST-HOC diagnostic in the screen and feeds no WP6 decision clause. Here it is
#: used only to select which cases are "transition window" cases, exactly as the brief froze it.
XI_WINDOW_PROVENANCE = ("docs/insights/screens/WP6-LC-IDENT/result.json"
                        " :: sensitivity_envelopes.continuous_window_post_hoc.floors.1pct"
                        " (POST_HOC_DIAGNOSTIC_NOT_IN_DECISION in the source screen)")

# ---- frozen solver configuration (PROTOCOL §5) --------------------------------------------
#: tau_plus = 2.0 (not the kernel default 1.2). TRT with magic Lambda = 3/16 makes the bounce-back
#: wall position viscosity-independent, so this is a pure time-step economy, not a physics change:
#: the canonical plane-channel verification returns k err = +0.05203 % at tau_plus = 1.2, 2.0 AND
#: 3.0 — identical to five significant figures — while the step count falls 8600 -> 4200 -> 2600.
#: Arm A re-runs one full fixture case at tau_plus = 1.2 to confirm the independence holds for the
#: assembled 3D geometry too, not just the analytic channel.
TAU_PLUS = 2.0
TAU_CROSS_CHECK = 1.2
#: g scaled with nu so the lattice velocity (hence the Mach number and the roundoff headroom)
#: matches what tau_plus = 1.2 with g = 1e-5 would have produced: u ~ g/nu.
G_PRIMARY = 2.0e-5
G_LINEARITY = (0.5, 2.0)
RTOL = 1.0e-7
CHECK = 200
MIN_STEPS = 2000
#: Forced-step audit multiplier: one case per resolution is re-run at this multiple of its
#: converged step count and the observables must agree within TOL_CONVERGENCE_REL.
CONVERGENCE_AUDIT_FACTOR = 1.5
TOL_CONVERGENCE_REL = 1.0e-4
MAX_STEPS = 60000
#: Discretisation law measured on the canonical plane channel (Arm A): the slot-permeability
#: error is +50/h^2 percent for h in 3..31 lattice units. This is the quantitative justification
#: for the minimum resolved feature size, and it is why the frozen aperture family excludes
#: kz = 1 (which would be 2 lattice units at S_COARSE, a ~12 % element error).
CHANNEL_ERR_LAW_PCT = "50/h^2"
MIN_FEATURE_VOX = 4

# ---- frozen tolerances (software/discretisation, NOT experimental uncertainties) ----------
TOL_MASS_REL = 1.0e-3        # plane-to-plane axial flux drift, relative to the plane mean
TOL_LINEARITY_REL = 1.0e-4   # conductance drift across x0.5 / x1 / x2 forcing
TOL_MACH = 0.03              # max lattice speed; Ma = u*sqrt(3)
TOL_SWAP_R_REL = 5.0e-3      # |R_swap/R - 1| under the exact path-swap transformation
TOL_SWAP_XI_REL = 5.0e-2     # |Xi_swap/Xi - 1|
TOL_PLANE_REL = 5.0e-3       # outlet-share difference between the two frozen measurement planes
#: ROUTE-A ISOLATION GATE (erratum E1, predeclared before Arm J ran). The programme authorization
#: already established a 0.1 % bound on return-path contribution; these are that bound applied to
#: the two observables the WP6 inverse actually consumes. They are NOT chosen relative to any
#: observed value: 1e-3 on the ratio R, and 5e-4 absolute on the outlet share (0.1 % relative
#: around s = 1/2). Exceeding either in a decision-carrying case means Route A has not been
#: sufficiently isolated, and the disposition is INVALID_EXECUTION — never a relaxed second
#: tolerance and never a silent switch to a pressure-boundary route.
TOL_RETURN_PATH_R_REL = 1.0e-3
TOL_RETURN_PATH_S_ABS = 5.0e-4
#: Node-surface sensitivity is LOAD-BEARING, not a nicety: the return-path result shows the nominal
#: inlet/outlet ports are not perfect equipotentials. Moving the frozen surfaces must not change
#: the classification, and no surface may be chosen because it improves agreement with Xi_hat.
TOL_NODE_OFFSET_R_REL = 5.0e-3
_RECORD_DP = 12


# ==========================================================================================
# 2. GEOMETRY CONSTRUCTION
# ==========================================================================================

def _base_is_plenum(x: int) -> bool:
    return min(x, BASE["nx"] - x) < BASE["plenum_half"]


def _base_lane_height(x: int, lane: int) -> int:
    """Slot height (base voxels, counted up from z_lo) of `lane` at base station `x`."""
    if BASE["seg_top_lo"] <= x <= BASE["seg_top_hi"]:
        return BASE["h_high"] if lane == 1 else BASE["h_low"]
    if BASE["seg_bot_lo"] <= x <= BASE["seg_bot_hi"]:
        return BASE["h_low"] if lane == 1 else BASE["h_high"]
    return BASE["h_low"]                      # the transition band: both lanes low


def _base_aperture_x(kx: int):
    if kx % 2 != 1:
        raise ValueError("aperture kx must be odd so it is centred on the mirror plane, got %r" % kx)
    half = (kx - 1) // 2
    lo, hi = BASE["bridge_centre"] - half, BASE["bridge_centre"] + half
    if lo < BASE["trans_lo"] or hi > BASE["trans_hi"]:
        raise ValueError("aperture kx=%r does not fit the transition band" % kx)
    return lo, hi


def base_mask(aperture=None, variant="mirror"):
    """The frozen base template as a boolean SOLID mask of shape (nx, ny, nz).

    ``aperture`` None -> the blocked fixture (the divider is continuous). A dict ``{kx, kz}``
    opens the lateral bridge and changes NOTHING else. ``variant`` is 'mirror' (lane 2 carries
    the reversed segment order) or 'identical' (both lanes ordered like lane 1 — the negative
    control, which is structurally degenerate: X = g1t*g2b - g2t*g1b = 0).
    """
    if variant not in ("mirror", "identical"):
        raise ValueError("variant must be 'mirror' or 'identical', got %r" % (variant,))
    nx, ny, nz = BASE["nx"], BASE["ny"], BASE["nz"]
    solid = np.ones((nx, ny, nz), dtype=bool)
    z_lo, z_hi_full = BASE["z_lo"], BASE["z_lo"] + BASE["h_high"] - 1
    for x in range(nx):
        if _base_is_plenum(x):
            solid[x, 1:ny - 1, z_lo:z_hi_full + 1] = False       # one common, full-section node
            continue
        for lane, (ylo, yhi) in ((1, (BASE["lane1_lo"], BASE["lane1_hi"])),
                                 (2, (BASE["lane2_lo"], BASE["lane2_hi"]))):
            h = _base_lane_height(x, 1 if variant == "identical" else lane)
            solid[x, ylo:yhi + 1, z_lo:z_lo + h] = False
    if aperture is not None:
        ax_lo, ax_hi = _base_aperture_x(int(aperture["kx"]))
        kz = int(aperture["kz"])
        if not 1 <= kz <= BASE["h_low"]:
            raise ValueError("aperture kz must lie in 1..%d, got %r" % (BASE["h_low"], kz))
        solid[ax_lo:ax_hi + 1, BASE["div_lo"]:BASE["div_hi"] + 1, z_lo:z_lo + kz] = False
    return solid


def scale(mask_b, S: int):
    """Replicate a base mask S times on every axis — exact geometric similarity."""
    if not isinstance(S, int) or isinstance(S, bool) or S < 1:
        raise ValueError("S must be a positive int, got %r" % (S,))
    return np.repeat(np.repeat(np.repeat(mask_b, S, axis=0), S, axis=1), S, axis=2)


def mirror_x(mask, S: int):
    """The exact voxel-index x-reflection about the fixture's mirror planes (x = 0 and
    x = bridge_centre). Cellwise: base b -> (nx - b) mod nx, with sub-cell order reversed."""
    return np.roll(np.flip(mask, axis=0), S, axis=0)


def swap_paths(mask):
    """The exact path-swap: reflect y about the divider mid-plane, exchanging lane 1 and lane 2.
    This is an index transformation of the SAME array — the swapped fixture is never rebuilt."""
    return np.flip(mask, axis=1)


def _apply_perturbation(mask, S: int, name: str):
    """Apply a predeclared one-voxel adversarial perturbation (Arm I). Returns a NEW mask."""
    spec = PERTURBATIONS[name]
    out = mask.copy()
    if spec["kind"] == "plug":
        bx, by, bz = spec["base"]
        out[bx * S, by * S, bz * S] = True                     # exactly one lattice voxel
    elif spec["kind"] == "slab":
        # move lane 1's upstream-segment end plane by one lattice voxel: the LAST lattice plane
        # of base cell `base_x` reverts from the high slot to the low slot, in lane 1 only.
        x = (spec["base_x"] + 1) * S - 1
        ylo, yhi = BASE["lane1_lo"] * S, (BASE["lane1_hi"] + 1) * S - 1
        zlo = (BASE["z_lo"] + BASE["h_low"]) * S
        zhi = (BASE["z_lo"] + BASE["h_high"]) * S - 1
        out[x, ylo:yhi + 1, zlo:zhi + 1] = True
    else:                                                       # pragma: no cover - frozen set
        raise ValueError("unknown perturbation kind %r" % (spec["kind"],))
    return out


def build_fixture(S: int, aperture=None, variant="mirror", swapped=False, perturbation=None):
    """The full virtual fixture at resolution S, with its frozen region and plane indices."""
    mask = scale(base_mask(aperture=aperture, variant=variant), S)
    if swapped:
        mask = swap_paths(mask)
    if perturbation is not None:
        mask = _apply_perturbation(mask, S, perturbation)
    return mask, fixture_meta(S, aperture=aperture, variant=variant, swapped=swapped,
                              perturbation=perturbation, mask=mask)


def fixture_meta(S, aperture=None, variant="mirror", swapped=False, perturbation=None, mask=None):
    """Every frozen index the observable calculation is allowed to use. Nothing here is fitted."""
    nx, ny, nz = BASE["nx"] * S, BASE["ny"] * S, BASE["nz"] * S
    lane1 = (BASE["lane1_lo"] * S, (BASE["lane1_hi"] + 1) * S)      # [lo, hi) voxel slices
    lane2 = (BASE["lane2_lo"] * S, (BASE["lane2_hi"] + 1) * S)
    if swapped:                       # the swap relabels nothing: lane 1 is still y-low
        pass
    meta = {
        "S": S, "variant": variant, "swapped": bool(swapped),
        "perturbation": perturbation, "aperture": None if aperture is None else dict(aperture),
        "shape": (nx, ny, nz),
        "lane1_y": lane1, "lane2_y": lane2,
        "divider_y": (BASE["div_lo"] * S, (BASE["div_hi"] + 1) * S),
        "lane_x": (BASE["lane_lo"] * S, (BASE["lane_hi"] + 1) * S),
        # ---- node surfaces: the plenum planes immediately abutting the lane ends. These are
        # the only planes where the cross-section is ONE connected common region, i.e. a genuine
        # network node (PROTOCOL §8.2).
        "x_node_in": BASE["lane_lo"] * S - 1,
        "x_node_out": (BASE["lane_hi"] + 1) * S,
        # frozen node-surface offsets for the §8.2 sensitivity report (further into the plenum)
        "node_offsets": (1, 2),
        # ---- outlet-flux measurement planes, both inside the downstream segment ----
        "x_meas_a": (BASE["lane_hi"] + 1) * S - 1,          # immediately before the plenum
        "x_meas_b": 48 * S,                                  # a second frozen plane, 5 base up
        "x_meas_in": BASE["lane_lo"] * S,                    # lane inlet plane (conservation)
        # ---- bridge instrumentation ----
        "y_bridge": (BASE["div_lo"] + 1) * S,                # mid-plane of the divider slab
        "y_face1": BASE["div_lo"] * S - 1,                   # last lane-1 voxel before the bridge
        "y_face2": (BASE["div_hi"] + 1) * S,                 # first lane-2 voxel after it
    }
    if aperture is not None:
        ax_lo, ax_hi = _base_aperture_x(int(aperture["kx"]))
        meta["aperture_x"] = (ax_lo * S, (ax_hi + 1) * S)
        meta["aperture_z"] = (BASE["z_lo"] * S, (BASE["z_lo"] + int(aperture["kz"])) * S)
    else:                       # blocked: the bridge footprint the SAME aperture would occupy
        meta["aperture_x"] = None
        meta["aperture_z"] = None
    if mask is not None:
        meta["mask_sha256"] = mask_hash(mask)
        meta["n_solid"] = int(mask.sum())
        meta["n_fluid"] = int((~mask).sum())
    return meta


def mask_hash(mask) -> str:
    """SHA-256 of the packed boolean mask plus its shape — the geometry's identity."""
    h = hashlib.sha256()
    h.update(("%d,%d,%d|" % mask.shape).encode())
    h.update(np.packbits(np.ascontiguousarray(mask, dtype=bool)).tobytes())
    return h.hexdigest()


def is_mirror_symmetric(mask, S: int) -> bool:
    """Exact voxel-index mirror test: swap_paths(mirror_x(mask)) == mask."""
    return bool(np.array_equal(swap_paths(mirror_x(mask, S)), mask))


def connectivity(mask, meta):
    """Connected-component audit of the fluid space: the required flow regions must form ONE
    component under x-periodic / y,z-walled connectivity, and no fluid may touch a y or z face."""
    from scipy import ndimage
    fluid = ~mask
    nx = mask.shape[0]
    # x-periodic labelling: label the doubled array then fold, so wrap-connections are seen.
    lab, n = ndimage.label(np.concatenate([fluid, fluid], axis=0))
    a, b = lab[:nx], lab[nx:]
    merge = {}
    for u, v in set(zip(a[fluid].ravel().tolist(), b[fluid].ravel().tolist())):
        merge.setdefault(u, set()).add(v)
    # union-find over the two copies
    parent = {}

    def find(k):
        parent.setdefault(k, k)
        while parent[k] != k:
            parent[k] = parent[parent[k]]
            k = parent[k]
        return k

    def union(p, q):
        rp, rq = find(p), find(q)
        if rp != rq:
            parent[rp] = rq

    for u, vs in merge.items():
        for v in vs:
            union(u, v)
    comps = {find(int(v)) for v in np.unique(a[fluid])}
    y_face = bool(fluid[:, 0, :].any() or fluid[:, -1, :].any())
    z_face = bool(fluid[:, :, 0].any() or fluid[:, :, -1].any())
    return {"n_components_raw": int(n), "n_components_periodic": len(comps),
            "fluid_on_y_face": y_face, "fluid_on_z_face": z_face,
            "single_connected": len(comps) == 1,
            "no_lateral_bypass": not (y_face or z_face)}


# ==========================================================================================
# 3. COUPON GEOMETRY  (PROTOCOL §8.1)
# ==========================================================================================

def build_axial_coupon(S: int, level: str, orientation: str = "x"):
    """A straight duct coupon reproducing one axial segment: same slot height, same lane width,
    same wall treatment (a 1-base-voxel outer wall on one side, the 2-base-voxel divider on the
    other), same length, x-periodic. ``orientation`` 'y' transposes the duct axis onto the y
    lattice direction and back, so the SAME duct is calibrated in two lattice orientations
    (PROTOCOL §11.6 anisotropy check) — the solver still drives +x."""
    if level not in ("high", "low"):
        raise ValueError("level must be 'high' or 'low', got %r" % (level,))
    if orientation not in ("x", "y"):
        raise ValueError("orientation must be 'x' or 'y', got %r" % (orientation,))
    h = BASE["h_high"] if level == "high" else BASE["h_low"]
    lx = BASE["seg_top_hi"] - BASE["seg_top_lo"] + 1               # 20 base voxels
    ny_b = BASE["div_hi"] + 1                                      # wall + lane 1 + divider
    solid_b = np.ones((lx, ny_b, BASE["nz"]), dtype=bool)
    solid_b[:, BASE["lane1_lo"]:BASE["lane1_hi"] + 1, BASE["z_lo"]:BASE["z_lo"] + h] = False
    mask = scale(solid_b, S)
    if orientation == "y":
        # Rotate the CROSS-SECTION, not the flow axis: the duct axis must stay along +x because
        # that is the only direction the kernel drives. Swapping axes 1 and 2 puts the slot's
        # narrow dimension along y instead of z, which is exactly the lattice-anisotropy test
        # (same duct, same length, same wall treatment, different lattice orientation).
        mask = np.ascontiguousarray(np.swapaxes(mask, 1, 2))
    meta = {"S": S, "kind": "axial_coupon", "level": level, "orientation": orientation,
            "length_vox": lx * S, "shape": tuple(int(v) for v in mask.shape),
            "mask_sha256": mask_hash(mask), "n_fluid": int((~mask).sum())}
    return mask, meta


#: Bridge-coupon plenum depth on each side of the divider, in base voxels, and the transverse
#: span it is embedded in. Frozen; NOT tuned against any assembled-fixture output.
BRIDGE_COUPON = {"plenum": 6, "span": 13}


def build_bridge_coupon(S: int, kx: int, kz: int):
    """AXIS-ROTATED bridge coupon: the divider slab and its aperture, rebuilt so the transverse
    (bridge) axis lies along the solver's +x lattice direction. The existing x-directed kernel
    therefore measures the transverse conductance directly, with no invented anisotropy
    correction. Plena of the transition-band slot height sit on both sides and join through the
    x wrap, exactly as the full fixture's common node does."""
    ax_lo, ax_hi = _base_aperture_x(int(kx))                       # validate against the family
    kz = int(kz)
    if not 1 <= kz <= BASE["h_low"]:
        raise ValueError("aperture kz must lie in 1..%d, got %r" % (BASE["h_low"], kz))
    p, span = BRIDGE_COUPON["plenum"], BRIDGE_COUPON["span"]
    w = BASE["div_hi"] - BASE["div_lo"] + 1                        # divider thickness = 2 base
    lx = 2 * p + w
    solid_b = np.ones((lx, span, BASE["nz"]), dtype=bool)
    # plena: the transition-band cross-section (slot height h_low), walled on both span faces
    solid_b[:p, 1:span - 1, BASE["z_lo"]:BASE["z_lo"] + BASE["h_low"]] = False
    solid_b[p + w:, 1:span - 1, BASE["z_lo"]:BASE["z_lo"] + BASE["h_low"]] = False
    # the aperture through the divider slab, centred on the span
    c = span // 2
    half = (int(kx) - 1) // 2
    solid_b[p:p + w, c - half:c + half + 1, BASE["z_lo"]:BASE["z_lo"] + kz] = False
    mask = scale(solid_b, S)
    meta = {"S": S, "kind": "bridge_coupon", "kx": int(kx), "kz": kz,
            "wall_thickness_vox": w * S, "plenum_vox": p * S,
            "shape": tuple(int(v) for v in mask.shape), "mask_sha256": mask_hash(mask),
            "n_fluid": int((~mask).sum()),
            "x_node_in": p * S - 1, "x_node_out": (p + w) * S,
            "aperture_x_extent_vox": int(kx) * S, "aperture_z_extent_vox": kz * S}
    return mask, meta


# ==========================================================================================
# 4. FIELD READERS — the TRUTH pipeline. NEVER calls the WP6 inverse.
# ==========================================================================================

def plane_flux(ux, mask, x, y_slice=None):
    """Axial volumetric flux through the lattice plane at index ``x`` (lattice units).
    ``ux`` must be the solver's returned ux (which already carries the +g/2 correction);
    solid nodes are masked here because the kernel returns g/2 there, not 0."""
    u = np.where(mask[x], 0.0, ux[x])
    if y_slice is not None:
        u = u[y_slice[0]:y_slice[1]]
    return float(u.sum())


def plane_pressure(rho, mask, x, g, y_slice=None):
    """Fluid-area-averaged PHYSICAL pressure on the lattice plane at ``x``.

    In the periodic body-force formulation the lattice density carries only the periodic part of
    the pressure; the physical field is  p = rho/3 - g*x  (see BOUNDARY_TOPOLOGY_ADJUDICATION.md
    §2). Returns (mean, std, n_fluid) so pressure NONUNIFORMITY over a nominal node surface is
    always reported alongside the mean, never hidden inside it."""
    fl = ~mask[x]
    if y_slice is not None:
        fl = fl.copy()
        fl[:y_slice[0]] = False
        fl[y_slice[1]:] = False
    vals = rho[x][fl] / 3.0 - g * x
    return float(vals.mean()), float(vals.std()), int(fl.sum())


def boundary_record_from_fields(res_open, res_blocked, mask_open, mask_blocked, meta, g):
    """Form the SIX boundary numbers (and only those) from the two solver results.

    Everything read here is available at the boundary of a physical fixture: the two node-plane
    pressures, the total flow, and the two separately measured lane outlet fluxes. No internal
    pressure, no bridge flux, no calibrated conductance, no prescribed aperture size."""
    out = {}
    for tag, res, mask in (("open", res_open, mask_open), ("blocked", res_blocked, mask_blocked)):
        ux, rho = res["ux"], res["rho"]
        xin, xout = meta["x_node_in"], meta["x_node_out"]
        p_in, p_in_sd, n_in = plane_pressure(rho, mask, xin, g)
        p_out, p_out_sd, n_out = plane_pressure(rho, mask, xout, g)
        q1 = plane_flux(ux, mask, meta["x_meas_a"], meta["lane1_y"])
        q2 = plane_flux(ux, mask, meta["x_meas_a"], meta["lane2_y"])
        q1b = plane_flux(ux, mask, meta["x_meas_b"], meta["lane1_y"])
        q2b = plane_flux(ux, mask, meta["x_meas_b"], meta["lane2_y"])
        out[tag] = {"dP": p_in - p_out, "Q": q1 + q2, "q1": q1, "q2": q2,
                    "q1_plane_b": q1b, "q2_plane_b": q2b,
                    "p_node_in": p_in, "p_node_out": p_out,
                    "p_node_in_sd": p_in_sd, "p_node_out_sd": p_out_sd,
                    "n_node_in": n_in, "n_node_out": n_out,
                    "steps": int(res["steps"]), "converged": bool(res["steps"] < MAX_STEPS)}
    return out


def field_truth(res_open, res_blocked, mask_open, mask_blocked, meta, g):
    """The INDEPENDENT in-situ coarse-grained truth (PROTOCOL §8.2). Reads internal pressure and
    velocity fields and the prescribed geometry only. It NEVER calls the WP6 inverse, and its
    output is joined to the inference record only after inference has been recorded."""
    if meta["aperture_x"] is None:
        raise ValueError("field_truth needs the OPEN fixture's aperture footprint")
    ax, az = meta["aperture_x"], meta["aperture_z"]
    xin, xout = meta["x_node_in"], meta["x_node_out"]

    def node_pressures(res, mask):
        rho = res["rho"]
        pin = plane_pressure(rho, mask, xin, g)
        pout = plane_pressure(rho, mask, xout, g)
        return pin, pout

    def face_pressure(res, mask, y):
        """Area-averaged physical pressure on the aperture footprint at lattice row ``y``."""
        rho, vals = res["rho"], []
        for x in range(ax[0], ax[1]):
            fl = ~mask[x, y, az[0]:az[1]]
            if fl.any():
                vals.append(rho[x, y, az[0]:az[1]][fl] / 3.0 - g * x)
        if not vals:
            return float("nan"), float("nan"), 0
        v = np.concatenate(vals)
        return float(v.mean()), float(v.std()), int(v.size)

    # ---- blocked fixture: the four axial segment conductances, coarse-grained in situ --------
    (pin_b, pin_b_sd, _), (pout_b, pout_b_sd, _) = node_pressures(res_blocked, mask_blocked)
    q1_0 = plane_flux(res_blocked["ux"], mask_blocked, meta["x_meas_a"], meta["lane1_y"])
    q2_0 = plane_flux(res_blocked["ux"], mask_blocked, meta["x_meas_a"], meta["lane2_y"])
    p1_0, p1_0_sd, p1_0_n = face_pressure(res_blocked, mask_blocked, meta["y_face1"])
    p2_0, p2_0_sd, p2_0_n = face_pressure(res_blocked, mask_blocked, meta["y_face2"])
    g1_top = q1_0 / (pin_b - p1_0)
    g1_bot = q1_0 / (p1_0 - pout_b)
    g2_top = q2_0 / (pin_b - p2_0)
    g2_bot = q2_0 / (p2_0 - pout_b)
    A1, A2 = g1_top + g1_bot, g2_top + g2_bot
    c_field = (g1_top - g1_bot) / A1
    c_field_lane2 = (g2_bot - g2_top) / A2
    X = g1_top * g2_bot - g2_top * g1_bot

    # ---- open fixture: the signed lateral flux and the local pressure gap that drives it -----
    uy = res_open["uy"]
    yb = meta["y_bridge"]
    q_lat = float(np.where(mask_open[:, yb, :], 0.0, uy[:, yb, :])[ax[0]:ax[1], az[0]:az[1]].sum())
    yb2 = yb - 1
    q_lat_alt = float(
        np.where(mask_open[:, yb2, :], 0.0, uy[:, yb2, :])[ax[0]:ax[1], az[0]:az[1]].sum())
    p1, p1_sd, p1_n = face_pressure(res_open, mask_open, meta["y_face1"])
    p2, p2_sd, p2_n = face_pressure(res_open, mask_open, meta["y_face2"])
    gap = p1 - p2
    ok = bool(np.isfinite(gap) and gap != 0.0 and np.sign(gap) == np.sign(q_lat) and q_lat != 0.0)
    G_lat = (q_lat / gap) if ok else float("nan")
    Xi_field = G_lat * (1.0 / A1 + 1.0 / A2) if ok else float("nan")

    return {
        "g1_top": g1_top, "g1_bot": g1_bot, "g2_top": g2_top, "g2_bot": g2_bot,
        "A1_field": A1, "A2_field": A2, "c_field": c_field, "c_field_lane2": c_field_lane2,
        "c_field_lane_asymmetry": c_field - c_field_lane2,
        "X_cross_product": X, "X_normalised": X / (A1 * A2),
        "q1_blocked": q1_0, "q2_blocked": q2_0,
        "blocked_share": q1_0 / (q1_0 + q2_0),
        "p_mid1_blocked": p1_0, "p_mid2_blocked": p2_0,
        "p_mid_gap_blocked": p1_0 - p2_0,
        "q_lat": q_lat, "q_lat_alt_plane": q_lat_alt,
        "q_lat_plane_rel_diff": (abs(q_lat_alt - q_lat) / abs(q_lat)) if q_lat else float("nan"),
        "p_face1_open": p1, "p_face2_open": p2, "p_face_gap_open": gap,
        "G_lat_field": G_lat, "Xi_field": Xi_field,
        "gap_sign_consistent": ok,
        "nonuniformity": {
            "node_in_sd_over_dP": pin_b_sd / (pin_b - pout_b),
            "node_out_sd_over_dP": pout_b_sd / (pin_b - pout_b),
            "face1_sd_over_gap": (p1_sd / abs(gap)) if ok else float("nan"),
            "face2_sd_over_gap": (p2_sd / abs(gap)) if ok else float("nan"),
            "face1_sd_blocked_over_gap": (p1_0_sd / abs(p1_0 - p2_0)) if p1_0 != p2_0 else float("nan"),
            "n_face1": p1_n, "n_face2": p2_n, "n_face1_blocked": p1_0_n, "n_face2_blocked": p2_0_n,
        },
    }


def coupon_truth(a_coupon, b_coupon, g_bridge_coupon):
    """The SEPARATE composability prediction (PROTOCOL §8.1): what the two-node network says the
    assembled mirror fixture should be, using only independently calibrated pieces."""
    c = (a_coupon - b_coupon) / (a_coupon + b_coupon)
    A1 = A2 = a_coupon + b_coupon
    return {"a_coupon": a_coupon, "b_coupon": b_coupon, "c_coupon": c,
            "A1_coupon": A1, "A2_coupon": A2, "G_bridge_coupon": g_bridge_coupon,
            "Xi_coupon": g_bridge_coupon * (1.0 / A1 + 1.0 / A2)}


# ==========================================================================================
# 5. BOUNDARY-ONLY INFERENCE — the pipeline under test
# ==========================================================================================

#: The ONLY keys ``infer_from_boundary`` will accept. Anything else is a contract violation and
#: raises: no internal pressure, no bridge flux, no calibrated G_lat, no aperture size, no
#: c_truth, no Xi_truth, no fitted correction may reach the inverse (PROTOCOL §6).
BOUNDARY_KEYS = ("Q0", "dP0", "q1", "q2", "dP", "orientation", "converged")


def infer_from_boundary(record):
    """Blind boundary inversion. Accepts ONLY ``BOUNDARY_KEYS`` and delegates to the existing
    verified WP6 inverse — this module contains no inverse of its own.

        R = (Q/dP)_open / (Q0/dP0)_blocked        s = q1 / (q1 + q2)
    """
    keys = tuple(sorted(record))
    if keys != tuple(sorted(BOUNDARY_KEYS)):
        raise ValueError(
            "infer_from_boundary accepts exactly %r; got %r — the anti-circularity contract "
            "(PROTOCOL §6) forbids passing any truth-side quantity to the inverse."
            % (sorted(BOUNDARY_KEYS), list(keys)))
    q1, q2 = float(record["q1"]), float(record["q2"])
    Q = q1 + q2
    R = (Q / float(record["dP"])) / (float(record["Q0"]) / float(record["dP0"]))
    s = q1 / Q
    out = dict(wp6.invert(R, s))
    out["R"] = R
    out["s"] = s
    out["dP_ratio_open_over_blocked"] = float(record["dP"]) / float(record["dP0"])
    out["orientation"] = record["orientation"]
    out["converged"] = bool(record["converged"])
    return out


def network_prediction(g1_top, g1_bot, g2_top, g2_bot, G_lat):
    """Forward two-node network prediction of (R, s) from calibrated elements — used ONLY in
    Arm F, after inference is recorded, to separate inverse failure from reduction failure."""
    from puckworks.models import lateral_coupling as lc
    P = 1.0
    op = lc.model1_two_path(P, g1_top, g1_bot, g2_top, g2_bot, G_lat)
    bl = lc.model1_two_path(P, g1_top, g1_bot, g2_top, g2_bot, 0.0)
    return {"R": op["Q"] / bl["Q"], "s": op["q1"] / op["Q"]}


# ==========================================================================================
# 6. DECISION RULE  (PROTOCOL §12 — frozen before execution)
# ==========================================================================================

def _clause(name, ok, detail):
    return {"clause": name, "pass": bool(ok), "detail": detail}


def decide(runs):
    """Evaluate the frozen disposition rule against the joined records. Returns
    (disposition, clauses). ``runs`` is the compact record structure written by the slow driver
    and re-derived by ``assemble``."""
    cl = []
    ctrl = runs["controls"]

    # Execution validity. `frozen_C_linearity_control` is deliberately ABSENT from the required
    # set and present in the reported set: it is a preserved historical failure, and the question
    # it was meant to answer is now answered by `componentwise_creeping_flow_control` (can the
    # INTERNAL fields serve as truth?) and `boundary_inference_forcing_stability` (are the
    # BOUNDARY observables stable?). A stable R may never stand in for the componentwise test.
    REQUIRED = ("convergence", "low_mach_linearity", "componentwise_creeping_flow_control",
                "boundary_inference_forcing_stability", "mass_conservation", "topology",
                "coarse_graining_surface_stability", "plane_invariance", "grid_refinement")
    REPORTED = REQUIRED + ("frozen_C_linearity_control", "backend_cross_check")
    valid = all(ctrl[k]["pass"] for k in REQUIRED)
    # A control that FAILED ON EVIDENCE and one that was NOT EVALUATED are different things, and
    # the record must not conflate them: an unevaluated downstream control is a CONSEQUENCE of an
    # upstream failure, never itself the reason execution was judged invalid.
    def _st(k):
        return ctrl[k].get("status", "EVALUATED")

    failed_on_evidence = [k for k in REQUIRED
                          if not ctrl[k]["pass"] and _st(k) == "EVALUATED"]
    not_evaluated = [k for k in REQUIRED if _st(k) != "EVALUATED"]
    cl.append(_clause("1_execution_valid", valid,
                      {"required": {k: {"pass": ctrl[k]["pass"], "status": _st(k)}
                                    for k in REQUIRED},
                       "reported_not_required": {
                           k: {"pass": ctrl[k]["pass"], "status": _st(k)}
                           for k in REPORTED if k not in REQUIRED},
                       "failed_on_evidence": failed_on_evidence,
                       "not_evaluated_downstream": not_evaluated,
                       "primary_cause": failed_on_evidence[0] if failed_on_evidence else None,
                       "note": ("componentwise_creeping_flow_control is load-bearing: if the "
                                "internal components are not proportional to the forcing within "
                                "1e-4, a stable R cannot rescue the execution and the disposition "
                                "is INVALID_EXECUTION.")}))

    primary = [r for r in runs["cases"]
               if r["role"] == "primary" and r["S"] == max(SCIENTIFIC_RESOLUTIONS)]
    if not primary:
        primary = [r for r in runs["cases"] if r["role"] == "primary"]
    # Xi_field is None when the truth was unavailable (zero or sign-inconsistent bridge pressure
    # gap, e.g. the identical-path control). Such a case is NEVER silently treated as zero, and it
    # cannot enter the window set.
    def _usable(x):
        """None (rounded artifact) and NaN (raw record) both mean 'truth unavailable'."""
        return isinstance(x, (int, float)) and not isinstance(x, bool) and math.isfinite(x)

    def _in_window(r):
        x = r["truth"].get("Xi_field")
        return _usable(x) and XI_WINDOW_LO <= x <= XI_WINDOW_HI

    window = [r for r in runs["cases"] if r["role"] == "primary" and _in_window(r)]
    unavailable = [{"S": r["S"], "aperture": r["aperture"]} for r in runs["cases"]
                   if r["role"] == "primary" and not _usable(r["truth"].get("Xi_field"))]
    per_res = {}
    for S in SCIENTIFIC_RESOLUTIONS:
        per_res[S] = [r for r in window if r["S"] == S]
    n_window_min = min((len(v) for v in per_res.values()), default=0)
    cl.append(_clause("2_three_window_cases", n_window_min >= 3,
                      {"per_resolution_counts": {str(k): len(v) for k, v in per_res.items()},
                       "window": [XI_WINDOW_LO, XI_WINDOW_HI],
                       "primary_cases_with_unavailable_Xi_field": unavailable}))

    ratios = [(r["S"], r["aperture"], r["inference"]["status"],
               (r["inference"]["Xi_hat"] / r["truth"]["Xi_field"])
               if r["inference"]["Xi_hat"] else None) for r in window]
    ok3 = bool(window) and all(
        st == "ok" and ra is not None and 0.5 <= ra <= 2.0 for _, _, st, ra in ratios)
    cl.append(_clause("3_factor_two_recovery", ok3, {"ratios": ratios}))

    cdiffs = [(r["S"], r["aperture"], r["inference"]["c_hat"], r["truth"]["c_field"])
              for r in window]
    ok4 = bool(window) and all(
        ch is not None and (ch > 0) == (cf > 0) and abs(ch - cf) <= 0.10
        for _, _, ch, cf in cdiffs)
    cl.append(_clause("4_contrast_sign_and_tolerance", ok4, {"pairs": cdiffs}))

    mono = {}
    for S in SCIENTIFIC_RESOLUTIONS:
        pts = sorted(((r["truth"]["Xi_field"], r["inference"]["Xi_hat"])
                      for r in runs["cases"] if r["role"] == "primary" and r["S"] == S
                      and _usable(r["inference"]["Xi_hat"])
                      and _usable(r["truth"].get("Xi_field"))), key=lambda t: t[0])
        mono[str(S)] = all(b[1] > a[1] for a, b in zip(pts, pts[1:])) if len(pts) > 1 else False
    cl.append(_clause("5_strict_monotonicity", all(mono.values()) and bool(mono), mono))

    swaps = runs["path_swap"]
    ok6 = bool(swaps) and all(s["signature_ok"] for s in swaps)
    cl.append(_clause("6_path_swap_signature", ok6,
                      [{"S": s["S"], "aperture": s["aperture"], **{k: s[k] for k in
                        ("share_sign_reversed", "c_sign_reversed", "R_preserved",
                         "Xi_field_preserved", "Xi_hat_preserved")}} for s in swaps]))

    cls_by_res = runs["grid_refinement"]["classification_by_resolution"]
    ok7 = len(set(cls_by_res.values())) == 1 and len(cls_by_res) >= 2
    cl.append(_clause("7_resolution_stable_classification", ok7, cls_by_res))

    passes = {c["clause"]: c["pass"] for c in cl}
    if not passes["1_execution_valid"]:
        return "INVALID_EXECUTION", cl
    if not passes["2_three_window_cases"]:
        return "DESIGN_MISSED_TARGET", cl
    if all(passes.values()):
        return "CROSS_MODEL_RECOVERY", cl
    mechanism = (passes["5_strict_monotonicity"] and passes["6_path_swap_signature"]
                 and runs["mechanism"]["bridge_flux_consistent"]
                 and runs["mechanism"]["R_direction_consistent"])
    return ("MECHANISM_ONLY" if mechanism else "NO_CROSS_MODEL_TRANSFER"), cl


# ==========================================================================================
# 7. BUNDLE ASSEMBLY / WRITE / VERIFY
# ==========================================================================================

def _sha(rel):
    p = REPO_ROOT / rel
    return hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None


def _round(o, nd=_RECORD_DP):
    if isinstance(o, float):
        if math.isnan(o):
            return None
        if math.isinf(o):
            return "inf" if o > 0 else "-inf"
        return round(o, nd)
    if isinstance(o, dict):
        return {k: _round(v, nd) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_round(v, nd) for v in o]
    return o


def load_runs():
    """Load the committed compact run record produced by the slow driver."""
    p = REPO_ROOT / RUNS_REL / "run_record.json"
    if not p.exists():
        raise FileNotFoundError(
            "no run record at %s — execute the heavy driver first:\n"
            "  python -m puckworks.validation.slow.rp_d_lc_001 --backend reference "
            "--mode primary --output <gitignored-run-dir>" % p)
    return json.loads(p.read_text())


def assemble():
    runs = load_runs()
    disposition, clauses = decide(runs)
    doc = {
        "schema_version": SCHEMA_VERSION,
        "program_id": PROGRAM_ID,
        "tranche_id": TRANCHE_ID,
        "source_commit": BASE_COMMIT,
        "source_tree": runs["source_tree"],
        "protocol_sha256": _sha(PROTOCOL_PATH),
        "input_sha256": {rel: _sha(rel) for rel in INPUT_FILES},
        "environment": runs["environment"],
        "solver": runs["solver"],
        "boundary_mode": runs["boundary_mode"],
        "resolutions": list(SCIENTIFIC_RESOLUTIONS),
        "aperture_candidates": [dict(a) for a in APERTURE_CANDIDATES],
        "aperture_freeze": runs["aperture_freeze"],
        "geometry": runs["geometry"],
        "coupons": runs["coupons"],
        "blocked": runs["blocked"],
        "cases": runs["cases"],
        "path_swap": runs["path_swap"],
        "identical_path_control": runs["identical_path_control"],
        "asymmetry": runs["asymmetry"],
        "grid_refinement": runs["grid_refinement"],
        "controls": runs["controls"],
        "mechanism": runs["mechanism"],
        "arm_a_solver_verification": runs["arm_a"],
        "disposition": disposition,
        "decision_clauses": clauses,
        # Under a failed execution-validity clause every recovery number in this bundle is
        # DIAGNOSTIC ONLY. It may inform a redesign; it may not be quoted as recovery,
        # mechanism-only transfer, or a weak quantitative success at ANY strength.
        "evidence_use": ("DIAGNOSTIC_ONLY_INVALID_EXECUTION"
                         if disposition == "INVALID_EXECUTION" else "DECISION_BEARING"),
        "cross_model_transfer_adjudicated": disposition != "INVALID_EXECUTION",
        "unadjudicated_note": (
            "The cross-model transfer question remains UNADJUDICATED, not negative: the proposed "
            "independent truth did not satisfy its forcing-independence requirement, so no "
            "quantitative statement about recovery of Xi is licensed in either direction."
            if disposition == "INVALID_EXECUTION" else None),
        "claim_ceiling": list(CLAIM_CEILING),
        "evidence_classification": [
            "CROSS_MODEL_NUMERICAL_VERIFICATION", "DETERMINISTIC_SYNTHETIC_GEOMETRY",
            "NOT_EXPERIMENTAL_VALIDATION", "NOT_REAL_PUCK_INFERENCE",
            "NOT_A_REGISTRY_STATUS_PROMOTION", "NOT_A_PUBLICATION_RESULT_YET"],
    }
    doc = _round(doc)
    doc["content_sha256"] = hashlib.sha256(
        json.dumps(doc, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    return doc


def summary_rows(doc):
    rows = [("role", "S", "kx", "kz", "R", "s", "Xi_field", "Xi_coupon", "Xi_hat",
             "Xi_hat_over_Xi_field", "c_field", "c_hat", "status")]
    for r in doc["cases"]:
        ap = r["aperture"] or {}
        xh, xf = r["inference"]["Xi_hat"], r["truth"]["Xi_field"]
        rows.append((r["role"], r["S"], ap.get("kx"), ap.get("kz"),
                     r["boundary"]["R"], r["boundary"]["s"], xf, r["truth"].get("Xi_coupon"),
                     xh, (xh / xf) if (xh and xf) else None,
                     r["truth"]["c_field"], r["inference"]["c_hat"], r["inference"]["status"]))
    return rows


def write():
    doc = assemble()
    out = REPO_ROOT / BUNDLE_REL
    out.mkdir(parents=True, exist_ok=True)
    (out / "result.json").write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n")
    rows = summary_rows(doc)
    (out / "summary.csv").write_text(
        "\n".join(",".join("" if v is None else str(v) for v in r) for r in rows) + "\n")
    try:
        figure(doc, out / "figures" / "primary.png")
    except Exception as exc:                       # figure is a reporting aid, not the result
        print("figure skipped: %s: %s" % (type(exc).__name__, exc))
    print("wrote %s (disposition=%s)" % (out / "result.json", doc["disposition"]))
    return doc


def verify():
    doc = assemble()
    p = REPO_ROOT / BUNDLE_REL / "result.json"
    if not p.exists():
        print("MISSING %s" % p)
        return 1
    have = json.loads(p.read_text())
    if have.get("content_sha256") != doc["content_sha256"]:
        print("DRIFT: result.json content hash %s != regenerated %s"
              % (have.get("content_sha256"), doc["content_sha256"]))
        return 1
    rows = summary_rows(doc)
    want = "\n".join(",".join("" if v is None else str(v) for v in r) for r in rows) + "\n"
    if (REPO_ROOT / BUNDLE_REL / "summary.csv").read_text() != want:
        print("DRIFT: summary.csv")
        return 1
    print("OK %s (disposition=%s)" % (TRANCHE_ID, doc["disposition"]))
    return 0


def figure(doc=None, path=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    doc = doc or assemble()
    path = pathlib.Path(path or (REPO_ROOT / BUNDLE_REL / "figures" / "primary.png"))
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(2, 2, figsize=(12.5, 9.6))

    # --- A: labelled fixture geometry — an x-z slice through EACH lane, stacked, so the
    #        mirrored segment order and the bridge are both visible in one panel.
    ax = axes[0, 0]
    S = S_COARSE
    ap = doc["aperture_freeze"]["selected"][len(doc["aperture_freeze"]["selected"]) // 2]
    mask, meta = build_fixture(S, aperture=ap, variant="mirror")
    y1 = (BASE["lane1_lo"] + BASE["lane1_hi"]) // 2 * S
    y2 = (BASE["lane2_lo"] + BASE["lane2_hi"]) // 2 * S
    sep = np.full((2, mask.shape[0]), 0.45)
    img = np.concatenate([mask[:, y2, :].T.astype(float), sep,
                          mask[:, y1, :].T.astype(float)], axis=0)
    ax.imshow(img, origin="lower", cmap="Greys", aspect="auto", interpolation="nearest",
              vmin=0, vmax=1)
    nz = mask.shape[2]
    for x, col, ls, lab in ((meta["x_node_in"], "tab:blue", "-", "node"),
                            (meta["x_node_out"], "tab:blue", "-", None),
                            (meta["x_meas_a"], "tab:red", "--", "flux plane a"),
                            (meta["x_meas_b"], "tab:red", ":", "flux plane b")):
        ax.axvline(x, color=col, lw=1.1, ls=ls, label=lab)
    axc = (meta["aperture_x"][0] + meta["aperture_x"][1]) / 2.0
    ax.annotate("bridge", xy=(axc, nz + 1), xytext=(axc, nz + 7), fontsize=8, color="tab:orange",
                ha="center", arrowprops=dict(arrowstyle="->", color="tab:orange", lw=1.2))
    ax.axhline(nz + 1, color="0.6", lw=0.8)
    ax.set_yticks([nz / 2, nz + 2 + nz / 2])
    ax.set_yticklabels(["lane 2\n(low→high)", "lane 1\n(high→low)"], fontsize=8)
    ax.set_title("A  virtual fixture: x–z slice through each lane (solid black)\n"
                 "S=%d, aperture kx=%d kz=%d · blue = node surfaces · red = outlet-flux planes"
                 % (S, ap["kx"], ap["kz"]), fontsize=9)
    ax.set_xlabel("x (lattice) — flow →")
    ax.legend(fontsize=7, loc="lower right", framealpha=0.9)

    # --- B: Xi_hat vs Xi_field, log-log, 1:1 and factor-of-two bounds ---
    ax = axes[0, 1]
    lo, hi = 1e-3, 1e2
    xs = np.array([lo, hi])
    ax.plot(xs, xs, "k-", lw=1, label="1:1")
    ax.plot(xs, 2 * xs, "k--", lw=0.8, label="factor 2")
    ax.plot(xs, 0.5 * xs, "k--", lw=0.8)
    ax.axvspan(XI_WINDOW_LO, XI_WINDOW_HI, color="tab:orange", alpha=0.12,
               label="WP6 1% window")
    for S, mk in ((S_COARSE, "o"), (S_FINE, "s")):
        pts = [(r["truth"]["Xi_field"], r["inference"]["Xi_hat"]) for r in doc["cases"]
               if r["role"] == "primary" and r["S"] == S and r["inference"]["Xi_hat"]]
        if pts:
            ax.plot(*zip(*pts), mk, ms=6, label="S=%d" % S)
    sw = [(r["Xi_field_swap"], r["Xi_hat_swap"]) for r in doc["path_swap"]
          if r.get("Xi_hat_swap") and r.get("Xi_field_swap")]
    if sw:
        ax.plot(*zip(*sw), "^", ms=6, mfc="none", label="path-swapped")
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlabel(r"$\Xi_{\rm field}$ (independent, in-situ)")
    ax.set_ylabel(r"$\hat\Xi$ (boundary inverse)")
    ax.set_title("B  cross-model recovery", fontsize=9)
    ax.legend(fontsize=7, loc="upper left")
    ax.grid(alpha=0.25, which="both")

    # --- C: boundary signatures ---
    ax = axes[1, 0]
    for S, mk in ((S_COARSE, "o"), (S_FINE, "s")):
        d = [(r["truth"]["Xi_field"], r["boundary"]["R"] - 1.0, r["boundary"]["s"] - 0.5)
             for r in doc["cases"] if r["role"] == "primary" and r["S"] == S]
        if d:
            x, r_, s_ = zip(*d)
            ax.plot(x, r_, mk, color="tab:blue", ms=5, label="R-1 (S=%d)" % S)
            ax.plot(x, s_, mk, color="tab:red", ms=5, mfc="none", label="s-1/2 (S=%d)" % S)
    d = [(r["Xi_field_swap"], r["R_swap"] - 1.0, r["s_swap"] - 0.5) for r in doc["path_swap"]
         if r.get("Xi_field_swap")]
    if d:
        x, r_, s_ = zip(*d)
        ax.plot(x, s_, "^", color="tab:red", ms=6, label="s-1/2 (swapped)")
    ax.axhline(0, color="k", lw=0.6)
    ax.set_xscale("log")
    ax.set_xlim(1e-2, 1e2)
    ax.set_xlabel(r"$\Xi_{\rm field}$"); ax.set_ylabel("boundary signature")
    ax.set_title("C  boundary signatures and path-swap sign reversal", fontsize=9)
    ax.legend(fontsize=7); ax.grid(alpha=0.25)

    # --- D: reduction diagnostics ---
    ax = axes[1, 1]
    d = [(r["truth"]["Xi_field"], r["truth"].get("Xi_coupon")) for r in doc["cases"]
         if r["role"] == "primary" and r["truth"].get("Xi_coupon")]
    if d:
        ax.plot(*zip(*d), "d", color="tab:purple", ms=6, label=r"$\Xi_{\rm coupon}$")
    ax.plot(xs, xs, "k-", lw=1)
    nu = [(r["truth"]["Xi_field"], r["truth"]["nonuniformity"]["node_in_sd_over_dP"])
          for r in doc["cases"] if r["role"] == "primary"]
    if nu:
        ax2 = ax.twinx()
        ax2.plot(*zip(*nu), "x", color="tab:gray", ms=5)
        ax2.set_ylabel("node pressure SD / ΔP", color="tab:gray", fontsize=8)
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
    ax.set_xlabel(r"$\Xi_{\rm field}$"); ax.set_ylabel(r"$\Xi_{\rm coupon}$")
    ax.set_title("D  subcomponent composability and node nonuniformity", fontsize=9)
    ax.legend(fontsize=7); ax.grid(alpha=0.25, which="both")

    invalid = doc["disposition"] == "INVALID_EXECUTION"
    fig.suptitle("RP-D-LC-001 — deterministic 3D lateral-coupling virtual fixture · "
                 "CROSS-MODEL NUMERICAL VERIFICATION ONLY · not experimental validation · "
                 "disposition: %s" % doc["disposition"], fontsize=9)
    if invalid:
        # Every recovery number on this figure is diagnostic only. Say so ON the figure, not in a
        # caption a reader can separate from it.
        fig.text(0.5, 0.5, "DIAGNOSTIC ONLY\nINVALID EXECUTION\ncross-model transfer NOT adjudicated",
                 fontsize=34, color="tab:red", alpha=0.16, ha="center", va="center",
                 rotation=24, zorder=10, fontweight="bold")
        fig.text(0.5, 0.945,
                 "EXECUTION VALIDITY FAILED — these panels are DIAGNOSTIC ONLY and may not be "
                 "quoted as recovery, mechanism-only transfer, or a weak quantitative success. "
                 "The cross-model transfer question is UNADJUDICATED, not negative.",
                 fontsize=8, color="tab:red", ha="center", va="top", wrap=True)
    fig.tight_layout(rect=(0, 0, 1, 0.93 if invalid else 0.96))
    fig.savefig(path, dpi=140)
    plt.close(fig)
    return path


def main(argv=None):
    ap = argparse.ArgumentParser(prog="puckworks.analysis.rp_d_lc_virtual_fixture")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--figure", action="store_true")
    a = ap.parse_args(argv)
    if a.write:
        write()
        return 0
    if a.verify:
        return verify()
    if a.figure:
        print(figure())
        return 0
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
