function monitor_init(p,x)
global CAMMON;
CAMMON=struct('rhs_calls',0,'jac_calls',0,'rhs_seconds',0,'jac_seconds',0, ...
 'rhs_max_trial_time',0,'jac_max_trial_time',0,'callback_calls',0, ...
 'callback_last_time',0,'last_snapshot_time',-Inf,'snapshots',0, ...
 'clock',tic(),'last_flush_wall',0,'params',p,'x',x, ...
 'A',linear_jacobian(p,x),'jac_all_sparse',true);
CAMMON.progress=fopen('progress.csv','w');
fprintf(CAMMON.progress,'kind,t_hat,wall_seconds,rhs_calls,jac_calls,rhs_seconds,jac_seconds,min_state,max_state\n');
fflush(CAMMON.progress);
end
