"""Generated artifacts — the corpus map, atlas, portfolio, indices, and the ChatGPT source pack.

Everything under `docs/insights/generated/` is written by this module and MUST NOT be hand-edited:
the tests fail on drift, exactly as the Paper-3 evidence graph's generated matrix does. Curate the
authorities (registry, cards, manifest, claims); regenerate the rest.

**No wall-clock timestamp appears in any tracked artifact.** The blueprint's snapshot manifest
carries `generated_at`, but a timestamp makes every regeneration a diff and makes drift
undetectable, which defeats the staleness control it was meant to serve (§19.7). The commit sha
plus a sha256 per input file identifies a snapshot strictly better — it changes when and only when
the inputs change. `--stamp-time` adds the timestamp for an untracked, human-facing export.
"""
from __future__ import annotations

import csv
import io

from . import candidates as CD, corpus_map as CM, schema as S, tension_atlas as TA

GENERATED_REL = "docs/insights/generated"
PACK_REL = GENERATED_REL + "/chatgpt_project"

BANNER = ("GENERATED by `python -m puckworks.insights write` from the live registry, "
          "docs/cards/, puckworks/data/MANIFEST.csv and docs/public/generated/claims.json. "
          "DO NOT EDIT BY HAND — edits are overwritten and fail the tests. Curate the "
          "authorities instead.")
_MD_BANNER = "<!-- " + BANNER + " -->"


def _csv(header, rows) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def build_all(commit: str | None = None) -> dict:
    """Build the whole Foundry state once. Returns the pieces every renderer needs."""
    corpus = CM.build(commit)
    tensions = TA.build(corpus)
    cands = CD.generate(corpus, tensions)      # assigns candidate_id back onto the tension rows
    return {"corpus": corpus, "tensions": tensions, "candidates": cands}


# ---- renderers ----------------------------------------------------------------------------


def render_corpus_map(state) -> str:
    return S.canonical_json(state["corpus"])


def render_observable_index(state) -> str:
    header, rows = CM.model_observable_matrix(state["corpus"])
    return _csv(header, rows)


def render_tension_atlas_csv(state) -> str:
    header = ["tension_id", "lens", "lens_letter", "difference_type", "entity_ids",
              "shared_observable", "shared_domain", "difference_summary", "evidence_basis",
              "candidate_discriminator", "data_available", "cheap_test_possible",
              "candidate_id", "human_status", "relation_confidences", "source_paths",
              "source_commit"]
    rows = []
    for t in state["tensions"]:
        rows.append([t.tension_id, t.lens, S.LENSES[t.lens], t.difference_type,
                     " | ".join(t.entity_ids), t.shared_observable, t.shared_domain,
                     t.difference_summary, t.evidence_basis, t.candidate_discriminator,
                     t.data_available, t.cheap_test_possible, t.candidate_id, t.human_status,
                     " | ".join(sorted(set(t.relation_confidences))),
                     " | ".join(sorted({p.source_path for p in t.provenance})),
                     state["corpus"]["commit"]])
    return _csv(header, rows)


def render_tension_atlas_md(state) -> str:
    corpus, tensions = state["corpus"], state["tensions"]
    by_lens = {}
    for t in tensions:
        by_lens.setdefault(t.lens, []).append(t)
    out = [_MD_BANNER, "", "# Tension atlas", "",
           "Commit `%s` · %d rows across %d lenses. A row is a source-bound statement that two "
           "parts of the corpus are comparable and differ in some declared respect. **A row is "
           "not a finding**, and `human_status` stays `UNREVIEWED` until a person rules."
           % (corpus["commit"][:10], len(tensions), len(by_lens)), ""]
    out += ["## Rows per lens", "", "| lens | blueprint §9 | rows |", "|---|---|---|"]
    for lens, rows in sorted(by_lens.items()):
        out.append("| %s | %s | %d |" % (lens, S.LENSES[lens], len(rows)))
    out += ["", "## Lenses not implemented", "",
            "Absent by decision, not oversight — each needs component EXECUTION this layer does "
            "not do:", ""]
    for lens, why in sorted(TA.DEFERRED_LENSES.items()):
        out.append("- **%s** — %s" % (lens, why))
    for lens, rows in sorted(by_lens.items()):
        out += ["", "## %s (%s)" % (lens, S.LENSES[lens]), ""]
        for t in rows:
            out.append("- **%s** [%s] %s" % (t.tension_id, t.difference_type,
                                             t.difference_summary))
            out.append("  - discriminator: %s · data: %s · cheap test: %s · candidate: %s"
                       % (t.candidate_discriminator or "—", t.data_available,
                          t.cheap_test_possible, t.candidate_id or "—"))
            out.append("  - sources: %s"
                       % ", ".join("`%s`" % p for p in sorted({q.source_path
                                                               for q in t.provenance})))
    return "\n".join(out) + "\n"


def render_portfolio_json(state) -> str:
    cands = state["candidates"]
    return S.canonical_json({
        "schema_version": S.SCHEMA_VERSION,
        "generator_version": CD.GENERATOR_VERSION,
        "commit": state["corpus"]["commit"],
        "summary": CD.portfolio_summary(cands),
        "candidates": [c.as_dict() for c in cands],
    })


def render_portfolio_md(state) -> str:
    corpus, cands = state["corpus"], state["candidates"]
    summary = CD.portfolio_summary(cands)
    out = [_MD_BANNER, "", "# Insight portfolio", "",
           "Commit `%s` · **%d candidates, all `SEED`**. Every candidate is a QUESTION with "
           "provenance. None is scored, ranked, or adjudicated: scoring is a human triage aid "
           "applied after a person reads the portfolio, and none of these has been read yet."
           % (corpus["commit"][:10], summary["total"]), "",
           "Next step is blueprint §12 Stage B — human triage down to 10–15, then three cheap "
           "screens. Do not start manuscript work on any of these.", "",
           "## By lens", "", "| lens | candidates |", "|---|---|"]
    for lens, n in summary["by_lens"].items():
        out.append("| %s | %d |" % (lens, n))
    out += ["", "## By audience track", "",
            "Tracks overlap by design — public value and academic value are separate axes "
            "(blueprint §3.6).", "", "| track | candidates |", "|---|---|"]
    for track, n in summary["by_audience_track"].items():
        out.append("| %s | %d |" % (track, n))
    out += ["", "## Candidates", ""]
    for c in cands:
        out += ["### %s — %s" % (c.id, c.title), "",
                "- **Question.** %s" % c.question,
                "- **Lens.** %s · tracks: %s" % (c.lens, ", ".join(c.audience_tracks)),
                "- **Cheap screen.** %s" % c.cheap_test,
                "- **Minimum figure.** %s" % c.minimum_figure,
                "- **Decision rule.**",
                "    - SURVIVE if %s" % c.survive_if,
                "    - RETIRE if %s" % c.retire_if,
                "    - INCONCLUSIVE if %s" % c.inconclusive_if,
                "- **Stop condition.** %s" % c.stop_condition,
                "- **Strongest alternative.** %s" % c.strongest_alternative,
                "- **Entities.** %s" % ", ".join("`%s`" % e for e in c.entity_ids[:10]) +
                (" … (%d total)" % len(c.entity_ids) if len(c.entity_ids) > 10 else ""),
                "- **Tension rows.** %s" % ", ".join(c.tension_ids[:12]) +
                (" … (%d total)" % len(c.tension_ids) if len(c.tension_ids) > 12 else ""),
                "- **Status.** %s" % c.status, ""]
    return "\n".join(out) + "\n"


def render_evidence_lineage_index(state) -> str:
    """Per-dataset lineage: the manifest's own wording, the derived tags, and the consumers."""
    corpus = state["corpus"]
    consumers = {}
    for r in CM.relations_of(corpus, "CALIBRATED_FROM"):
        consumers.setdefault(r["target"], []).append(r["source"].split(":", 1)[-1])
    claims = {}
    for r in CM.relations_of(corpus, "SUPPORTS_CLAIM"):
        claims.setdefault(r["source"], []).append(r["target"].split(":", 1)[-1])

    header = ["dataset_id", "source_card_as_written", "source_card_resolved",
              "validation_strength_verbatim", "derived_lineage_tags", "uncertainty_retained",
              "extraction_method", "same_source_consumers", "claims_using_it", "caveat_verbatim"]
    rows = []
    for d in sorted(CM.entities_of(corpus, "dataset"), key=lambda e: e["id"]):
        a = d["attrs"]
        rows.append([d["label"], a.get("source_card", ""), a.get("source_card_resolved", ""),
                     a.get("validation_strength", ""), " | ".join(a.get("lineage_tags", [])),
                     a.get("uncertainty_retained", ""), a.get("extraction_method", ""),
                     " | ".join(sorted(set(consumers.get(d["id"], [])))),
                     " | ".join(sorted(set(claims.get(d["id"], [])))), a.get("caveat", "")])
    return _csv(header, rows)


def render_closure_index(state) -> str:
    """Per-calibration-component closure index (blueprint §15.3)."""
    corpus = state["corpus"]
    cand_by_entity = {}
    for c in state["candidates"]:
        for e in c.entity_ids:
            cand_by_entity.setdefault(e, []).append(c.id)

    header = ["closure_component", "stage", "provenance_class", "evidence_strength_verbatim",
              "declared_validity_range_verbatim", "gates", "runtime_consumers_same_stage",
              "candidate_ids"]
    runtime_by_stage = {}
    for m in CM.entities_of(corpus, "model"):
        if m["attrs"].get("execution_role") == "runtime":
            runtime_by_stage.setdefault(m["attrs"].get("stage"), []).append(m["label"])
    rows = []
    for m in sorted(CM.entities_of(corpus, "model"), key=lambda e: e["id"]):
        a = m["attrs"]
        if a.get("execution_role") != "calibration":
            continue
        rows.append([m["label"], a.get("stage", ""), a.get("provenance_class", ""),
                     a.get("evidence_strength", ""), a.get("valid_range", ""),
                     " | ".join(a.get("gates", [])),
                     " | ".join(sorted(runtime_by_stage.get(a.get("stage"), []))),
                     " | ".join(sorted(set(cand_by_entity.get(m["id"], []))))])
    return _csv(header, rows)


def render_public_claim_inventory(state) -> str:
    """What the repository has ALREADY said in public — the duplicate-proposal guard (§19.3)."""
    corpus = state["corpus"]
    out = [_MD_BANNER, "", "# Public claim inventory", "",
           "Commit `%s` · %d generated claims. Read before proposing any public story: a "
           "candidate that restates one of these is a duplicate, not an insight."
           % (corpus["commit"][:10], len(CM.entities_of(corpus, "claim"))), ""]
    for c in sorted(CM.entities_of(corpus, "claim"), key=lambda e: e["id"]):
        a = c["attrs"]
        out += ["## %s — %s" % (a.get("claim_id"), a.get("headline")), "",
                "- **Question.** %s" % a.get("public_question"),
                "- **Badge.** `%s` · **evidence strength (verbatim).** `%s`"
                % (a.get("badge"), a.get("evidence_strength")),
                "- **Validity.** %s" % a.get("validity_range"),
                "- **Primary caveat.** %s" % a.get("primary_caveat"),
                "- **Datasets.** %s" % ", ".join("`%s`" % d
                                                 for d in a.get("dataset_manifest_ids", [])),
                "- **Producer.** `%s`" % a.get("producer"), ""]
    return "\n".join(out) + "\n"


def render_snapshot(state) -> str:
    """`INSIGHT_SNAPSHOT.md` — the one file a reader (or a ChatGPT Project) opens first."""
    corpus, tensions, cands = state["corpus"], state["tensions"], state["candidates"]
    counts, summary = corpus["counts"], CD.portfolio_summary(cands)
    by_lens = {}
    for t in tensions:
        by_lens.setdefault(t.lens, []).append(t)

    out = [_MD_BANNER, "", "# Puckworks insight snapshot", "",
           "**Commit** `%s` · **schema** v%d · **generator** v%d"
           % (corpus["commit"], S.SCHEMA_VERSION, CM.GENERATOR_VERSION), "",
           "Every count below is generated from the tree at that commit (blueprint §4.3). "
           "Nothing here is an authority: follow `card_path` / `source_path` to the card, the "
           "manifest row, or the registry entry that owns each statement.", "",
           "## Corpus", "", "| entity kind | count |", "|---|---|"]
    for kind, n in counts["entities_by_kind"].items():
        out.append("| %s | %d |" % (kind, n))
    out += ["", "| relation type | count |", "|---|---|"]
    for rtype, n in counts["relations_by_type"].items():
        out.append("| %s | %d |" % (rtype, n))
    out += ["", "### Registered models by stage", "", "| stage | models |", "|---|---|"]
    for stage, n in counts["models_by_stage"].items():
        out.append("| %s | %d |" % (stage, n))
    out += ["", "### Registered models by evidence strength (registry wording, verbatim)", "",
            "| evidence_strength | models |", "|---|---|"]
    for ev, n in counts["models_by_evidence_strength"].items():
        out.append("| `%s` | %d |" % (ev, n))

    out += ["", "## Tension atlas", "",
            "%d rows across %d lenses." % (len(tensions), len(by_lens)), "",
            "| lens | rows |", "|---|---|"]
    for lens, rows in sorted(by_lens.items()):
        out.append("| %s | %d |" % (lens, len(rows)))
    out += ["", "Not implemented, by decision: %s."
            % ", ".join("**%s** (%s)" % (k, v.split(";")[0])
                        for k, v in sorted(TA.DEFERRED_LENSES.items())), ""]

    out += ["## Candidate portfolio", "",
            "**%d candidates, every one `SEED`.** None scored, ranked, or adjudicated."
            % summary["total"], "", "| lens | candidates |", "|---|---|"]
    for lens, n in summary["by_lens"].items():
        out.append("| %s | %d |" % (lens, n))

    out += ["", "## Existing public claims", "",
            "The repository has already published these; a candidate restating one is a "
            "duplicate:", ""]
    for c in sorted(CM.entities_of(corpus, "claim"), key=lambda e: e["id"]):
        out.append("- **%s** [`%s`] %s" % (c["attrs"].get("claim_id"), c["attrs"].get("badge"),
                                           c["attrs"].get("headline")))

    out += ["", "## Standing negative results", ""]
    for t in sorted(by_lens.get("negative_result", []), key=lambda x: x.tension_id):
        out.append("- %s" % t.difference_summary)

    out += ["", "## Build warnings", "",
            "%d warnings. These are corpus findings, not build failures — an unresolved card or "
            "an untraceable manifest cell is exactly the kind of thing the Foundry exists to "
            "surface." % len(corpus["warnings"]), ""]
    for w in corpus["warnings"]:
        out.append("- %s" % w)

    out += ["", "## Snapshot limitations", "",
            "- No component was EXECUTED. Every 'do they disagree' row records comparability, "
            "not a numerical comparison; matched-scenario execution is RP-A (ROADMAP §9).",
            "- The model/observable matrix is read from each card's `Interface mapping` section. "
            "Cards without that section contribute no cells and are listed in the build "
            "warnings.",
            "- Lineage tags are conservative keyword derivations that sit BESIDE the manifest's "
            "own wording; the verbatim cell is carried in `evidence_lineage_index.csv` and is "
            "the thing to quote.",
            "- No evidence label, badge, or validation rung anywhere in the repository was "
            "changed, promoted, or restated by this build.", ""]
    return "\n".join(out) + "\n"


# ---- artifact table + writer ---------------------------------------------------------------

#: `(relative path, renderer)`. The one place that says what the Foundry generates.
ARTIFACTS = (
    (GENERATED_REL + "/corpus_map.json", render_corpus_map),
    (GENERATED_REL + "/observable_index.csv", render_observable_index),
    (GENERATED_REL + "/tension_atlas.csv", render_tension_atlas_csv),
    (GENERATED_REL + "/tension_atlas.md", render_tension_atlas_md),
    (GENERATED_REL + "/candidate_portfolio.json", render_portfolio_json),
    (GENERATED_REL + "/candidate_portfolio.md", render_portfolio_md),
    (GENERATED_REL + "/evidence_lineage_index.csv", render_evidence_lineage_index),
    (GENERATED_REL + "/closure_portability_index.csv", render_closure_index),
    (GENERATED_REL + "/public_claim_inventory.md", render_public_claim_inventory),
    (GENERATED_REL + "/INSIGHT_SNAPSHOT.md", render_snapshot),
)

#: The ChatGPT Project source pack (blueprint §14.2): numbered so upload order is obvious, and
#: capped well inside the 40-file Project limit. Files are COPIES of the artifacts above plus the
#: Project instructions, so the Project and the repo never disagree about what a snapshot said.
PACK = (
    ("01_INSIGHT_SNAPSHOT.md", GENERATED_REL + "/INSIGHT_SNAPSHOT.md"),
    ("02_corpus_map.json", GENERATED_REL + "/corpus_map.json"),
    ("03_tension_atlas.csv", GENERATED_REL + "/tension_atlas.csv"),
    ("04_candidate_portfolio.md", GENERATED_REL + "/candidate_portfolio.md"),
    ("05_candidate_portfolio.json", GENERATED_REL + "/candidate_portfolio.json"),
    ("06_evidence_lineage_index.csv", GENERATED_REL + "/evidence_lineage_index.csv"),
    ("07_model_observable_matrix.csv", GENERATED_REL + "/observable_index.csv"),
    ("08_closure_portability_index.csv", GENERATED_REL + "/closure_portability_index.csv"),
    ("09_public_claim_inventory.md", GENERATED_REL + "/public_claim_inventory.md"),
    ("10_PROJECT_INSTRUCTIONS.md", "docs/insights/chatgpt_project/PROJECT_INSTRUCTIONS.md"),
)


def generate_all(state=None, commit: str | None = None) -> dict:
    """`{relative path: content}` for every tracked artifact. Pure — writes nothing."""
    state = state or build_all(commit)
    return {rel: render(state) for rel, render in ARTIFACTS}


def snapshot_manifest(contents: dict, state, stamp_time: bool = False) -> dict:
    """Build integrity record (blueprint §8.6): commit, input hashes, output hashes."""
    man = {
        "repository": "trbrewer/puckworks",
        "commit": state["corpus"]["commit"],
        "schema_version": S.SCHEMA_VERSION,
        "generator_version": CM.GENERATOR_VERSION,
        "counts": {"entities": state["corpus"]["counts"]["entities_total"],
                   "relations": state["corpus"]["counts"]["relations_total"],
                   "tensions": len(state["tensions"]),
                   "candidates": len(state["candidates"]),
                   "warnings": len(state["corpus"]["warnings"])},
        "inputs": state["corpus"]["inputs"],
        "outputs": [{"path": rel, "sha256": S.sha256_text(text)}
                    for rel, text in sorted(contents.items())],
        "pack": [name for name, _ in PACK],
    }
    if stamp_time:
        # untracked, human-facing exports only — see the module docstring
        import datetime
        man["generated_at"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    return man


def write(commit: str | None = None, stamp_time: bool = False) -> list:
    """Write every tracked artifact, the snapshot manifest, and the ChatGPT pack. Returns paths."""
    state = build_all(commit)
    contents = generate_all(state)
    written = []
    for rel, text in sorted(contents.items()):
        p = S.REPO_ROOT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        written.append(rel)

    man_rel = GENERATED_REL + "/snapshot_manifest.json"
    man_path = S.REPO_ROOT / man_rel
    man_path.write_text(S.canonical_json(snapshot_manifest(contents, state, stamp_time)),
                        encoding="utf-8")
    written.append(man_rel)

    pack_dir = S.REPO_ROOT / PACK_REL
    pack_dir.mkdir(parents=True, exist_ok=True)
    for name, src_rel in PACK:
        src = S.REPO_ROOT / src_rel
        if not src.exists():
            continue
        (pack_dir / name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        written.append(PACK_REL + "/" + name)
    return written


def verify() -> list:
    """Check the tracked artifacts against the tree. Returns problems, most urgent first.

    Two signals, deliberately distinguished — a naive "regenerate and diff" check would conflate
    them and, worse, would fail on every commit, because the artifacts record the commit they were
    generated from and HEAD moves the moment they are committed:

      * **STALE** — an input file's sha256 differs from the one recorded in the snapshot manifest.
        The authorities moved; regenerate. Content comparison is meaningless until you do, so
        staleness short-circuits.
      * **DRIFT** — inputs are unchanged, but a tracked artifact's bytes differ from what the
        generator produces at the SAME commit. That means someone hand-edited a generated file.

    Regenerating at the manifest's stored commit is what makes DRIFT mean "hand-edited" rather
    than "committed since".
    """
    import json
    man_path = S.REPO_ROOT / (GENERATED_REL + "/snapshot_manifest.json")
    if not man_path.exists():
        return ["MISSING: %s/snapshot_manifest.json (run `python -m puckworks.insights write`)"
                % GENERATED_REL]
    stored = json.loads(man_path.read_text(encoding="utf-8"))

    current = {d["path"]: d["sha256"] for d in CM._input_hashes()}
    recorded = {d["path"]: d["sha256"] for d in stored.get("inputs", [])}
    problems = []
    for path in sorted(set(recorded) | set(current)):
        if path not in current:
            problems.append("STALE: input %s has been removed since the snapshot" % path)
        elif path not in recorded:
            problems.append("STALE: input %s is new since the snapshot" % path)
        elif recorded[path] != current[path]:
            problems.append("STALE: input %s changed since the snapshot" % path)
    if problems:
        return problems + ["-> run `python -m puckworks.insights write` to regenerate"]

    contents = generate_all(commit=stored.get("commit", ""))
    for rel, text in sorted(contents.items()):
        p = S.REPO_ROOT / rel
        if not p.exists():
            problems.append("MISSING: %s (run `python -m puckworks.insights write`)" % rel)
        elif p.read_text(encoding="utf-8") != text:
            problems.append("DRIFT: %s was hand-edited — regenerate instead" % rel)
    # The pack is a gitignored re-export, so its ABSENCE is normal (a fresh clone has never run
    # `write`). Only a pack that exists and disagrees with its source is a problem.
    for name, src_rel in PACK:
        pack_file = S.REPO_ROOT / PACK_REL / name
        src = S.REPO_ROOT / src_rel
        if not (pack_file.exists() and src.exists()):
            continue
        if pack_file.read_text(encoding="utf-8") != src.read_text(encoding="utf-8"):
            problems.append("PACK_DRIFT: %s/%s differs from %s — re-run `write`"
                            % (PACK_REL, name, src_rel))
    return problems
